//! Deterministic in-memory ingestion of exact Verified Chat artifact bytes.

use agentmage_capability_knowledge::{
    PdfExtractionProfile, PresentationProfile, SpreadsheetProfile, WordConversionProfile,
    extract_docx_to_sidecar, extract_pdf_to_pages, inspect_pptx, inspect_xlsx,
};
use agentmage_kernel_contracts::{
    CONTRACT_SCHEMA_VERSION, CanonicalArtifactIngestionResult, CanonicalArtifactReference,
    CanonicalArtifactTransformation, CanonicalByteRange, CanonicalIngestionDisposition,
    RuntimeArtifactId, WorkspaceId, WorkspacePath,
};
use sha2::{Digest, Sha256};

/// Stable parser failure without source content.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ArtifactIngestionError {
    /// Source identity, digest, media type, or bytes were inconsistent.
    InvalidInput,
    /// A parser rejected malformed, encrypted, unsafe, or oversized content.
    ParseFailed(&'static str),
    /// A derivative could not be encoded within the artifact boundary.
    EncodingFailed,
}

impl ArtifactIngestionError {
    /// Returns a stable content-free code.
    #[must_use]
    pub const fn code(self) -> &'static str {
        match self {
            Self::InvalidInput => "engineering.ingestion.input.invalid",
            Self::ParseFailed(code) => code,
            Self::EncodingFailed => "engineering.ingestion.encoding.failed",
        }
    }
}

/// Pure ingestion plan whose generated bytes have no authority until separately persisted.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ArtifactIngestionPlan {
    /// Terminal schema-bound ingestion result.
    pub result: CanonicalArtifactIngestionResult,
    /// Transformation provenance when a derivative was produced.
    pub transformation: Option<CanonicalArtifactTransformation>,
    /// Media type of the generated derivative.
    pub derivative_media_type: Option<String>,
    /// Exact deterministic derivative bytes.
    pub derivative_bytes: Option<Vec<u8>>,
}

struct ParsedDerivative {
    transformer_id: &'static str,
    transformer_version: &'static str,
    media_type: String,
    bytes: Vec<u8>,
    warnings: Vec<String>,
    disposition: CanonicalIngestionDisposition,
}

/// Parses one exact captured source without filesystem, network, or execution effects.
pub fn plan_artifact_ingestion(
    artifact_id: &RuntimeArtifactId,
    media_type: &str,
    source_sha256: &str,
    source: &[u8],
) -> Result<ArtifactIngestionPlan, ArtifactIngestionError> {
    if source.is_empty()
        || source_sha256 != sha256(source)
        || media_type.is_empty()
        || media_type.len() > 128
    {
        return Err(ArtifactIngestionError::InvalidInput);
    }
    let ingestion_id = format!(
        "ingestion:{}",
        &sha256(format!("{}:{source_sha256}", artifact_id.as_str()).as_bytes())[..32]
    );
    let source_reference = CanonicalArtifactReference {
        artifact_id: artifact_id.as_str().to_owned(),
        sha256: source_sha256.to_owned(),
        byte_length: source.len() as u64,
    };
    let parsed = match parse(media_type, source_sha256, source) {
        Ok(parsed) => parsed,
        Err(ArtifactIngestionError::ParseFailed(code)) => {
            return Ok(ArtifactIngestionPlan {
                result: CanonicalArtifactIngestionResult {
                    schema_version: CONTRACT_SCHEMA_VERSION,
                    ingestion_id,
                    artifact_id: artifact_id.as_str().to_owned(),
                    disposition: CanonicalIngestionDisposition::Failed,
                    source: Some(source_reference),
                    transformation_ids: Vec::new(),
                    warnings: Vec::new(),
                    error_code: Some(code.to_owned()),
                    terminal: true,
                },
                transformation: None,
                derivative_media_type: None,
                derivative_bytes: None,
            });
        }
        Err(error) => return Err(error),
    };
    let Some(parsed) = parsed else {
        return Ok(ArtifactIngestionPlan {
            result: CanonicalArtifactIngestionResult {
                schema_version: CONTRACT_SCHEMA_VERSION,
                ingestion_id,
                artifact_id: artifact_id.as_str().to_owned(),
                disposition: CanonicalIngestionDisposition::Unsupported,
                source: Some(source_reference),
                transformation_ids: Vec::new(),
                warnings: vec!["engineering.ingestion.parser.unavailable".to_owned()],
                error_code: Some("engineering.ingestion.format.unsupported".to_owned()),
                terminal: true,
            },
            transformation: None,
            derivative_media_type: None,
            derivative_bytes: None,
        });
    };
    if parsed.bytes.is_empty() {
        return Err(ArtifactIngestionError::EncodingFailed);
    }
    let transformation_id = format!(
        "transformation:{}",
        &sha256(
            format!(
                "{}:{source_sha256}:{}:{}",
                artifact_id.as_str(),
                parsed.transformer_id,
                parsed.transformer_version
            )
            .as_bytes()
        )[..32]
    );
    let transformation = CanonicalArtifactTransformation {
        schema_version: CONTRACT_SCHEMA_VERSION,
        transformation_id: transformation_id.clone(),
        artifact_id: artifact_id.as_str().to_owned(),
        transformer_id: parsed.transformer_id.to_owned(),
        transformer_version: parsed.transformer_version.to_owned(),
        input_sha256: source_sha256.to_owned(),
        output_sha256: Some(sha256(&parsed.bytes)),
        source_ranges: vec![CanonicalByteRange {
            start_byte: 0,
            end_byte_exclusive: source.len() as u64,
        }],
        warnings: parsed.warnings.clone(),
        reproducible: true,
    };
    Ok(ArtifactIngestionPlan {
        result: CanonicalArtifactIngestionResult {
            schema_version: CONTRACT_SCHEMA_VERSION,
            ingestion_id,
            artifact_id: artifact_id.as_str().to_owned(),
            disposition: parsed.disposition,
            source: Some(source_reference),
            transformation_ids: vec![transformation_id],
            warnings: parsed.warnings,
            error_code: None,
            terminal: true,
        },
        transformation: Some(transformation),
        derivative_media_type: Some(parsed.media_type),
        derivative_bytes: Some(parsed.bytes),
    })
}

fn parse(
    media_type: &str,
    source_sha256: &str,
    source: &[u8],
) -> Result<Option<ParsedDerivative>, ArtifactIngestionError> {
    let path = artifact_path(source_sha256)?;
    match media_type.split(';').next().unwrap_or(media_type).trim() {
        "application/pdf" => {
            let report =
                extract_pdf_to_pages(&path, source, &PdfExtractionProfile::strict_default())
                    .map_err(|error| ArtifactIngestionError::ParseFailed(error.code()))?;
            let warnings = report
                .limitations
                .iter()
                .map(|item| item.reason_code.clone())
                .collect();
            derivative(
                "agentmage-pdf-extractor",
                "1",
                &report,
                warnings,
                if report.extraction_complete {
                    CanonicalIngestionDisposition::Parsed
                } else {
                    CanonicalIngestionDisposition::Partial
                },
            )
        }
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document" => {
            let report =
                extract_docx_to_sidecar(&path, source, &WordConversionProfile::strict_default())
                    .map_err(|error| ArtifactIngestionError::ParseFailed(error.code()))?;
            derivative(
                "agentmage-word-ooxml",
                "1",
                &report,
                report
                    .fidelity_warnings
                    .iter()
                    .map(|warning| warning.reason_code.clone())
                    .collect(),
                CanonicalIngestionDisposition::Parsed,
            )
        }
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" => {
            let report = inspect_xlsx(path, source, &SpreadsheetProfile::default())
                .map_err(|error| ArtifactIngestionError::ParseFailed(error.code()))?;
            let warnings = report
                .findings
                .iter()
                .map(|item| item.reason_code.clone())
                .collect();
            let disposition = if report.inspection_complete && report.safe_for_analysis {
                CanonicalIngestionDisposition::Parsed
            } else {
                CanonicalIngestionDisposition::Partial
            };
            derivative(
                "agentmage-spreadsheet-ooxml",
                "1",
                &report,
                warnings,
                disposition,
            )
        }
        "application/vnd.openxmlformats-officedocument.presentationml.presentation" => {
            let report = inspect_pptx(path, source, &PresentationProfile::default())
                .map_err(|error| ArtifactIngestionError::ParseFailed(error.code()))?;
            let warnings = report
                .findings
                .iter()
                .map(|item| item.reason_code.clone())
                .collect();
            let disposition = if report.inspection_complete && report.safe_for_reuse {
                CanonicalIngestionDisposition::Parsed
            } else {
                CanonicalIngestionDisposition::Partial
            };
            derivative(
                "agentmage-presentation-ooxml",
                "1",
                &report,
                warnings,
                disposition,
            )
        }
        "application/json" | "application/ld+json" | "application/x-ipynb+json" => {
            let parsed: serde_json::Value = serde_json::from_slice(source).map_err(|_| {
                ArtifactIngestionError::ParseFailed("engineering.ingestion.json.malformed")
            })?;
            let bytes =
                serde_json::to_vec(&parsed).map_err(|_| ArtifactIngestionError::EncodingFailed)?;
            Ok(Some(ParsedDerivative {
                transformer_id: "agentmage-json-canonicalizer",
                transformer_version: "1",
                media_type: "application/json".to_owned(),
                bytes,
                warnings: Vec::new(),
                disposition: CanonicalIngestionDisposition::Parsed,
            }))
        }
        value if value.starts_with("text/") => {
            std::str::from_utf8(source).map_err(|_| {
                ArtifactIngestionError::ParseFailed("engineering.ingestion.text.invalid_utf8")
            })?;
            Ok(Some(ParsedDerivative {
                transformer_id: "agentmage-utf8-identity",
                transformer_version: "1",
                media_type: value.to_owned(),
                bytes: source.to_vec(),
                warnings: Vec::new(),
                disposition: CanonicalIngestionDisposition::Parsed,
            }))
        }
        _ => Ok(None),
    }
}

fn derivative<T: serde::Serialize>(
    transformer_id: &'static str,
    transformer_version: &'static str,
    report: &T,
    warnings: Vec<String>,
    disposition: CanonicalIngestionDisposition,
) -> Result<Option<ParsedDerivative>, ArtifactIngestionError> {
    let bytes = serde_json::to_vec(report).map_err(|_| ArtifactIngestionError::EncodingFailed)?;
    Ok(Some(ParsedDerivative {
        transformer_id,
        transformer_version,
        media_type: "application/vnd.agentmage.parsed+json".to_owned(),
        bytes,
        warnings,
        disposition,
    }))
}

fn artifact_path(source_sha256: &str) -> Result<WorkspacePath, ArtifactIngestionError> {
    // This content-addressed path is descriptive parser provenance. WorkspacePath carries no
    // descriptor, ambient root, or filesystem authority, and every parser remains in-memory.
    WorkspacePath::new(
        WorkspaceId::from_raw("verified-artifact-parser"),
        ["artifacts", source_sha256],
    )
    .map_err(|_| ArtifactIngestionError::InvalidInput)
}

fn sha256(bytes: &[u8]) -> String {
    let mut encoded = String::with_capacity(64);
    for byte in Sha256::digest(bytes) {
        use std::fmt::Write as _;
        let _ = write!(encoded, "{byte:02x}");
    }
    encoded
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn json_derivative_is_deterministic_and_source_bound() {
        let source = br#"{ "answer": 42, "items": [1, 2] }"#;
        let artifact_id = RuntimeArtifactId::from_raw("artifact:json");
        let first =
            plan_artifact_ingestion(&artifact_id, "application/json", &sha256(source), source)
                .expect("valid JSON");
        let second =
            plan_artifact_ingestion(&artifact_id, "application/json", &sha256(source), source)
                .expect("valid JSON again");
        assert_eq!(first, second);
        assert_eq!(
            first.result.disposition,
            CanonicalIngestionDisposition::Parsed
        );
        assert_eq!(
            first.derivative_bytes.as_deref(),
            Some(br#"{"answer":42,"items":[1,2]}"#.as_slice())
        );
        assert_eq!(
            first.transformation.expect("transformation").source_ranges[0].end_byte_exclusive,
            source.len() as u64
        );
    }

    #[test]
    fn unsupported_and_malformed_inputs_are_truthful() {
        let artifact_id = RuntimeArtifactId::from_raw("artifact:binary");
        let bytes = b"opaque";
        let unsupported = plan_artifact_ingestion(
            &artifact_id,
            "application/octet-stream",
            &sha256(bytes),
            bytes,
        )
        .expect("unsupported is a terminal result");
        assert_eq!(
            unsupported.result.disposition,
            CanonicalIngestionDisposition::Unsupported
        );
        assert!(unsupported.derivative_bytes.is_none());
        let malformed =
            plan_artifact_ingestion(&artifact_id, "application/json", &sha256(bytes), bytes)
                .expect("parse failures are terminal records");
        assert_eq!(
            malformed.result.error_code.as_deref(),
            Some("engineering.ingestion.json.malformed")
        );
        assert_eq!(
            malformed.result.disposition,
            CanonicalIngestionDisposition::Failed
        );
    }
}
