#!/usr/bin/env python3
"""Generate and validate the closed Sprint 61 PDF generation review records."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Final


ROOT: Final = Path(__file__).resolve().parents[1]
CORPUS: Final = ROOT / "docs/verification/sprint-61-pdf-generation-corpus.json"
MANIFEST: Final = ROOT / "docs/verification/sprint-61-pdf-dependency-manifest.json"


def groups() -> dict[str, tuple[str, list[str]]]:
    return {
        "inspection": (
            "61.1.1.1",
            [
                "inspection accepts only caller-supplied bytes and a canonical path",
                "title author subject keywords creator producer and dates are bounded",
                "custom metadata retains key names without custom values",
                "page count binds reopened extraction when extraction is available",
                "internal destinations remain inert",
                "external URI targets remain inert",
                "remote-document launch JavaScript and submit actions block safe reuse",
                "form names and value-presence state are inventoried without values",
                "page images retain object identity dimensions filters and encoded digest",
                "embedded files and automatic actions block safe reuse",
                "encrypted input returns a blocked inventory without password handling",
                "malformed structures fail closed",
                "safe reuse is reproducible from completeness encryption and findings",
                "inspection performs no file network or process effect",
            ],
        ),
        "generation": (
            "61.1.1.2",
            [
                "report identity output path metadata geometry and blocks are closed",
                "output proposals require a nonempty PDF filename",
                "HTML content is escaped",
                "HTML declares a deny-by-default content security policy",
                "HTML admits only self or data images and self fonts",
                "tables preserve cell order and header state",
                "internal links resolve only to generated pages",
                "text form fields require unique safe names",
                "PDF bytes are deterministic for an exact request",
                "PDF metadata uses caller-controlled fixed values without a clock",
                "PDF output reopens through the bounded inspector",
                "generated active content prevents return",
                "the pinned base-font profile rejects unsupported characters",
                "source Markdown digest remains exact when present",
                "raw HTML from Markdown remains escaped inert text",
                "Markdown fidelity limitations remain visible",
                "generated bytes and serialized records are hash-bound",
                "generation performs no file network or child-process effect",
            ],
        ),
        "redaction": (
            "61.1.1.4",
            [
                "redaction accepts only an exactly reproducible AgentMage report specification",
                "arbitrary in-place PDF redaction is not claimed",
                "source PDF and HTML hashes must reproduce before redaction",
                "targets are exact case-sensitive caller-authorized strings",
                "raw targets are omitted from the retained receipt",
                "metadata fields are regenerated without targets",
                "paragraph heading list table and link labels are regenerated without targets",
                "form names labels defaults and values are regenerated without targets",
                "the output is a full regeneration rather than an incremental update",
                "HTML bytes are scanned for every target",
                "raw PDF bytes are scanned for every target",
                "parsed PDF names strings dictionaries arrays and streams are scanned",
                "reopened metadata forms and extracted text are scanned",
                "cross-reference and EOF counts reject appended incremental updates",
                "any residue fails closed",
                "visual review remains required after machine residue checks",
                "source and output identities remain distinct",
                "redaction performs no file network or child-process effect",
            ],
        ),
        "visual": (
            "61.1.1.4",
            [
                "visual comparison consumes externally supplied decoded RGBA pages",
                "renderer executable and font manifests are hash-bound in the profile",
                "platform and renderer evidence class must match",
                "page pixels bind exact SHA-256 values",
                "page dimensions and total decoded bytes are bounded",
                "pixel count channel delta and difference bounds are deterministic",
                "pagination clipping overlap font table and image observations are explicit",
                "redaction-mask failures are explicit",
                "reading-order and accessibility observations are explicit",
                "incomplete observations fail machine completion",
                "synthetic fixtures can never satisfy release evidence",
                "ambiguous differences require human review",
                "native evidence is not inferred from synthetic evidence",
                "the core comparator never launches a renderer",
                "comparison performs no file network or process effect",
            ],
        ),
        "diagram": (
            "61.1.1.3",
            [
                "offline Mermaid observations bind exact source and SVG digests",
                "the package name version license executable and lock file are exact",
                "the external adapter must report network denial and no remote assets",
                "nonzero renderer exit status rejects",
                "SVG is parsed as XML under a byte and depth ceiling",
                "script foreign-object iframe object and embed elements reject",
                "event-handler attributes reject",
                "HTTP HTTPS FTP file JavaScript and protocol-relative references reject",
                "document types reject",
                "passive fragment references remain admissible",
                "validation launches no renderer",
                "the Mermaid package remains development-only and is not a product renderer",
            ],
        ),
        "runtime_record": (
            "61.1.2/61.1.3",
            [
                "PDF inspection schema is closed and versioned",
                "generated PDF report schema is closed and versioned",
                "redaction receipt schema is closed and versioned",
                "visual comparison schema is closed and versioned",
                "offline diagram projection schema is closed and versioned",
                "byte hash drift rejects",
                "inspection path and source binding drift rejects",
                "residue count and completion drift rejects",
                "synthetic visual completion drift rejects",
                "unknown fields and effect broadening reject",
            ],
        ),
        "external_blocker": (
            "61.1",
            [
                "Sprint 60 remains an upstream blocker",
                "no admitted product PDF rasterizer exists",
                "no admitted product Mermaid execution adapter exists",
                "no native Fedora rendering evidence exists",
                "no native Ubuntu rendering evidence exists",
                "no native Windows 11 rendering evidence exists",
                "no retained Apple Silicon macOS rendering evidence exists",
                "no installed-product accessibility evidence exists",
                "no independent native-boundary review exists",
                "merge and split workflows remain unimplemented",
                "arbitrary-PDF secure redaction remains unsupported",
                "approved OCR execution remains absent",
                "manual fuzzing remains explicitly deferred",
                "Sprint 61 remains blocked while required evidence is absent",
            ],
        ),
    }


def expected_cases() -> list[dict[str, str]]:
    cases = []
    for category, (requirement, expectations) in groups().items():
        for index, expected in enumerate(expectations, 1):
            cases.append(
                {
                    "case_id": f"pdf61-{category}-{index:02d}",
                    "category": category,
                    "expected": expected,
                    "requirement": requirement,
                }
            )
    return cases


def expected_corpus() -> dict[str, Any]:
    cases = expected_cases()
    return {
        "schema_version": 1,
        "record_type": "sprint_61_pdf_generation_corpus",
        "story_id": "61.1",
        "legacy_story_id": "S-051",
        "case_count": len(cases),
        "cases": cases,
        "executable_sprint_61_rust_fixture_count": 15,
        "executable_all_pdf_rust_fixture_count": 21,
        "runtime_schema_count": 7,
        "native_render_fixture_count": 0,
        "network_enabled": False,
        "filesystem_mutation_enabled": False,
        "product_renderer_execution_enabled": False,
        "release_completion_claimed": False,
    }


def expected_manifest() -> dict[str, Any]:
    return {
        "schema_version": 1,
        "record_type": "sprint_61_pdf_dependency_manifest",
        "story_id": "61.1",
        "admitted_production_dependencies": [
            {
                "capabilities": [
                    "bounded-extraction",
                    "deterministic-basic-generation",
                    "metadata-inspection",
                    "regeneration-redaction",
                ],
                "cargo_checksum_sha256": "5e2ec995d822e05cabc3f06d196ee43650af3fe4fe38012cacb35e0c3d113b68",
                "default_features": False,
                "license": "MIT",
                "name": "lopdf",
                "version": "0.44.0",
            }
        ],
        "development_only_dependencies": [
            {
                "capability": "documentation-mermaid-validation",
                "license": "MIT",
                "name": "@mermaid-js/mermaid-cli",
                "version": "11.16.0",
                "product_runtime_admitted": False,
            }
        ],
        "unadmitted_product_components": [
            {"capability": "pdf-native-rendering", "reason_code": "pdf.renderer.not-admitted", "state": "blocked"},
            {"capability": "mermaid-product-execution", "reason_code": "pdf.mermaid.product-adapter-not-admitted", "state": "blocked"},
            {"capability": "pdf-ocr", "reason_code": "pdf.ocr.package-model-not-admitted", "state": "blocked"},
        ],
        "required_first_ga_platforms": ["fedora", "ubuntu", "windows11-x64"],
        "retained_post_ga_platforms": ["macos-apple-silicon"],
        "executed_core_platforms": ["fedora-x86_64"],
        "executed_native_renderer_platforms": [],
        "cross_platform_acceptance_complete": False,
        "independent_native_review_complete": False,
    }


def validate(corpus: Any, manifest: Any) -> list[str]:
    failures = []
    if corpus != expected_corpus():
        failures.append("Sprint 61 PDF generation corpus drifted")
    if manifest != expected_manifest():
        failures.append("Sprint 61 PDF dependency manifest drifted")
    encoded = json.dumps([corpus, manifest], sort_keys=True).lower()
    for prohibited in (
        "credential_value",
        "secret_value",
        "private_key",
        "access_token",
        "raw_document",
        "absolute_workspace_path",
        "native_renderer_complete",
        "release_approved",
    ):
        if prohibited in encoded:
            failures.append(f"prohibited review-record field: {prohibited}")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    arguments = parser.parse_args()
    if arguments.write:
        CORPUS.parent.mkdir(parents=True, exist_ok=True)
        CORPUS.write_text(json.dumps(expected_corpus(), indent=2) + "\n", encoding="utf-8")
        MANIFEST.write_text(json.dumps(expected_manifest(), indent=2) + "\n", encoding="utf-8")
    if not CORPUS.is_file() or not MANIFEST.is_file():
        print("error: Sprint 61 PDF review records are missing")
        return 1
    failures = validate(
        json.loads(CORPUS.read_text(encoding="utf-8")),
        json.loads(MANIFEST.read_text(encoding="utf-8")),
    )
    if failures:
        for failure in failures:
            print(f"error: {failure}")
        return 1
    print(
        "Sprint 61 PDF generation records validated: "
        f"{expected_corpus()['case_count']} cases, 1 production parser/generator, "
        "1 development-only diagram tool, 3 blocked product capability classes"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
