#!/usr/bin/env python3
"""Generate and validate the closed Sprint 63 reconciliation review records."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Final


ROOT: Final = Path(__file__).resolve().parents[1]
CORPUS: Final = ROOT / "docs/verification/sprint-63-reconciliation-corpus.json"
MANIFEST: Final = ROOT / "docs/verification/sprint-63-reconciliation-dependency-manifest.json"


def groups() -> dict[str, tuple[str, list[str]]]:
    return {
        "json_parse": ("63.1.1.1", [
            "exact source path and bytes are hash-bound", "empty JSON rejects", "malformed JSON rejects",
            "trailing input rejects", "duplicate object keys reject at every depth",
            "prototype-like keys reject", "null boolean integer decimal string array and object types remain distinct",
            "finite IEEE-754 round-trip number normalization is declared", "non-finite numbers reject",
            "source bytes depth nodes and strings are bounded", "object keys serialize in stable lexical order",
            "canonical bytes and digest are exact", "closed schema any null boolean number and string rules validate",
            "closed schema array length and item rules validate", "closed schema object property and required rules validate",
            "closed schema additional properties can fail", "schema issues retain canonical pointers and reason codes",
            "schema validity is recomputed from issues", "schema failure does not mutate or guess source data",
            "parsing performs no file network or execution effect",
        ]),
        "json_redaction_compare": ("63.1.1.1/63.1.1.2", [
            "redaction policy identity is closed", "redaction pointers are strict sorted and unique",
            "redaction key names are strict sorted and unique", "invalid pointer escapes reject",
            "missing pointer targets reject", "global key redaction traverses arrays and objects",
            "removed values retain canonical hashes without raw values", "redacted output is full regeneration",
            "redacted canonical bytes and digest are exact", "source canonical and source byte digests remain distinct",
            "redaction performs no file network or execution effect", "object comparison uses canonical key order",
            "array comparison uses stable indexes", "missing-left and missing-right reasons bind hash presence",
            "type mismatch and value mismatch bind both hashes", "equal subtrees produce no difference",
            "differences are pointer ordered", "exact-match state is recomputed from differences",
            "comparison retains exact left and right source hashes", "comparison performs no file network or execution effect",
        ]),
        "workbook_generation": ("63.1.1.3", [
            "generation accepts only a content-minimized comparison", "output path must be a canonical XLSX path",
            "workbook method and profile identities are closed", "left and right source hashes remain exact",
            "summary sheet records source and method identity", "reconciliation sheet records key hashes and closed reasons",
            "source row numbers and differing fields remain ordered", "raw compared values are absent",
            "caller title remains escaped inline text", "caller text cannot become a formula",
            "digest cells use text formatting", "header and body styles are explicit", "column widths are explicit",
            "one structured table covers reconciliation output", "one closed reason-list validation is present",
            "one static reason-count chart is present", "formula policy admits only generator-owned summary formulas",
            "formula text is hash-bound", "formula cached values derive deterministically from comparison",
            "calculation mode is manual with no automatic execution", "XLSX bytes are deterministic",
            "generated bytes reopen through the bounded direct inspector", "unsafe reopen findings fail generation",
            "formula error cells fail scanning", "source workbooks and tables remain unchanged",
            "generation returns a proposal without file network or execution effects",
        ]),
        "native_verification": ("63.1.1.4/63.1.3.4", [
            "external observation binds exact workbook digest", "application name and version are exact",
            "executable package and font manifests are hash-bound", "platform and evidence class are closed",
            "formula observations are cell ordered", "every expected formula identity must be observed",
            "formula errors fail recalculation checks", "structural failures fail presentation checks",
            "visual failures fail presentation checks", "accessibility failures fail presentation checks",
            "incomplete observations fail presentation checks", "synthetic fixtures never pass native machine checks",
            "synthetic fixtures always require human review", "failed native observations require human review",
            "the core validator performs no file network or execution effect",
        ]),
        "runtime_records": ("63.1.2/63.1.3", [
            "structured JSON document schema is closed and versioned", "structured JSON redaction schema is closed and versioned",
            "structured JSON comparison schema is closed and versioned", "generated reconciliation workbook schema is closed and versioned",
            "spreadsheet verification report schema is closed and versioned", "canonical JSON value drift rejects",
            "redaction byte and ledger drift rejects", "comparison reason and aggregate drift reject",
            "workbook byte path source and reopen drift reject", "synthetic native-completion drift rejects",
            "unknown fields and broadened effects reject",
        ]),
        "external_blocker": ("63.1", [
            "Sprint 62 remains blocked upstream", "numeric tolerance reconciliation is not implemented",
            "financial rounding policy is not implemented", "many-to-many allocation is not implemented",
            "stale-data policy is not implemented", "arbitrary-precision decimal reconciliation is not implemented",
            "encrypted workbook handling is not implemented", "legacy XLS handling is not implemented",
            "native office recalculation evidence is absent", "Fedora native visual evidence is absent",
            "Ubuntu native visual evidence is absent", "Windows native visual evidence is absent",
            "retained macOS native visual evidence is absent", "installed accessibility evidence is absent",
            "independent review is absent", "manual fuzzing remains explicitly deferred",
            "Sprint 63 remains blocked while required evidence is absent",
        ]),
    }


def expected_cases() -> list[dict[str, str]]:
    return [{"case_id": f"data63-{category}-{index:02d}", "category": category, "expected": expected, "requirement": requirement} for category, (requirement, expectations) in groups().items() for index, expected in enumerate(expectations, 1)]


def expected_corpus() -> dict[str, Any]:
    cases = expected_cases()
    return {
        "schema_version": 1, "record_type": "sprint_63_reconciliation_corpus",
        "story_id": "63.1", "legacy_story_id": "S-052", "case_count": len(cases), "cases": cases,
        "json_rust_fixture_count": 5, "workbook_rust_fixture_count": 4,
        "runtime_schema_count": 5, "implemented_method_count": 6,
        "native_office_fixture_count": 0, "network_enabled": False,
        "filesystem_mutation_enabled": False, "formula_execution_enabled": False,
        "release_completion_claimed": False,
    }


def expected_manifest() -> dict[str, Any]:
    return {
        "schema_version": 1, "record_type": "sprint_63_reconciliation_dependency_manifest",
        "story_id": "63.1",
        "admitted_production_dependencies": [
            {"name": "quick-xml", "version": "0.41.0", "license": "MIT", "cargo_checksum_sha256": "e660451e55124f798a69a5af3f49ccfbefbd41910eefd25caf2393e1f3473ec1", "capability": "bounded-open-xml-parsing"},
            {"name": "serde_json", "version": "1.0.151", "license": "MIT OR Apache-2.0", "cargo_checksum_sha256": "c841b55ecdae098c80dcae9cf767f6f8a0c2cdb3416bbef72181df4d0fe73f14", "capability": "strict-json-parsing-and-canonical-serialization"},
            {"name": "zip", "version": "8.6.0", "license": "MIT", "cargo_checksum_sha256": "2d04a6b5381502aa6087c94c669499eb1602eb9c5e8198e534de571f7154809b", "capability": "deterministic-xlsx-container-generation"},
        ],
        "unadmitted_product_components": [
            {"capability": "native-office-recalculation", "reason_code": "reconciliation.native-recalc.not-admitted", "state": "blocked"},
            {"capability": "native-office-rendering", "reason_code": "reconciliation.native-render.not-admitted", "state": "blocked"},
            {"capability": "arbitrary-precision-financial-methods", "reason_code": "reconciliation.decimal-method.not-implemented", "state": "blocked"},
        ],
        "required_first_ga_platforms": ["fedora", "ubuntu", "windows11-x64"],
        "retained_post_ga_platforms": ["macos-apple-silicon"],
        "executed_core_platforms": ["fedora-x86_64"], "executed_native_office_platforms": [],
        "cross_platform_acceptance_complete": False, "independent_review_complete": False,
    }


def validate(corpus: Any, manifest: Any) -> list[str]:
    failures = []
    if corpus != expected_corpus(): failures.append("Sprint 63 reconciliation corpus drifted")
    if manifest != expected_manifest(): failures.append("Sprint 63 dependency manifest drifted")
    encoded = json.dumps([corpus, manifest], sort_keys=True).lower()
    for prohibited in ("credential_value", "secret_value", "private_key", "access_token", "raw_json", "raw_workbook", "absolute_workspace_path", "native_office_complete", "release_approved"):
        if prohibited in encoded: failures.append(f"prohibited review-record field: {prohibited}")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser(); parser.add_argument("--write", action="store_true"); arguments = parser.parse_args()
    if arguments.write:
        CORPUS.parent.mkdir(parents=True, exist_ok=True)
        CORPUS.write_text(json.dumps(expected_corpus(), indent=2) + "\n", encoding="utf-8")
        MANIFEST.write_text(json.dumps(expected_manifest(), indent=2) + "\n", encoding="utf-8")
    if not CORPUS.is_file() or not MANIFEST.is_file(): print("error: Sprint 63 review records are missing"); return 1
    failures = validate(json.loads(CORPUS.read_text()), json.loads(MANIFEST.read_text()))
    if failures:
        for failure in failures: print(f"error: {failure}")
        return 1
    print(f"Sprint 63 reconciliation records validated: {expected_corpus()['case_count']} cases")
    return 0


if __name__ == "__main__": raise SystemExit(main())
