"""Exact test-only ownership of whole Rust source files for developer scans.

Not a Rust parser or permission boundary. A file is test-only only when it is
referenced at least once and every recognized reference to it comes from
test-only code: an inline test module, an exact `#[cfg(test)]` module
declaration, or another test-only file. Everything else stays production.

Every `mod`, `include!` and `path` token in code must belong to a recognized
reference, and production references are resolved as the compiler resolves
them: a default declaration names both `name.rs` and `name/mod.rs`, and
children of a file loaded through `#[path]` or `include!` live beside it. A
module name that a `macro_rules!` body, a `$` fragment, a `cfg_attr`
or any other attribute naming `path` could produce is treated as ambiguous,
and any ambiguity disables every file exemption. Modules generated by
procedural macros or build scripts are outside what this lexical check can
see, so the native compiler and separate closed-boundary checks remain required.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Iterable, Mapping

from scripts.rust_source_audit import _code_mask


# The shared audit pattern plus an optional visibility qualifier, which does
# not change a `cfg(test)` module's compilation. Kept local so the strict-local
# and effect-boundary scans keep their existing exemption set.
TEST_MODULE = re.compile(
    r"(?m)^#\[cfg\((?:test|all\(test,\s*target_os\s*=\s+\))\)\]"
    r"\s*\n(?:pub(?:\((?:crate|super)\))?[ \t]+)?mod\s+[A-Za-z_][A-Za-z_0-9]*\s*\{"
)
ATTRIBUTE = re.compile(r"#\[[^\[\]\n]*\]")
DECLARATION = re.compile(
    r"(?P<attributes>(?:#\[[^\[\]\n]*\][ \t]*\n?[ \t]*)*)"
    r"(?<![A-Za-z0-9_])(?:pub(?:\([a-z]+\))?[ \t]+)?"
    r"(?P<keyword>mod)[ \t]+(?:r#)?(?P<name>[A-Za-z_][A-Za-z_0-9]*)[ \t]*;"
)
PATH_ATTRIBUTE = re.compile(r'#\[path[ \t]*=[ \t]*"(?P<value>[^"\n]*)"\]')
INCLUDE = re.compile(r'include!\([ \t]*"(?P<value>[^"\n]*)"[ \t]*\)')
PLAIN_FILE = re.compile(r"[A-Za-z0-9_]+\.rs")
# Every such token in code must belong to a recognized reference.
FILE_MODULE_TOKEN = re.compile(r"(?<![A-Za-z0-9_])mod\s+(?:r#)?[A-Za-z_][A-Za-z_0-9]*\s*;")
INCLUDE_TOKEN = re.compile(r"(?<![A-Za-z0-9_])include!")
PATH_WORD = re.compile(r"(?<![A-Za-z0-9_])path(?![A-Za-z0-9_])")
MOD_WORD = re.compile(r"(?<![A-Za-z0-9_])mod(?![A-Za-z0-9_])")
FRAGMENT_MODULE = re.compile(r"(?<![A-Za-z0-9_])mod\s*\$")
MACRO_RULES = re.compile(r"(?<![A-Za-z0-9_])macro_rules\s*!\s*(?:r#)?[A-Za-z_][A-Za-z_0-9]*\s*")
MOD_RS_FILES = frozenset({"lib.rs", "main.rs", "mod.rs"})
CLOSING = {"{": "}", "(": ")", "[": "]"}


class AmbiguousReference(ValueError):
    """A module or include reference could not be resolved with certainty."""


def _test_module_spans(mask: str) -> list[tuple[int, int]] | None:
    """Complete inline test modules; None when one is unbalanced."""
    spans: list[tuple[int, int]] = []
    cursor = 0
    for module in TEST_MODULE.finditer(mask):
        if module.start() < cursor:
            continue
        index = module.end()
        depth = 1
        while index < len(mask) and depth:
            depth += (mask[index] == "{") - (mask[index] == "}")
            index += 1
        if depth:
            return None
        spans.append((module.start(), index))
        cursor = index
    return spans


def _balanced_end(mask: str, start: int) -> int | None:
    """End offset after the group opened at `start`; None when unbalanced."""
    stack = [CLOSING[mask[start]]]
    index = start + 1
    while index < len(mask) and stack:
        character = mask[index]
        if character in CLOSING:
            stack.append(CLOSING[character])
        elif character in CLOSING.values():
            if character != stack.pop():
                return None
        index += 1
    return None if stack else index


def _attribute_spans(mask: str) -> list[tuple[int, int]] | None:
    spans = []
    for match in re.finditer(r"#!?\s*\[", mask):
        end = _balanced_end(mask, match.end() - 1)
        if end is None:
            return None
        spans.append((match.start(), end))
    return spans


def _macro_bodies(mask: str) -> list[tuple[int, int]] | None:
    spans = []
    for match in MACRO_RULES.finditer(mask):
        if match.end() >= len(mask) or mask[match.end()] not in CLOSING:
            return None
        end = _balanced_end(mask, match.end())
        if end is None:
            return None
        spans.append((match.end(), end))
    return spans


def _depth(mask: str, offset: int) -> int:
    return mask.count("{", 0, offset) - mask.count("}", 0, offset)


def _is_code(source: str, mask: str, offset: int) -> bool:
    return mask[offset] == source[offset] and not mask[offset].isspace()


def _references(path: Path, source: str, beside: bool) -> list[tuple[Path, bool, str]]:
    """Return (target, test_context, kind) for one file's references.

    `beside` resolves default child modules next to the file, as for `lib.rs`,
    `main.rs`, `mod.rs` and any file loaded through `#[path]` or `include!`.
    """
    mask = _code_mask(source)
    if mask is None:
        raise AmbiguousReference(f"{path}: malformed lexical source")
    spans = _test_module_spans(mask)
    if spans is None:
        raise AmbiguousReference(f"{path}: unbalanced test module")
    attribute_spans = _attribute_spans(mask)
    macros = _macro_bodies(mask)
    if attribute_spans is None or macros is None:
        raise AmbiguousReference(f"{path}: unbalanced attribute or macro body")
    if FRAGMENT_MODULE.search(mask) or any(
        MOD_WORD.search(mask, start, end) for start, end in macros
    ):
        raise AmbiguousReference(f"{path}: macro-generated module declaration")

    def in_test_module(offset: int) -> bool:
        return any(start <= offset < end for start, end in spans)

    references: list[tuple[Path, bool, str]] = []
    declared_at: set[int] = set()
    path_attributes_at: set[int] = set()
    for match in DECLARATION.finditer(source):
        keyword = match.start("keyword")
        if not _is_code(source, mask, keyword):
            continue
        declared_at.add(keyword)
        attributes = list(ATTRIBUTE.finditer(match["attributes"]))
        start = match.start("attributes")
        path_attributes_at.update(
            start + item.start() for item in attributes if item.group(0).startswith("#[path")
        )
        if any(not _is_code(source, mask, start + item.start()) for item in attributes):
            raise AmbiguousReference(f"{path}: module attribute is not plain code")
        texts = [item.group(0) for item in attributes]
        paths = [PATH_ATTRIBUTE.fullmatch(text) for text in texts]
        declared = [value["value"] for value in paths if value]
        if any(text.startswith("#[path") for text, value in zip(texts, paths) if not value):
            raise AmbiguousReference(f"{path}: unrecognized path attribute")
        if len(declared) > 1:
            raise AmbiguousReference(f"{path}: repeated path attribute")
        depth = _depth(mask, keyword)
        if depth and not in_test_module(keyword):
            # Inline production modules change relative resolution; never guess it.
            raise AmbiguousReference(f"{path}: nested production module declaration")
        if declared:
            if not PLAIN_FILE.fullmatch(declared[0]):
                raise AmbiguousReference(f"{path}: non-sibling path attribute")
            target = path.parent / declared[0]
        elif depth:
            # Only reachable inside a test module; its default file is test-owned.
            target = path.parent / path.stem / f"{match['name']}.rs"
        elif beside:
            target = path.parent / f"{match['name']}.rs"
        else:
            target = path.parent / path.stem / f"{match['name']}.rs"
        test_context = in_test_module(keyword) or (depth == 0 and "#[cfg(test)]" in texts)
        references.append((target, test_context, "path" if declared else "default"))
        if not declared:
            # The compiler also accepts `name/mod.rs` for a default declaration.
            references.append((target.parent / target.stem / "mod.rs", test_context, "default-mod"))
    included_at: set[int] = set()
    for match in INCLUDE.finditer(source):
        if not _is_code(source, mask, match.start()):
            continue
        if not PLAIN_FILE.fullmatch(match["value"]):
            raise AmbiguousReference(f"{path}: non-sibling include")
        included_at.add(match.start())
        references.append((path.parent / match["value"], in_test_module(match.start()), "include"))
    for pattern, recognized, kind in (
        (FILE_MODULE_TOKEN, declared_at, "module declaration"),
        (INCLUDE_TOKEN, included_at, "include"),
    ):
        for token in pattern.finditer(mask):
            if token.start() not in recognized:
                raise AmbiguousReference(f"{path}: unrecognized {kind}")
    for start, end in attribute_spans:
        # Only an exact plain `#[path = "..."]` on a recognized declaration may
        # name `path`; a `cfg_attr` or any other form could select another file.
        if PATH_WORD.search(mask, start, end) and start not in path_attributes_at:
            raise AmbiguousReference(f"{path}: unrecognized path attribute")
    return references


def test_only_files(sources: Mapping[Path, str]) -> frozenset[Path]:
    """Return files owned only by test code; raise when any reference is ambiguous."""
    initial = {
        path: _references(path, source, path.name in MOD_RS_FILES)
        for path, source in sources.items()
    }
    # `#[path]` and `include!` targets do not depend on how their owner was
    # loaded; the files they load resolve default children beside themselves.
    defaults = ("default", "default-mod")
    loaded_beside = {
        target for found in initial.values() for target, _, kind in found if kind not in defaults
    }
    loaded_by_default = {
        target for found in initial.values() for target, _, kind in found if kind in defaults
    }
    edges: list[tuple[Path, Path, bool]] = []
    for path, source in sources.items():
        found = initial[path]
        if path in loaded_beside and path.name not in MOD_RS_FILES:
            if path in loaded_by_default and any(kind in defaults for _, _, kind in found):
                raise AmbiguousReference(f"{path}: child modules depend on how it is loaded")
            found = _references(path, source, True)
        for target, _, kind in found:
            # The compiler refuses a module found at both default locations.
            if kind == "default" and target in sources and (
                target.parent / target.stem / "mod.rs"
            ) in sources:
                raise AmbiguousReference(f"{target}: module file exists at both default paths")
        edges.extend((path, target, test) for target, test, _ in found)
    test_only: set[Path] = set()
    while True:
        referenced: dict[Path, bool] = {}
        for owner, target, test in edges:
            in_test = test or owner in test_only
            referenced[target] = referenced.get(target, True) and in_test
        found = {
            path for path, only_test in referenced.items() if only_test and path in sources
        }
        if found == test_only:
            return frozenset(test_only)
        test_only = found


def _production_text(source: str) -> str:
    """Blank complete inline test modules, keeping line numbers and trailing items."""
    mask = _code_mask(source)
    spans = None if mask is None else _test_module_spans(mask)
    if not spans:
        return source
    result: list[str] = []
    cursor = 0
    for start, end in spans:
        result.append(source[cursor:start])
        result.append("\n" * source[start:end].count("\n"))
        cursor = end
    result.append(source[cursor:])
    return "".join(result)


def production_sources(paths: Iterable[Path]) -> dict[Path, str]:
    """Map each path to its production text for lexical neutrality scans.

    Exactly owned test-only files map to an empty string. Other files keep all
    production items, including any after an inline test module. If ownership
    is ambiguous anywhere, no whole file is exempted.
    """
    sources = {path: path.read_text(encoding="utf-8") for path in paths}
    try:
        exempt = test_only_files(sources)
    except AmbiguousReference:
        exempt = frozenset()
    return {
        path: "" if path in exempt else _production_text(source)
        for path, source in sources.items()
    }
