#!/usr/bin/env python3
"""Build truthful Sprint 141 productivity workflow evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/productivity_workflow.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-141/workflow-corpus.json","scripts/productivity_workflow_contract.py","tests/test_productivity_workflow_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_141_evidence.py","tests/test_sprint_141_evidence.py")
COMMANDS:Final=(("workflow-rust",("cargo","test","-p","agentmage-kernel-engine","productivity_workflow::tests","--lib")),("workflow-corpus",("python3","-m","unittest","tests.test_productivity_workflow_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_141_evidence")));FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"workflow_family_count":7,"node_kind_count":18,"attack_family_count":16,"failure_family_count":10,"fixture_case_count":5600,"unauthorized_effect_count":0,"duplicate_effect_count":0,"inferred_consent_count":0,"content_authority_count":0,"removal_authority_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-127-140-BLOCKED","owner":"141"},{"code":"BLOCKED_EXTERNAL","platform":"all native productivity provider accounts, authenticated Proton UI, accessibility surfaces, and independent epic-review environment","artifact":"untouched integrated identity, synchronization, autonomy, injection, uncertainty, accessibility, reviewer, strict-local, and removal evidence","action":"satisfy every Sprint 127-140 external tuple, then run AT-WFA-001, AT-PCAL-001, all applicable provider campaigns, RV-31, RV-32, and RV-35","credential":"all provider-specific credentials and user-established Proton session recorded by Sprints 127-140","payment":"provider subscription costs if applicable"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"immutable_compilation_complete":True,"current_policy_intersection_complete":True,"lifecycle_and_recovery_complete":True,"hostile_workflow_campaign_complete":True,"confirmed_calendar_workflow_complete":True,"native_integrated_campaign_complete":False,"epic_gate_closed":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_141_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprints_127_140_closed":False,"epic_12_closed":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=141,root=ROOT,output="artifacts/sprints/sprint-141/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-WFA-001","AT-WFA-001","AM-PCAL-001","AT-PCAL-001","SR-PRD-009","SR-PRD-012","RV-31","RV-32","RV-35"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
