#!/usr/bin/env python3
"""Build truthful Sprint 159 tiered-command and immutable-audit evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","TASKS.md","SECURITY-REVIEW.md","TRUSTED-OPERATIONS.md","CODEBASE-AUDIT.md","kernel/engine/src/lib.rs","kernel/engine/src/tiered_command_audit.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-159/tiered-command-audit-corpus.json","scripts/tiered_command_audit_contract.py","tests/test_tiered_command_audit_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_159_evidence.py","tests/test_sprint_159_evidence.py")
COMMANDS:Final=(("tiered-command-audit-rust",("cargo","test","-p","agentmage-kernel-engine","tiered_command_audit::tests","--lib")),("tiered-command-audit-corpus",("python3","-m","unittest","tests.test_tiered_command_audit_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_159_evidence")));FOCUSED_COMMANDS:Final=tuple(item[0]for item in COMMANDS[:3])
IMPLEMENTED:Final={"command_level_count":5,"command_semantic_count":14,"authority_attack_count":10,"owner_terminal_trigger_count":9,"repository_state_count":22,"audit_hazard_count":12,"authority_case_count":6300,"audit_case_count":792,"escape_count":0,"hidden_launch_count":0,"surviving_process_count":0,"canonical_mutation_count":0,"hosted_mutation_count":0,"raw_secret_count":0,"content_authority_count":0,"silent_omission_count":0,"parser_escape_count":0,"promotion_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-41-43-74-128-157-158-BLOCKED","owner":"159"},{"code":"BLOCKED_EXTERNAL","platform":"native Fedora, Ubuntu, and Windows command-worker, Owner-mode user-interface, accessibility, process-control, repository, and independent review environments","artifact":"untouched platform command semantics, constraint, authentication, warning, remaining-time, keyboard, screen-reader, focus, contrast, panic-stop, process-tree, repository-state, canonical-immutability, canary, cleanup, RV-36, RV-44, and RV-45 evidence","action":"satisfy upstream blockers, provision exact native platforms and repository fixtures, then run AT-AUT-002, AT-CLI-002, AT-CEN-001, AT-ROA-001, RV-36, RV-44, and RV-45 separately per platform","credential":"platform authentication, repository, container, package, network, accessibility, and independent reviewer credentials","payment":"platform, repository hosting, accessibility, container, package, network, or independent evaluator costs if applicable"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"tiered_authority_complete":True,"command_plan_complete":True,"owner_activation_complete":True,"owner_revocation_complete":True,"census_contract_complete":True,"canonical_immutability_complete":True,"hostile_content_isolation_complete":True,"native_platform_campaign_complete":False,"accessibility_campaign_complete":False,"rv36_44_45_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_159_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"tiered_command_promoted":False,"whole_codebase_audit_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=159,root=ROOT,output="artifacts/sprints/sprint-159/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-AUT-002","AM-CLI-002","AM-CEN-001","AM-ROA-001","AT-AUT-002","AT-CLI-002","AT-CEN-001","AT-ROA-001","SR-CMD-001","SR-CMD-004","SR-AUD-001","SR-AUD-004","RV-36","RV-44","RV-45"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
