#!/usr/bin/env python3
"""Build truthful Sprint 77 local desktop lifecycle evidence."""
from pathlib import Path
from typing import Final
try: from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError: from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT: Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS: Final=("Cargo.toml","Cargo.lock","shells/host/Cargo.toml","shells/host/src/lib.rs","shells/host/src/desktop_experience.rs","shells/host/src/desktop_lifecycle.rs","kernel/contracts/src/conversation.rs","schemas/runtime/thin-client-request.schema.json","schemas/runtime/thin-client-event.schema.json","docs/architecture/thin-client-boundary.md","docs/architecture/desktop-thin-client.md","docs/guides/desktop-status-recovery-packaging.md","docs/verification/sprint-77-desktop-lifecycle-corpus.json","artifacts/sprints/sprint-76/local-evidence-report.json","scripts/desktop_lifecycle_contract.py","tests/test_desktop_lifecycle_contract.py","supply-chain/dependency-hashes.sha256","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","scripts/sprint_evidence_recorder.py","scripts/sprint_77_evidence.py","tests/test_sprint_77_evidence.py")
COMMANDS: Final=(("desktop-lifecycle-rust-contract",("cargo","test","-p","agentmage-host","desktop_lifecycle::tests","--all-features")),("desktop-lifecycle-artifact-contract",("python3","-m","unittest","tests.test_desktop_lifecycle_contract")),("runtime-schema-contract",("npm","run","-s","schemas:test")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_77_evidence")))
FOCUSED_COMMANDS: Final=tuple(item[0] for item in COMMANDS[:2])
IMPLEMENTED: Final={"status_field_count":9,"single_writer_lease":True,"read_only_safe_mode":True,"local_asset_kind_count":5,"protocol_operation_count":6,"corpus_case_count":38,"telemetry_count":0,"advertisement_count":0,"remote_asset_count":0,"automatic_cloud_check_count":0,"direct_client_effect_count":0,"signed_package_present":False,"native_package_tested":False}
BLOCKERS: Final=({"code":"UPSTREAM-SPRINT-76-BLOCKED","owner":"77.1"},{"code":"SIGNED-NATIVE-DESKTOP-PACKAGES-ABSENT","owner":"77.1.2.1"},{"code":"NATIVE-DESKTOP-ACCESSIBILITY-RECOVERY-ABSENT","owner":"77.1.2.3"},{"code":"NATIVE-DESKTOP-SECURITY-EVIDENCE-ABSENT","owner":"77.1.3.4"})
VERIFICATION: Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"rust_test_count":8,"corpus_case_count":38,"direct_client_effect_count":0,"native_protocol_parity":False,"native_crash_injection":False,"native_accessibility":False,"clean_install":False,"independent_review":False,"sprint_gate_closed":False}
SUMMARY: Final={"local_sprint_77_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_76_closed":False,"signed_package_present":False,"native_package_tested":False,"native_accessibility_complete":False,"native_security_evidence_complete":False,"independent_review_present":False,"release_approval":False}
DEFINITION: Final=SprintEvidenceDefinition(sprint=77,root=ROOT,output="artifacts/sprints/sprint-77/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=("SR-PLT-001","SR-PLT-002","SR-PLT-003","SR-PLT-004","SR-PLT-005","SR-PLT-006","SR-PLT-007","SR-PLT-008","SR-PLT-009","SR-PLT-010","SR-ACC-001","SR-TST-007","SR-TST-008","SR-TST-009","SR-CIV-006","SR-CIV-007","SR-CIV-008","SR-CIV-009"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__": raise SystemExit(main(DEFINITION))
