#!/usr/bin/env python3
"""Build truthful Sprint 122 local Windows runtime-boundary evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","platforms/windows/Cargo.toml","platforms/windows/src/lib.rs","platforms/windows/src/runtime_boundary.rs","WINDOWS-BOUNDARIES.md","SECURITY-REVIEW.md","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-122/windows-runtime-corpus.json","scripts/windows_runtime_boundary.py","tests/test_windows_runtime_boundary.py","scripts/sprint_evidence_recorder.py","scripts/sprint_122_evidence.py","tests/test_sprint_122_evidence.py")
COMMANDS:Final=(("windows-rust-contract",("cargo","test","-p","agentmage-platform-windows","--lib")),("windows-runtime-corpus",("python3","-m","unittest","tests.test_windows_runtime_boundary")),("dependency-boundary-contract",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_122_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"path_case_count":1024,"sandbox_case_count":512,"state_attack_case_count":512,"recovery_case_count":512,"native_guest_execution_count":0,"observed_network_minutes":0,"packet_trace_count":0,"accessibility_run_count":0,"promoted_platform_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-121-BLOCKED","owner":"122"},{"code":"BLOCKED-EXTERNAL-WINDOWS-AT-WIN-001","owner":"122"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"path_contract_complete":True,"restricted_worker_contract_complete":True,"state_and_key_contract_complete":True,"model_contract_complete":True,"provider_worker_contract_complete":True,"native_path_campaign_complete":False,"strict_local_60_minute_complete":False,"native_accessibility_complete":False,"rv03_complete":False,"rv04_complete":False,"rv06_complete":False,"rv08_10_complete":False,"rv16_17_complete":False,"rv20_complete":False,"rv24_complete":False,"rv30_complete":False,"at_win_001_complete":False,"independent_human_review":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_122_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_121_closed":False,"windows_platform_supported":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=122,root=ROOT,output="artifacts/sprints/sprint-122/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=("AM-WIN-001","AT-WIN-001","SR-PLT-013","SR-PLT-014","SR-PLT-015","SR-PLT-016","SR-PLT-017","RV-03","RV-04","RV-06","RV-08","RV-09","RV-10","RV-16","RV-17","RV-20","RV-24","RV-30"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
