#!/usr/bin/env python3
"""Build and validate truthful Sprint 71 local evidence."""
from pathlib import Path
from typing import Final
try:
    from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:
    from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT: Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS: Final=("Cargo.toml","Cargo.lock","capabilities/knowledge/Cargo.toml","capabilities/knowledge/src/connected_connector.rs","capabilities/knowledge/src/github_provider.rs","capabilities/knowledge/src/lib.rs","schemas/runtime/github-auth-diagnostic.schema.json","schemas/runtime/github-read-receipt.schema.json","schemas/runtime/examples/github-auth-diagnostic.valid.json","schemas/runtime/examples/github-read-receipt.valid.json","scripts/validate_planning_schemas.mjs","tests/test_planning_schemas.mjs","supply-chain/dependency-hashes.sha256","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","docs/architecture/github-read-only-provider.md","docs/guides/github-provider-review.md","docs/verification/sprint-71-github-provider-corpus.json","docs/verification/sprint-71-github-dependency-manifest.json","docs/verification/sprint-71-local-results.md","scripts/github_provider_contract.py","tests/test_github_provider_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_71_evidence.py","tests/test_sprint_71_evidence.py")
COMMANDS: Final=(("github-unit",("cargo","test","-p","agentmage-capability-knowledge","github_provider::tests","--lib","--locked")),("github-contract",("python3","-m","unittest","tests.test_github_provider_contract")),("runtime-schema-contract",("npm","run","-s","schemas:test")),("github-strict-clippy",("cargo","clippy","-p","agentmage-capability-knowledge","--all-targets","--locked","--","-D","warnings")),("github-format",("cargo","fmt","--all","--","--check")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_71_evidence")))
FOCUSED_COMMANDS: Final=tuple(i[0] for i in COMMANDS[:3])
SECURITY_REQUIREMENTS: Final=("SR-ACC-002","SR-ACC-006","SR-DAT-002","SR-DAT-007","SR-NET-005","SR-NET-006","SR-OPS-001","SR-OPS-002","SR-OPS-003","SR-TST-004","SR-GIT-001","SR-GIT-009")
IMPLEMENTED: Final={"github_rust_fixture_count":4,"provider_corpus_case_count":58,"exact_auth_binding":True,"read_only_operation_count":4,"normalized_response_state_count":11,"runtime_schema_count":2,"actual_credential_derivation":False,"actual_provider_read":False,"network_client_count":0,"credential_material_count":0,"mutation_operation_count":0,"native_auth_campaign":False,"independent_review":False}
BLOCKERS: Final=({"code":"UPSTREAM-SPRINT-70-BLOCKED","owner":"71.1"},{"code":"CREDENTIAL-DERIVATION-AND-ACCOUNT-ABSENT","owner":"71.1.1.3"},{"code":"AUTHENTICATED-PROVIDER-READ-ABSENT","owner":"71.1.3.4"},{"code":"NATIVE-AUTH-SECURITY-CAMPAIGN-ABSENT","owner":"71.1.3.5"})
VERIFICATION: Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"provider_corpus_case_count":58,"normalized_response_state_count":11,"accepted_network_effect_count":0,"network_client_count":0,"credential_material_count":0,"mutation_operation_count":0,"native_auth_campaign":False,"independent_review":False,"sprint_gate_closed":False}
SUMMARY: Final={"local_sprint_71_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_70_closed":False,"credential_derivation_complete":False,"authenticated_provider_read_complete":False,"revocation_campaign_complete":False,"native_security_evidence_complete":False,"independent_review_present":False,"release_approval":False}
DEFINITION: Final=SprintEvidenceDefinition(sprint=71,root=ROOT,output="artifacts/sprints/sprint-71/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=SECURITY_REQUIREMENTS,implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__": raise SystemExit(main(DEFINITION))
