#!/usr/bin/env python3
"""Build truthful Sprint 72 local evidence."""
from pathlib import Path
from typing import Final
try: from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError: from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT: Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS: Final=("Cargo.toml","Cargo.lock","capabilities/knowledge/Cargo.toml","capabilities/knowledge/src/hosted_repository.rs","capabilities/knowledge/src/lib.rs","schemas/runtime/hosted-source-identity.schema.json","schemas/runtime/hosted-repository-view.schema.json","schemas/runtime/examples/hosted-source-identity.valid.json","schemas/runtime/examples/hosted-repository-view.valid.json","scripts/validate_planning_schemas.mjs","tests/test_planning_schemas.mjs","supply-chain/dependency-hashes.sha256","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","docs/architecture/hosted-repository-evidence.md","docs/guides/hosted-repository-evidence-review.md","docs/verification/sprint-72-hosted-repository-corpus.json","docs/verification/sprint-72-hosted-dependency-manifest.json","docs/verification/sprint-72-local-results.md","scripts/hosted_repository_contract.py","tests/test_hosted_repository_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_72_evidence.py","tests/test_sprint_72_evidence.py")
COMMANDS: Final=(("hosted-unit",("cargo","test","-p","agentmage-capability-knowledge","hosted_repository::tests","--lib","--locked")),("hosted-contract",("python3","-m","unittest","tests.test_hosted_repository_contract")),("runtime-schema-contract",("npm","run","-s","schemas:test")),("hosted-strict-clippy",("cargo","clippy","-p","agentmage-capability-knowledge","--all-targets","--locked","--","-D","warnings")),("hosted-format",("cargo","fmt","--all","--","--check")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_72_evidence")))
FOCUSED_COMMANDS: Final=tuple(x[0] for x in COMMANDS[:3])
IMPLEMENTED: Final={"rust_fixture_count":4,"corpus_case_count":64,"evidence_kind_count":25,"runtime_schema_count":2,"immutable_identity":True,"coverage_states":6,"actual_hosted_read":False,"hosted_local_comparison":False,"network_client_count":0,"git_client_count":0,"sensitive_payload_count":0,"mutation_operation_count":0,"native_campaign":False}
BLOCKERS: Final=({"code":"UPSTREAM-SPRINT-71-BLOCKED","owner":"72.1"},{"code":"HOSTED-ACCOUNT-AND-READ-ABSENT","owner":"72.1.3.4"},{"code":"NATIVE-HOSTED-SECURITY-CAMPAIGN-ABSENT","owner":"72.1.3.5"})
VERIFICATION: Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"corpus_case_count":64,"evidence_kind_count":25,"accepted_network_effect_count":0,"accepted_local_effect_count":0,"sensitive_payload_count":0,"mutation_operation_count":0,"native_campaign":False,"sprint_gate_closed":False}
SUMMARY: Final={"local_sprint_72_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_71_closed":False,"actual_hosted_read_complete":False,"hosted_local_comparison_complete":False,"native_security_evidence_complete":False,"independent_review_present":False,"release_approval":False}
DEFINITION: Final=SprintEvidenceDefinition(sprint=72,root=ROOT,output="artifacts/sprints/sprint-72/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=("SR-ACC-008","SR-AI-003","SR-AI-007","SR-AI-010","SR-NET-005","SR-NET-006","SR-OPS-001","SR-TST-004"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__": raise SystemExit(main(DEFINITION))
