#!/usr/bin/env python3
"""Build truthful Sprint 125 local integration evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","SECURITY-REVIEW.md","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-125/integrated-profile-corpus.json","scripts/integrated_delivery_profile_contract.py","tests/test_integrated_delivery_profile_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_125_evidence.py","tests/test_sprint_125_evidence.py")
COMMANDS:Final=(("integration-profile-contract",("python3","-m","unittest","tests.test_integrated_delivery_profile_contract")),("dependency-boundary-contract",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_125_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:2]);IMPLEMENTED:Final={"lifecycle_case_count":512,"attack_case_count":2048,"profile_boundary_count":49,"native_platform_count":0,"promoted_provider_path_count":0,"release_candidate_package_count":0,"enabled_profile_count":0,"review_vector_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-124-BLOCKED","owner":"125"},{"code":"BLOCKED-EXTERNAL-DELIVERY-WINDOWS-GATES","owner":"125"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"lifecycle_fixture_complete":True,"attack_recovery_fixture_complete":True,"profile_boundary_fixture_complete":True,"native_provider_lifecycle_complete":False,"native_platform_parity_complete":False,"release_candidate_complete":False,"all_profile_lifecycle_complete":False,"rv01_30_complete":False,"rv49_complete":False,"at_xte_001_complete":False,"at_win_001_complete":False,"g_delivery_closed":False,"g_windows_closed":False,"independent_decisions_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_125_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_124_closed":False,"delivery_gate_closed":False,"windows_gate_closed":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=125,root=ROOT,output="artifacts/sprints/sprint-125/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-XTE-001","AM-WIN-001","AT-XTE-001","AT-WIN-001","RV-01","RV-30","RV-49"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
