#!/usr/bin/env python3
"""Build truthful Sprint 117 local multi-vendor observability evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","kernel/engine/Cargo.toml","kernel/engine/src/lib.rs","kernel/engine/src/vendor_observability.rs","SECURITY-REVIEW.md","DELIVERY-SYSTEM.md","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-117/vendor-observability-corpus.json","scripts/vendor_observability_contract.py","tests/test_vendor_observability_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_117_evidence.py","tests/test_sprint_117_evidence.py")
COMMANDS:Final=(("vendor-rust-contract",("cargo","test","-p","agentmage-kernel-engine","vendor_observability::tests","--lib")),("vendor-corpus-contract",("python3","-m","unittest","tests.test_vendor_observability_contract")),("dependency-boundary-contract",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_117_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"provider_fixture_count":7,"object_fixture_count":10,"query_case_count":128,"attack_case_count":2048,"fault_case_count":512,"live_query_count":0,"tenant_crossover_count":0,"hidden_write_count":0,"promoted_provider_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-116-BLOCKED","owner":"117"},{"code":"BLOCKED-EXTERNAL-VENDOR-AT-OBS-001","owner":"117"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"exact_provider_identity":True,"namespaced_differences":True,"observe_authority_only":True,"published_read_matrices_complete":False,"at_obs_001_complete":False,"independent_human_review":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_117_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_116_closed":False,"live_provider_support":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=117,root=ROOT,output="artifacts/sprints/sprint-117/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=("AM-OBS-001","AT-OBS-001","SR-DEL-*","RV-23","RV-24","RV-27","RV-29"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
