#!/usr/bin/env python3
"""Build truthful Sprint 116 local telemetry evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","kernel/engine/Cargo.toml","kernel/engine/src/lib.rs","kernel/engine/src/telemetry_correlation.rs","SECURITY-REVIEW.md","DELIVERY-SYSTEM.md","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-116/telemetry-correlation-corpus.json","scripts/telemetry_correlation_contract.py","tests/test_telemetry_correlation_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_116_evidence.py","tests/test_sprint_116_evidence.py")
COMMANDS:Final=(("telemetry-rust-contract",("cargo","test","-p","agentmage-kernel-engine","telemetry_correlation::tests","--lib")),("telemetry-corpus-contract",("python3","-m","unittest","tests.test_telemetry_correlation_contract")),("dependency-boundary-contract",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_116_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"identity_count":14,"query_case_count":64,"correlation_case_count":128,"attack_case_count":2048,"fault_case_count":512,"live_query_count":0,"operation_authority_count":0,"causation_claim_count":0,"promoted_backend_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-115-BLOCKED","owner":"116"},{"code":"BLOCKED-EXTERNAL-OTEL-AT-OBS-001","owner":"116"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"bounded_queries":True,"inference_labeled":True,"uncertainty_preserved":True,"rv27_complete":False,"rv29_complete":False,"at_obs_001_complete":False,"independent_human_review":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_116_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_115_closed":False,"live_telemetry_support":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=116,root=ROOT,output="artifacts/sprints/sprint-116/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=("AM-OBS-001","AT-OBS-001","SR-DEL-004","SR-DEL-011","SR-DEL-014","RV-27","RV-29"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
