#!/usr/bin/env python3
"""Build truthful Sprint 97 local backup and migration evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","kernel/engine/Cargo.toml","kernel/engine/src/lib.rs","kernel/engine/src/backup_migration.rs","kernel/engine/src/operational_store.rs","docs/architecture/secret-store-encrypted-backup-format.md","docs/operations/maintenance-and-recovery.md","artifacts/sprints/sprint-11/story-11.1/secret-backup-format.json","artifacts/sprints/sprint-97/backup-migration-corpus.json","scripts/backup_migration_contract.py","tests/test_backup_migration_contract.py","supply-chain/dependency-hashes.sha256","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","scripts/sprint_evidence_recorder.py","scripts/sprint_97_evidence.py","tests/test_sprint_97_evidence.py")
COMMANDS:Final=(("backup-migration-rust-contract",("cargo","test","-p","agentmage-kernel-engine","backup_migration::tests","--lib")),("operational-backup-rust-contract",("cargo","test","-p","agentmage-kernel-engine","backup","--lib")),("backup-migration-artifact-contract",("python3","-m","unittest","tests.test_backup_migration_contract")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_97_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0] for i in COMMANDS[:3]);IMPLEMENTED:Final={"backup_domain_count":8,"attack_recovery_class_count":16,"case_count":64,"encrypted_store_backup_contract_count":1,"fresh_restore_candidate_contract_count":1,"native_cross_machine_migration_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-96-BLOCKED","owner":"97"},{"code":"NATIVE-COMPLETE-BACKUP-RESTORE-AND-CROSS-MACHINE-MIGRATION-ABSENT","owner":"97.1.1-97.1.3.4-97.AC2-97.AC5"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"case_count":64,"backup_domain_count":8,"secret_export_count":0,"native_cross_machine_migration_count":0,"supported_platform_migration_count":0,"independent_review":False,"sprint_gate_closed":False}
SUMMARY:Final={"local_sprint_97_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_96_closed":False,"complete_native_backup_restore":False,"cross_machine_migration_complete":False,"independent_review_present":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=97,root=ROOT,output="artifacts/sprints/sprint-97/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:2]),security_requirement_ids=("SR-DAT-005","SR-DAT-006","SR-DAT-007","SR-DAT-008","SR-DAT-009","SR-DAT-010","SR-DAT-011","SR-DAT-012","SR-SUP-002","SR-SUP-003","SR-SUP-004","SR-SUP-005","SR-SUP-006","SR-SUP-007","SR-SUP-008","SR-SUP-009","SR-SUP-010","SR-SUP-011","SR-SUP-012","SR-SUP-013","SR-OPS-006","SR-OPS-007","SR-OPS-008","SR-OPS-009","SR-OPS-010","SR-TST-003","SR-TST-005","SR-TST-007","SR-TST-008","SR-TST-009","SR-TST-010","SR-TST-011","RV-19","RV-21","RV-22"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
