#!/usr/bin/env python3
"""Build truthful Sprint 134 Gmail evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/communications_gmail.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-134/gmail-corpus.json","scripts/communications_gmail_contract.py","tests/test_communications_gmail_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_134_evidence.py","tests/test_sprint_134_evidence.py")
COMMANDS:Final=(("gmail-rust",("cargo","test","-p","agentmage-kernel-engine","communications_gmail::tests","--lib")),("gmail-corpus",("python3","-m","unittest","tests.test_communications_gmail_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_134_evidence")));FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"profile_count":6,"mutation_family_count":12,"fault_family_count":15,"fixture_case_count":4320,"unauthorized_effect_count":0,"duplicate_delivery_count":0,"removal_authority_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-133-BLOCKED","owner":"134"},{"code":"BLOCKED_EXTERNAL","platform":"Gmail test accounts and Google Cloud OAuth project","artifact":"untouched native account, history, push, delivery, security, reviewer, and removal evidence","action":"provision exact Gmail accounts/OAuth credentials and run AT-GML-001 plus RV-23 through RV-26 and RV-31 native campaigns","credential":"Google OAuth client and Gmail account credentials","payment":"Google Workspace or provider costs if applicable"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"gmail_identity_complete":True,"least_scope_complete":True,"exact_effect_complete":True,"history_completeness_complete":True,"recovery_and_removal_complete":True,"native_provider_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_134_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_133_closed":False,"native_gmail_support_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=134,root=ROOT,output="artifacts/sprints/sprint-134/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-GML-001","AT-GML-001","SR-PRD-005","SR-PRD-006","SR-PRD-007","RV-23","RV-24","RV-25","RV-26","RV-31"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
