#!/usr/bin/env python3
"""Build truthful Sprint 108 local multi-provider source evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","capabilities/knowledge/Cargo.toml","capabilities/knowledge/src/lib.rs","capabilities/knowledge/src/multi_provider_source.rs","DELIVERY-SYSTEM.md","artifacts/sprints/sprint-108/multi-provider-source-corpus.json","scripts/multi_provider_source_contract.py","tests/test_multi_provider_source_contract.py","supply-chain/dependency-hashes.sha256","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","scripts/sprint_evidence_recorder.py","scripts/sprint_108_evidence.py","tests/test_sprint_108_evidence.py")
COMMANDS:Final=(("multi-provider-source-rust-contract",("cargo","test","-p","agentmage-capability-knowledge","multi_provider_source::tests","--lib")),("multi-provider-source-artifact-contract",("python3","-m","unittest","tests.test_multi_provider_source_contract")),("dependency-boundary-contract",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_108_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0] for i in COMMANDS[:3]);IMPLEMENTED:Final={"provider_family_count":3,"published_tuple_count":4,"read_case_count":48,"effect_case_count":30,"prohibited_operation_count":6,"attack_case_count":2048,"recovery_case_count":512,"provider_request_count":0,"promoted_provider_count":0,"live_provider_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-107-BLOCKED","owner":"108"},{"code":"BLOCKED-EXTERNAL-AZURE-REPOS-GITLAB-AT-SRC-001","owner":"108"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"active_checkout_change_count":0,"credential_crossover_count":0,"stale_effect_count":0,"duplicate_effect_count":0,"reviewer":"scripts.multi_provider_source_contract","at_src_001_complete":False,"independent_human_review":False,"sprint_gate_closed":False}
SUMMARY:Final={"local_sprint_108_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_107_closed":False,"live_source_provider_support":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=108,root=ROOT,output="artifacts/sprints/sprint-108/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=tuple([f"SR-DEL-{i:03d}" for i in range(1,14)]+[f"RV-{i}" for i in range(23,28)]),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
