#!/usr/bin/env python3
"""Build truthful Sprint 140 document repository evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/document_repository_adapter.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-140/repository-corpus.json","scripts/document_repository_adapter_contract.py","tests/test_document_repository_adapter_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_140_evidence.py","tests/test_sprint_140_evidence.py")
COMMANDS:Final=(("repository-rust",("cargo","test","-p","agentmage-kernel-engine","document_repository_adapter::tests","--lib")),("repository-corpus",("python3","-m","unittest","tests.test_document_repository_adapter_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_140_evidence")));FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"profile_count":7,"operation_count":13,"mutation_family_count":16,"failure_family_count":12,"fixture_case_count":6720,"unauthorized_effect_count":0,"disclosure_count":0,"content_authority_count":0,"removal_authority_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-128-130-138-BLOCKED","owner":"140"},{"code":"BLOCKED_EXTERNAL","platform":"OneDrive, SharePoint, Google Drive, and Confluence test repositories and accounts","artifact":"untouched native object, version, permission, attachment, effect, security, reviewer, and removal evidence","action":"provision exact repositories/accounts/credentials and run AT-DREP-001 plus RV-23 through RV-26, RV-31, and RV-32 native campaigns","credential":"Microsoft Graph, Google Drive, and Atlassian credentials","payment":"provider subscription costs if applicable"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"repository_identity_complete":True,"operation_discovery_complete":True,"attachment_defenses_complete":True,"untrusted_content_complete":True,"reconciliation_and_removal_complete":True,"native_provider_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_140_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"native_repository_support_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=140,root=ROOT,output="artifacts/sprints/sprint-140/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-DREP-001","AT-DREP-001","SR-PRD-006","SR-PRD-007","RV-23","RV-24","RV-25","RV-26","RV-31","RV-32"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
