#!/usr/bin/env python3
"""Build truthful Sprint 79 local package runtime evidence."""
from pathlib import Path
from typing import Final
try: from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError: from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT: Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS: Final=("Cargo.toml","Cargo.lock","shells/host/Cargo.toml","shells/host/src/lib.rs","shells/host/src/capability_package.rs","shells/host/src/capability_package_runtime.rs","docs/guides/capability-package-trust.md","docs/guides/capability-package-runtime.md","docs/verification/sprint-78-capability-package-corpus.json","docs/verification/sprint-79-package-runtime-corpus.json","artifacts/sprints/sprint-78/local-evidence-report.json","scripts/capability_package_runtime_contract.py","tests/test_capability_package_runtime_contract.py","supply-chain/dependency-hashes.sha256","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","scripts/sprint_evidence_recorder.py","scripts/sprint_79_evidence.py","tests/test_sprint_79_evidence.py")
COMMANDS: Final=(("package-runtime-rust-contract",("cargo","test","-p","agentmage-host","capability_package_runtime::tests","--all-features")),("package-runtime-artifact-contract",("python3","-m","unittest","tests.test_capability_package_runtime_contract")),("runtime-schema-contract",("npm","run","-s","schemas:test")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_79_evidence")))
FOCUSED_COMMANDS: Final=tuple(item[0] for item in COMMANDS[:2])
IMPLEMENTED: Final={"hook_phase_count":10,"hook_outcome_count":4,"compatibility_dimension_count":7,"inventory_dimension_count":5,"prohibited_automation_count":6,"corpus_case_count":48,"installed_package_count":0,"enabled_package_count":0,"native_lifecycle_complete":False}
BLOCKERS: Final=({"code":"UPSTREAM-SPRINT-78-BLOCKED","owner":"79.1"},{"code":"NATIVE-PACKAGE-RECOVERY-AND-INDEPENDENT-REVIEW-ABSENT","owner":"79.1.3.5"})
VERIFICATION: Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"rust_test_count":8,"corpus_case_count":48,"installed_package_count":0,"enabled_package_count":0,"native_lifecycle_complete":False,"safe_mode_startup_observed":False,"independent_review":False,"sprint_gate_closed":False}
SUMMARY: Final={"local_sprint_79_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_78_closed":False,"native_package_recovery_complete":False,"native_security_evidence_complete":False,"independent_review_present":False,"release_approval":False}
DEFINITION: Final=SprintEvidenceDefinition(sprint=79,root=ROOT,output="artifacts/sprints/sprint-79/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=("SR-GOV-010","SR-PLT-011","SR-ACC-001","SR-SUP-002","SR-SUP-003","SR-SUP-004","SR-SUP-005","SR-SUP-006","SR-SUP-007","SR-SUP-008","SR-SUP-009","SR-SUP-010","SR-SUP-011","SR-SUP-012","SR-SUP-013","SR-OPS-008","SR-OPS-010","SR-TST-011"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
