#!/usr/bin/env python3
"""Build truthful Sprint 167 isolated lab evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","TASKS.md","SECURITY-REVIEW.md","MODEL-PROVENANCE-POLICY.md","experimental/model-lab/Cargo.toml","experimental/model-lab/Cargo.lock","experimental/model-lab/src/lib.rs","experimental/model-lab/src/main.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-167/experimental-model-lab-corpus.json","scripts/experimental_model_lab_contract.py","tests/test_experimental_model_lab_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_167_evidence.py","tests/test_sprint_167_evidence.py")
COMMANDS:Final=(("experimental-model-lab-rust",("cargo","test","--manifest-path","experimental/model-lab/Cargo.toml")),("experimental-model-lab-corpus",("python3","-m","unittest","tests.test_experimental_model_lab_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_167_evidence")));FOCUSED_COMMANDS:Final=tuple(x[0]for x in COMMANDS[:3]);IMPLEMENTED:Final={"hostile_artifact_count":9,"lifecycle_stage_count":8,"prohibited_route_count":12,"fault_count":8,"fixture_case_count":6912,"authority_count":0,"network_count":0,"canonical_write_count":0,"approved_store_count":0,"hidden_limitation_count":0,"promotion_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-157-163-164-166-BLOCKED","owner":"167"},{"code":"BLOCKED_EXTERNAL","platform":"native promoted lab platforms plus user-selected unapproved artifacts, accessibility, resource-pressure, crash, removal, residue, and independent review environments","artifact":"untouched native import, parser/load, resource, hostile artifact, injection, exfiltration, cancellation, crash, accessibility, removal, residue, limitation-display, AT-EML-001, and RV-42 evidence","action":"satisfy upstream blockers, provision exact native lab platforms and hostile user-selected artifacts, then run complete AT-EML-001 and RV-42 implementation, resource, accessibility, interruption, removal, and residue campaigns","credential":"artifact-source, platform, accessibility, and independent reviewer credentials","payment":"artifact, platform, accessibility, or independent evaluator costs if applicable"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"separate_package_complete":True,"prohibited_authority_absent":True,"policy_lineage_boundary_complete":True,"quarantine_resource_contract_complete":True,"synthetic_evaluation_complete":True,"hostile_route_contract_complete":True,"experimental_truth_complete":True,"native_lab_campaign_complete":False,"native_accessibility_removal_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_167_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"experimental_lab_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=167,root=ROOT,output="artifacts/sprints/sprint-167/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-EML-001","AT-EML-001","SR-LAB-001","SR-LAB-002","RV-42"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
