#!/usr/bin/env python3
"""Build truthful Sprint 165 final-reconciliation evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","TRUSTED-OPERATIONS.md","CODEBASE-AUDIT.md","TASKS.md","SECURITY-REVIEW.md","MODEL-PROVENANCE-POLICY.md","docs/decisions/0027-muse-first-model-neutral-runtime-and-evaluation.md","kernel/engine/src/lib.rs","kernel/engine/src/final_reconciliation.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-165/final-reconciliation-corpus.json","scripts/final_reconciliation_contract.py","tests/test_final_reconciliation_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_165_evidence.py","tests/test_sprint_165_evidence.py")
COMMANDS:Final=(("final-reconciliation-rust",("cargo","test","-p","agentmage-kernel-engine","final_reconciliation::tests","--lib")),("final-reconciliation-corpus",("python3","-m","unittest","tests.test_final_reconciliation_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_165_evidence")));FOCUSED_COMMANDS:Final=tuple(x[0]for x in COMMANDS[:3]);IMPLEMENTED:Final={"capability_count":10,"lifecycle_state_count":8,"attack_count":13,"variation_count":10,"composed_case_count":10400,"known_answer_fixture_count":11,"risk_class_count":8,"report_profile_count":3,"audit_case_count":264,"authority_reuse_count":0,"unauthorized_effect_count":0,"false_comprehensive_count":0,"muse_disposition":"BLOCKED","approved_model_count":0,"promotion_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-0-164-BLOCKED","owner":"165"},{"code":"BLOCKED_EXTERNAL","platform":"first-party Muse and complete eligible candidate sources plus native Fedora, Ubuntu, Windows, provider, storage, accessibility, strict-local, clean-install, removal, and independent review environments","artifact":"untouched exact candidate provenance, artifact, model/runtime/hardware, role-matrix, measurement, disposition, cross-capability native attack, disablement, removal, residue, accessibility, incident, recovery, support, RV-41, RV-43, and RV-46 through RV-48 evidence","action":"satisfy every upstream blocker, provision exact candidate artifacts and all native/provider/reviewer environments, then run the complete candidate admission, trusted-operations composition, removal, restoration, audit, accessibility, incident, recovery, and independent review campaigns","credential":"candidate-source, model artifact, provider, platform key-store, storage, accessibility, and independent reviewer credentials","payment":"model, provider, storage, platform, accessibility, or independent evaluator costs if applicable"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"candidate_negative_truth_complete":True,"candidate_independence_complete":True,"composed_authority_contract_complete":True,"composed_mutation_scale_complete":True,"cross_module_reconciliation_complete":True,"finding_calibration_complete":True,"report_completion_guard_complete":True,"known_answer_contract_complete":True,"native_candidate_admission_complete":False,"native_removal_restoration_complete":False,"independent_reproduction_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_165_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"muse_disposition":"BLOCKED","approved_model_count":0,"trusted_operations_promoted":False,"codebase_audit_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=165,root=ROOT,output="artifacts/sprints/sprint-165/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-MUSE-001","AM-MDL-004","AM-MDL-007","AM-AGT-001","AM-XOP-001","AM-RCN-001","AM-AUR-001","AT-MUSE-001","AT-MODEL-003","AT-MODEL-005","AT-CLASS-001","AT-AGENT-001","AT-XOP-001","AT-RCN-001","AT-AUR-001","SR-MGM-004","SR-MGM-005","SR-AI-015","SR-AI-018","SR-TOP-001","SR-AUD-007","SR-AUD-010","RV-41","RV-43","RV-46","RV-47","RV-48"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
