#!/usr/bin/env python3
"""Build truthful Sprint 106 local GitHub negative evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","kernel/engine/Cargo.toml","kernel/engine/src/repository_safety.rs","kernel/engine/tests/repository_safety_matrix.rs","capabilities/knowledge/Cargo.toml","capabilities/knowledge/src/github_provider.rs","capabilities/knowledge/src/github_mutation.rs","docs/security/repository-safety.md","artifacts/sprints/sprint-106/github-negative-corpus.json","scripts/github_provider_contract.py","scripts/github_mutation_contract.py","scripts/github_full_negative_contract.py","tests/test_github_provider_contract.py","tests/test_github_mutation_contract.py","tests/test_github_full_negative_contract.py","supply-chain/dependency-hashes.sha256","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","scripts/sprint_evidence_recorder.py","scripts/sprint_106_evidence.py","tests/test_sprint_106_evidence.py")
COMMANDS:Final=(("repository-preservation-ten-thousand",("cargo","test","-p","agentmage-kernel-engine","--test","repository_safety_matrix","ten_thousand_protected_manifest_mutations_have_zero_acceptance")),("github-provider-contract",("python3","-m","unittest","tests.test_github_provider_contract")),("github-mutation-contract",("python3","-m","unittest","tests.test_github_mutation_contract")),("github-negative-contract",("python3","-m","unittest","tests.test_github_full_negative_contract")),("dependency-boundary-contract",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_106_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0] for i in COMMANDS[:5]);IMPLEMENTED:Final={"prohibited_operation_count":22,"attack_class_count":24,"negative_mutation_count":10000,"unauthorized_effect_count":0,"user_work_loss_count":0,"native_request_count":0,"supported_github_com_tuple_count":0,"supported_ghes_tuple_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-105-BLOCKED","owner":"106"},{"code":"BLOCKED-EXTERNAL-GITHUB-COM-GHES-FULL-CONFORMANCE-RV49","owner":"106"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"prohibited_operations_absent":True,"unsupported_ghes_denied_without_fallback":True,"complete_rv49":False,"independent_review":False,"sprint_gate_closed":False}
SUMMARY:Final={"local_sprint_106_negative_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_105_closed":False,"github_com_supported":False,"ghes_supported":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=106,root=ROOT,output="artifacts/sprints/sprint-106/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=tuple([f"SR-GIT-{i:03d}" for i in range(1,13)]+["RV-49"]),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
