#!/usr/bin/env python3
"""Build truthful Sprint 145 read-only financial-adapter evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/financial_domain.rs","kernel/engine/src/financial_data_adapter.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-145/read-only-corpus.json","scripts/financial_data_adapter_contract.py","tests/test_financial_data_adapter_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_145_evidence.py","tests/test_sprint_145_evidence.py")
COMMANDS:Final=(("finance-read-rust",("cargo","test","-p","agentmage-kernel-engine","financial_data_adapter::tests","--lib")),("finance-read-corpus",("python3","-m","unittest","tests.test_financial_data_adapter_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_145_evidence")));FOCUSED_COMMANDS:Final=tuple(item[0]for item in COMMANDS[:3]);IMPLEMENTED:Final={"provider_count":1,"data_class_count":6,"mutation_family_count":12,"failure_family_count":10,"fixture_case_count":4320,"prohibited_family_count":13,"write_count":0,"disclosure_count":0,"credential_exposure_count":0,"removal_authority_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-128-130-142-143-BLOCKED","owner":"145"},{"code":"BLOCKED_EXTERNAL","platform":"Plaid sandbox provider, institution, items, and representative financial accounts","artifact":"untouched native provider-version, consent, account-scope, cursor, privacy, security, reviewer, revocation, deletion, and removal evidence","action":"provision the exact Plaid sandbox account, institution/items, accounts, and credentials, then run AT-BNK-001 plus RV-23, RV-24, RV-26, RV-33, and RV-35 native campaigns","credential":"Plaid sandbox client_id and secret","payment":"Plaid account costs if applicable"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"read_only_profile_complete":True,"consent_and_scope_complete":True,"normalization_complete":True,"sync_recovery_complete":True,"prohibited_families_absent":True,"revocation_and_removal_complete":True,"native_provider_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_145_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"native_financial_provider_support_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=145,root=ROOT,output="artifacts/sprints/sprint-145/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-BNK-001","AT-BNK-001","SR-FIN-005","SR-FIN-006","RV-23","RV-24","RV-26","RV-33","RV-35"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
