#!/usr/bin/env python3
"""Build truthful Sprint 146 financial-planning evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/financial_domain.rs","kernel/engine/src/financial_planning.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-146/planning-corpus.json","scripts/financial_planning_contract.py","tests/test_financial_planning_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_146_evidence.py","tests/test_sprint_146_evidence.py")
COMMANDS:Final=(("planning-rust",("cargo","test","-p","agentmage-kernel-engine","financial_planning::tests","--lib")),("planning-corpus",("python3","-m","unittest","tests.test_financial_planning_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_146_evidence")));FOCUSED_COMMANDS:Final=tuple(item[0]for item in COMMANDS[:3]);IMPLEMENTED:Final={"scenario_kind_count":6,"rule_kind_count":8,"mutation_family_count":12,"failure_family_count":10,"fixture_case_count":4320,"inexact_count":0,"order_drift_count":0,"hidden_limitation_count":0,"guaranteed_claim_count":0,"execution_attempt_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-142-145-BLOCKED","owner":"146"},{"code":"BLOCKED_EXTERNAL","platform":"macOS arm64 and Windows 11 x86_64 native hosts","artifact":"untouched native fixed-point budget, forecast, goal, debt, net-worth, scenario, uncertainty, and reviewer evidence","action":"provision exact hosts and run AT-BUD-001 and RV-33 native campaigns","credential":"none","payment":"host acquisition or access costs if applicable"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"budget_rules_complete":True,"forecasts_and_scenarios_complete":True,"truthful_uncertainty_complete":True,"reordered_determinism_complete":True,"external_execution_absent":True,"native_cross_platform_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_146_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"native_financial_planning_support_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=146,root=ROOT,output="artifacts/sprints/sprint-146/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-BUD-001","AT-BUD-001","SR-FIN-001","SR-FIN-004","SR-FIN-006","RV-33"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
