#!/usr/bin/env python3
"""Build truthful Sprint 101 local requirement-closure evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","README.md","PRD.md","Agent-Scaffolding-Inventory.md","TASKS.md","SECURITY-REVIEW.md","requirements/registry.json","requirements/traceability-report.json","architecture/status-model.json","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-101/requirement-closure-corpus.json","scripts/inherited_scope_closure_contract.py","tests/test_inherited_scope_closure_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_101_evidence.py","tests/test_sprint_101_evidence.py")
COMMANDS:Final=(("requirement-closure-contract",("python3","-m","unittest","tests.test_inherited_scope_closure_contract")),("requirements-currentness",("python3","scripts/requirement_registry.py","--check")),("traceability-currentness",("python3","scripts/traceability_report.py","--check")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_101_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"requirement_count":294,"inventory_item_count":1387,"completion_record_count":111,"deferred_exclusion_count":30,"promoted_mapping_gate_count":0,"user_approval_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-100-BLOCKED","owner":"101"},{"code":"INHERITED-PROMOTED-MAPPING-AND-USER-REVIEW-ABSENT","owner":"101.1.1.2-101.1.3.4-101.AC1-101.AC5"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"requirement_registry_rebuilt":True,"completion_records_compared":True,"deferred_exclusions_complete":True,"summary_reconciliation_complete":True,"authority_broadening_count":0,"promoted_mapping_complete":False,"signed_security_bundle_complete":False,"clean_platform_witnesses_complete":False,"user_approval_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_101_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_100_closed":False,"promoted_mapping_gate_closed":False,"inherited_release_approved":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=101,root=ROOT,output="artifacts/sprints/sprint-101/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("SR-GOV-010","SR-TST-005","SR-TST-006","SR-TST-011","RV-01","RV-30"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
