#!/usr/bin/env python3
"""Build truthful Sprint 155 cross-pack verification evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/cross_pack_verification.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-155/cross-pack-corpus.json","scripts/cross_pack_verification_contract.py","tests/test_cross_pack_verification_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_155_evidence.py","tests/test_sprint_155_evidence.py")
COMMANDS:Final=(("cross-pack-rust",("cargo","test","-p","agentmage-kernel-engine","cross_pack_verification::tests","--lib")),("cross-pack-corpus",("python3","-m","unittest","tests.test_cross_pack_verification_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_155_evidence")));FOCUSED_COMMANDS:Final=tuple(item[0]for item in COMMANDS[:3])
IMPLEMENTED:Final={"autonomy_level_count":4,"pack_set_count":6,"attack_count":16,"state_count":8,"removal_count":5,"prohibited_family_count":8,"case_count":15360,"unauthorized_disclosure_count":0,"unauthorized_effect_count":0,"money_movement_count":0,"cloud_mutation_count":0,"duplicate_count":0,"false_completion_count":0,"hidden_blocker_count":0,"residue_count":0,"promotion_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-127-154-BLOCKED","owner":"155"},{"code":"BLOCKED_EXTERNAL","platform":"all productivity, communications, finance, cloud, delivery, Windows, macOS, backup, update, and strict-local environments plus independent review environment","artifact":"untouched native cross-pack, mutation, fuzz, failure, resource, removal, restoration, support, accessibility, reviewer, and recomputation evidence","action":"satisfy every Sprint 127-154 external tuple and strict-local host blocker, then run AT-XPR-001, RV-01 through RV-35, complete platform, removal, restoration, accessibility, update, rollback, uninstall, and independent reproduction campaigns","credential":"all provider, platform, backup, update, signing, and evaluator credentials named by Sprints 127-154","payment":"provider, hardware, hosted environment, backup, signing, and independent evaluator costs if applicable"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"cross_pack_matrix_complete":True,"hostile_failure_resource_contract_complete":True,"prohibited_authority_absent":True,"removal_inventory_complete":True,"evidence_reconciliation_complete":True,"native_cross_pack_campaign_complete":False,"strict_local_restoration_complete":False,"independent_review_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_155_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"cross_pack_gate_closed":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=155,root=ROOT,output="artifacts/sprints/sprint-155/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-XPR-001","AT-XPR-001","SR-PRD-001","SR-FIN-001","SR-CLD-001","RV-01","RV-35"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
