#!/usr/bin/env python3
"""Build truthful Sprint 127 productivity-pack contract evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","docs/decisions/0009-productivity-finance-and-cloud-observer-expansion.md","kernel/engine/src/lib.rs","kernel/engine/src/productivity_pack.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-127/productivity-pack-corpus.json","scripts/productivity_pack_contract.py","tests/test_productivity_pack_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_127_evidence.py","tests/test_sprint_127_evidence.py")
COMMANDS:Final=(("productivity-rust-contract",("cargo","test","-p","agentmage-kernel-engine","productivity_pack::tests","--lib")),("productivity-corpus-contract",("python3","-m","unittest","tests.test_productivity_pack_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_127_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"support_state_count":6,"pack_family_count":3,"operation_class_count":5,"lifecycle_action_count":9,"inventory_field_count":11,"fixture_case_count":144,"allowed_data_flow_count":3,"installed_pack_count":0,"enabled_pack_count":0,"provider_account_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-126-BLOCKED","owner":"127"},);VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"manifest_schema_complete":True,"support_matrix_complete":True,"lifecycle_contract_complete":True,"data_flow_allowlist_complete":True,"negative_registration_complete":True,"strict_local_absence_equivalent":True,"native_provider_conformance_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_127_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_126_closed":False,"optional_pack_authority_count":0,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=127,root=ROOT,output="artifacts/sprints/sprint-127/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-ATC-001","AM-SYNC-001","AM-PGR-001","AM-UIN-001","AM-COM-001","AM-FIN-001","AM-CLO-001"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
