#!/usr/bin/env python3
"""Build truthful Sprint 131 inbox evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/productivity_inbox.rs","shells/vscode/src/productivity_inbox.ts","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-131/inbox-corpus.json","scripts/productivity_inbox_contract.py","tests/test_productivity_inbox_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_131_evidence.py","tests/test_sprint_131_evidence.py")
COMMANDS:Final=(("inbox-rust",("cargo","test","-p","agentmage-kernel-engine","productivity_inbox::tests","--lib")),("inbox-corpus",("python3","-m","unittest","tests.test_productivity_inbox_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_131_evidence")));FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"inbox_state_count":13,"source_family_count":6,"fault_family_count":13,"fixture_case_count":1014,"provider_write_count":0,"model_authority_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-130-BLOCKED","owner":"131"},);VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"native_source_truth_complete":True,"deterministic_query_complete":True,"coverage_gap_truth_complete":True,"native_vscode_projection_complete":True,"local_accessibility_matrix_complete":True,"native_connected_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_131_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_130_closed":False,"inbox_authority_broadening_count":0,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=131,root=ROOT,output="artifacts/sprints/sprint-131/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-UIN-001","AT-UIN-001","SR-PRD-004","RV-32"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
