#!/usr/bin/env python3
"""Build truthful Sprint 150 accounting evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/accounting_provider.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-150/accounting-corpus.json","scripts/accounting_provider_contract.py","tests/test_accounting_provider_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_150_evidence.py","tests/test_sprint_150_evidence.py")
COMMANDS:Final=(("accounting-rust",("cargo","test","-p","agentmage-kernel-engine","accounting_provider::tests","--lib")),("accounting-corpus",("python3","-m","unittest","tests.test_accounting_provider_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_150_evidence")));FOCUSED_COMMANDS:Final=tuple(x[0]for x in COMMANDS[:3]);IMPLEMENTED:Final={"provider_count":2,"object_count":8,"mutation_count":14,"failure_count":10,"case_count":13440,"wrong_write_count":0,"duplicate_write_count":0,"money_movement_count":0,"residual_authority_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-128-138-142-143-148-BLOCKED","owner":"150"},{"code":"BLOCKED_EXTERNAL","platform":"QuickBooks Online and Xero sandbox organizations with supported accounting objects","artifact":"untouched native organization, period, precision, tax, idempotency, recovery, security, reviewer, revocation, and removal evidence","action":"provision exact QuickBooks Online and Xero sandbox organizations and credentials, then run AT-ACC-001 and applicable reviewer campaigns","credential":"QuickBooks Online and Xero OAuth credentials","payment":"provider subscription costs if applicable"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"exact_discovery_complete":True,"bounded_reads_complete":True,"approved_writes_bounded":True,"unknown_effect_reconciliation_complete":True,"prohibited_families_absent":True,"removal_contract_complete":True,"native_provider_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_150_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"native_accounting_support_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=150,root=ROOT,output="artifacts/sprints/sprint-150/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-ACC-001","AT-ACC-001","SR-FIN-001","SR-FIN-002","SR-FIN-003","SR-FIN-004","SR-FIN-005","SR-FIN-006","RV-23","RV-24","RV-25","RV-26","RV-31","RV-33","RV-35"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
