#!/usr/bin/env python3
"""Build truthful Sprint 142 exact-financial-domain evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/financial_domain.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-142/financial-domain-corpus.json","scripts/financial_domain_contract.py","tests/test_financial_domain_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_142_evidence.py","tests/test_sprint_142_evidence.py")
COMMANDS:Final=(("financial-rust",("cargo","test","-p","agentmage-kernel-engine","financial_domain::tests","--lib")),("financial-corpus",("python3","-m","unittest","tests.test_financial_domain_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_142_evidence")));FOCUSED_COMMANDS:Final=tuple(item[0]for item in COMMANDS[:3]);IMPLEMENTED:Final={"currency_count":7,"scale_count":5,"rounding_mode_count":5,"financial_object_kind_count":20,"arithmetic_fixture_count":8400,"mutation_fixture_count":48,"binary_float_count":0,"inexact_result_count":0,"order_dependent_count":0,"silent_failure_count":0,"lineage_loss_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-127-129-141-BLOCKED","owner":"142"},{"code":"BLOCKED_EXTERNAL","platform":"macOS arm64 and Windows 11 x86_64 native hosts","artifact":"untouched native fixed-point arithmetic, serialization, ordering, lineage, and reviewer evidence","action":"provision exact hosts and run AT-FIN-001 and RV-33 native campaigns","credential":"none","payment":"host acquisition or access costs if applicable"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"fixed_point_complete":True,"financial_object_model_complete":True,"checked_arithmetic_complete":True,"immutable_lineage_complete":True,"reconciliation_records_complete":True,"native_cross_platform_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_142_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"native_financial_support_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=142,root=ROOT,output="artifacts/sprints/sprint-142/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-FIN-001","AT-FIN-001","SR-FIN-001","SR-FIN-002","RV-33"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
