#!/usr/bin/env python3
"""Build truthful Sprint 149 anomaly-indicator evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/financial_domain.rs","kernel/engine/src/financial_anomaly.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-149/anomaly-corpus.json","scripts/financial_anomaly_contract.py","tests/test_financial_anomaly_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_149_evidence.py","tests/test_sprint_149_evidence.py")
COMMANDS:Final=(("anomaly-rust",("cargo","test","-p","agentmage-kernel-engine","financial_anomaly::tests","--lib")),("anomaly-corpus",("python3","-m","unittest","tests.test_financial_anomaly_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_149_evidence")));FOCUSED_COMMANDS:Final=tuple(item[0]for item in COMMANDS[:3]);IMPLEMENTED:Final={"indicator_kind_count":10,"method_count":3,"attack_family_count":14,"corpus_family_count":9,"fixture_case_count":7560,"definitive_claim_count":0,"authority_count":0,"evidence_rewrite_count":0,"hidden_limitation_count":0,"replay_drift_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-142-148-BLOCKED","owner":"149"},{"code":"BLOCKED_EXTERNAL","platform":"native supported financial data sources and independent evaluation environment with representative labeled records","artifact":"untouched native baseline, feature, replay, accuracy, calibration, subgroup, drift, explanation, adversarial, reviewer, and removal evidence","action":"provision exact native data sources, representative labeled records, and independent evaluation environment, then run AT-FANL-001, RV-14, and RV-33 native campaigns","credential":"applicable financial data-source credentials","payment":"data-source, evaluator, or host costs if applicable"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"method_separation_complete":True,"reproducible_indicators_complete":True,"versioned_metrics_complete":True,"uncertainty_and_drift_complete":True,"definitive_claims_absent":True,"external_authority_absent":True,"native_labeled_evaluation_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_149_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"native_anomaly_support_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=149,root=ROOT,output="artifacts/sprints/sprint-149/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-FANL-001","AT-FANL-001","SR-FIN-004","SR-FIN-005","RV-14","RV-33"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
