#!/usr/bin/env python3
"""Build truthful Sprint 148 financial-document evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/financial_domain.rs","kernel/engine/src/financial_document.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-148/financial-document-corpus.json","scripts/financial_document_contract.py","tests/test_financial_document_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_148_evidence.py","tests/test_sprint_148_evidence.py")
COMMANDS:Final=(("financial-document-rust",("cargo","test","-p","agentmage-kernel-engine","financial_document::tests","--lib")),("financial-document-corpus",("python3","-m","unittest","tests.test_financial_document_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_148_evidence")));FOCUSED_COMMANDS:Final=tuple(item[0]for item in COMMANDS[:3]);IMPLEMENTED:Final={"document_kind_count":5,"field_kind_count":7,"privacy_copy_kind_count":7,"mutation_family_count":14,"failure_family_count":12,"fixture_case_count":6720,"silent_merge_count":0,"authority_count":0,"escape_count":0,"residue_count":0,"citation_loss_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-140-142-143-BLOCKED","owner":"148"},{"code":"BLOCKED_EXTERNAL","platform":"native supported financial-document, OCR, archive, malware, encrypted-storage, backup, and export environments with representative documents","artifact":"untouched native extraction, coordinate, parser, matching, duplicate, hostile-file, privacy-copy, backup, restore, deletion, reviewer, and removal evidence","action":"provision exact native environments and representative receipt, invoice, reimbursement, statement, and tax documents, then run AT-FDOC-001 and RV-33 native campaigns","credential":"applicable encrypted-storage, backup, and export destination credentials","payment":"host, OCR, storage, or provider costs if applicable"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"source_preservation_complete":True,"field_evidence_complete":True,"ambiguity_preservation_complete":True,"matching_reversible_complete":True,"privacy_copy_reconciliation_complete":True,"hostile_content_fail_closed":True,"native_document_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_148_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"native_financial_document_support_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=148,root=ROOT,output="artifacts/sprints/sprint-148/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-FDOC-001","AT-FDOC-001","SR-FIN-001","SR-FIN-005","SR-FIN-006","RV-33"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
