#!/usr/bin/env python3
"""Build truthful Sprint 152 cloud-observer evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/cloud_observer.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-152/cloud-observer-corpus.json","scripts/cloud_observer_contract.py","tests/test_cloud_observer_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_152_evidence.py","tests/test_sprint_152_evidence.py")
COMMANDS:Final=(("cloud-rust",("cargo","test","-p","agentmage-kernel-engine","cloud_observer::tests","--lib")),("cloud-corpus",("python3","-m","unittest","tests.test_cloud_observer_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_152_evidence")));FOCUSED_COMMANDS:Final=tuple(x[0]for x in COMMANDS[:3]);IMPLEMENTED:Final={"read_kind_count":10,"attack_count":15,"state_count":12,"fixture_count":6,"prohibited_count":13,"case_count":10800,"escape_count":0,"provider_effect_count":0,"authority_count":0,"residue_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-127-130-141-BLOCKED","owner":"152"},{"code":"BLOCKED_EXTERNAL","platform":"native reference cloud provider account and independent read-only review environment","artifact":"untouched native scope, hierarchy, query, pagination, quota, token, proxy, hostile-content, prohibited-family, reviewer, revocation, and removal evidence","action":"provision an exact native reference cloud account and credentials, then run AT-CLO-001, RV-34, and RV-35 native campaigns","credential":"reference cloud provider read-only credential","payment":"cloud account and resource costs if applicable"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"closed_read_schema_complete":True,"exact_worker_bounds_complete":True,"truthful_result_states_complete":True,"untrusted_content_inert":True,"prohibited_families_absent":True,"removal_complete":True,"native_reference_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_152_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"native_cloud_observer_support_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=152,root=ROOT,output="artifacts/sprints/sprint-152/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-CLO-001","AT-CLO-001","SR-CLD-001","SR-CLD-002","SR-CLD-003","RV-23","RV-24","RV-26","RV-34","RV-35"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
