#!/usr/bin/env python3
"""Build truthful Sprint 158 credential-broker evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/credential_broker.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-158/credential-broker-corpus.json","scripts/credential_broker_contract.py","tests/test_credential_broker_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_158_evidence.py","tests/test_sprint_158_evidence.py")
COMMANDS:Final=(("credential-broker-rust",("cargo","test","-p","agentmage-kernel-engine","credential_broker::tests","--lib")),("credential-broker-corpus",("python3","-m","unittest","tests.test_credential_broker_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_158_evidence")));FOCUSED_COMMANDS:Final=tuple(item[0]for item in COMMANDS[:3])
IMPLEMENTED:Final={"store_adapter_contract_count":4,"acquisition_flow_count":6,"credential_lifecycle_count":8,"prohibited_surface_count":13,"mutation_family_count":12,"mutation_case_count":6912,"disclosure_count":0,"wrong_account_count":0,"stale_reference_count":0,"canary_finding_count":0,"restored_raw_credential_count":0,"restored_usable_credential_count":0,"promotion_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-9-11-104-128-130-157-BLOCKED","owner":"158"},{"code":"BLOCKED_EXTERNAL","platform":"native Linux Secret Service, Windows Credential Manager or DPAPI, and retained macOS Keychain environments plus provider authentication and independent review environments","artifact":"untouched native store identity, access-control, cryptographic-provider, acquisition, worker-resolution, lifetime, canary, revocation, restoration, removal, and RV-38 evidence","action":"provision exact native platform key stores and provider credentials, then run AT-CRD-001 and RV-38 separately on each available first-GA platform","credential":"platform key-store, OAuth, SSH-agent, certificate, provider, and independent reviewer credentials","payment":"platform, provider, certificate, or independent evaluator costs if applicable"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"typed_reference_contract_complete":True,"store_attestation_contract_complete":True,"acquisition_contract_complete":True,"exact_worker_resolution_complete":True,"bounded_memory_clear_complete":True,"lifecycle_contract_complete":True,"canary_surface_contract_complete":True,"restore_reauthentication_complete":True,"native_platform_campaign_complete":False,"rv38_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_158_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"credential_broker_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=158,root=ROOT,output="artifacts/sprints/sprint-158/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-CRD-001","AT-CRD-001","SR-CRD-001","SR-CRD-002","SR-CRD-003","RV-38"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
