#!/usr/bin/env python3
"""Build truthful Sprint 119 local service-catalog evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","kernel/engine/Cargo.toml","kernel/engine/src/lib.rs","kernel/engine/src/service_catalog.rs","SECURITY-REVIEW.md","DELIVERY-SYSTEM.md","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-119/service-catalog-corpus.json","scripts/service_catalog_contract.py","tests/test_service_catalog_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_119_evidence.py","tests/test_sprint_119_evidence.py")
COMMANDS:Final=(("catalog-rust-contract",("cargo","test","-p","agentmage-kernel-engine","service_catalog::tests","--lib")),("catalog-corpus-contract",("python3","-m","unittest","tests.test_service_catalog_contract")),("dependency-boundary-contract",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_119_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"entity_kind_count":7,"link_kind_count":8,"extension_candidate_count":3,"entity_case_count":128,"attack_case_count":2048,"fault_case_count":512,"live_query_count":0,"authority_grant_count":0,"registered_extension_count":0,"promoted_provider_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-118-BLOCKED","owner":"119"},{"code":"BLOCKED-EXTERNAL-CATALOG-AT-CAT-001","owner":"119"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"provider_links_independent":True,"conflicts_explicit":True,"extensions_inert":True,"published_read_matrix_complete":False,"at_cat_001_complete":False,"independent_human_review":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_119_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_118_closed":False,"live_catalog_support":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=119,root=ROOT,output="artifacts/sprints/sprint-119/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=("AM-CAT-001","AT-CAT-001","SR-DEL-004","SR-DEL-011","SR-DEL-012","SR-DEL-013","SR-DEL-014","RV-23","RV-27","RV-29"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
