#!/usr/bin/env python3
"""Build truthful Sprint 136 Slack evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/communications_slack.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-136/slack-corpus.json","scripts/communications_slack_contract.py","tests/test_communications_slack_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_136_evidence.py","tests/test_sprint_136_evidence.py")
COMMANDS:Final=(("slack-rust",("cargo","test","-p","agentmage-kernel-engine","communications_slack::tests","--lib")),("slack-corpus",("python3","-m","unittest","tests.test_communications_slack_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_136_evidence")));FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"profile_count":6,"mutation_family_count":16,"failure_family_count":10,"lifecycle_state_count":5,"fixture_case_count":4800,"unauthorized_effect_count":0,"duplicate_post_count":0,"cross_workspace_disclosure_count":0,"removal_authority_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-132-BLOCKED","owner":"136"},{"code":"BLOCKED_EXTERNAL","platform":"Slack test workspaces, channels, direct messages, and accounts","artifact":"untouched native capability, membership, effect, event, rate, security, reviewer, and removal evidence","action":"provision exact Slack workspaces/accounts/tokens and run AT-SLK-001 plus RV-23 through RV-26 and RV-31 native campaigns","credential":"Slack OAuth app and workspace account credentials","payment":"Slack workspace or provider costs if applicable"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"workspace_identity_complete":True,"capability_discovery_complete":True,"exact_effect_complete":True,"event_and_recovery_complete":True,"isolation_and_removal_complete":True,"native_provider_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_136_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_132_closed":False,"native_slack_support_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=136,root=ROOT,output="artifacts/sprints/sprint-136/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-SLK-001","AT-SLK-001","SR-PRD-005","SR-PRD-006","SR-PRD-007","RV-23","RV-24","RV-25","RV-26","RV-31"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
