#!/usr/bin/env python3
"""Build truthful Sprint 118 local incident lifecycle evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","kernel/engine/Cargo.toml","kernel/engine/src/lib.rs","kernel/engine/src/incident_lifecycle.rs","SECURITY-REVIEW.md","DELIVERY-SYSTEM.md","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-118/incident-lifecycle-corpus.json","scripts/incident_lifecycle_contract.py","tests/test_incident_lifecycle_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_118_evidence.py","tests/test_sprint_118_evidence.py")
COMMANDS:Final=(("incident-rust-contract",("cargo","test","-p","agentmage-kernel-engine","incident_lifecycle::tests","--lib")),("incident-corpus-contract",("python3","-m","unittest","tests.test_incident_lifecycle_contract")),("dependency-boundary-contract",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_118_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"provider_fixture_count":5,"effect_class_count":8,"incident_case_count":128,"attack_case_count":2048,"fault_case_count":512,"external_effect_count":0,"autonomous_effect_count":0,"duplicate_effect_count":0,"promoted_provider_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-117-BLOCKED","owner":"118"},{"code":"BLOCKED-EXTERNAL-INCIDENT-AT-INC-001","owner":"118"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"evidence_classes_separate":True,"effects_separately_granted":True,"uncertain_effects_reconciled":True,"promoted_matrices_complete":False,"at_inc_001_complete":False,"expanded_tabletop_complete":False,"independent_human_review":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_118_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_117_closed":False,"live_incident_support":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=118,root=ROOT,output="artifacts/sprints/sprint-118/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=("AM-INC-001","AT-INC-001","SR-DEL-*","SR-OPS-*","RV-21","RV-23","RV-24","RV-25","RV-26","RV-27","RV-28","RV-29"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
