#!/usr/bin/env python3
"""Build truthful Sprint 128 Autonomy Center evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/autonomy_center.rs","shells/vscode/src/autonomy_center.ts","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-128/autonomy-center-corpus.json","scripts/autonomy_center_contract.py","tests/test_autonomy_center_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_128_evidence.py","tests/test_sprint_128_evidence.py")
COMMANDS:Final=(("autonomy-rust-contract",("cargo","test","-p","agentmage-kernel-engine","autonomy_center::tests","--lib")),("autonomy-mutation-contract",("python3","-m","unittest","tests.test_autonomy_center_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_128_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"autonomy_level_count":6,"policy_origin_count":7,"mutation_case_count":2520,"authority_broadening_count":0,"shell_authority_count":0,"prohibited_operation_count":2,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-127-BLOCKED","owner":"128"},);VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"policy_intersection_complete":True,"native_vscode_projection_complete":True,"fresh_revision_and_approval_complete":True,"emergency_disable_complete":True,"rv_31_local_mutations_complete":True,"native_connected_operation_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_128_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_127_closed":False,"authority_broadening_count":0,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=128,root=ROOT,output="artifacts/sprints/sprint-128/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-ATC-001","AT-AUT-001","SR-PRD-001","RV-31"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
