#!/usr/bin/env python3
"""Build truthful Sprint 124 local adapter-removal evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","SECURITY-REVIEW.md","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-124/adapter-removal-corpus.json","scripts/adapter_removal_contract.py","tests/test_adapter_removal_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_124_evidence.py","tests/test_sprint_124_evidence.py")
COMMANDS:Final=(("adapter-removal-contract",("python3","-m","unittest","tests.test_adapter_removal_contract")),("dependency-boundary-contract",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_124_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:2]);IMPLEMENTED:Final={"plan_case_count":1024,"attack_case_count":512,"recovery_case_count":512,"native_platform_count":0,"strict_local_rerun_count":0,"zero_egress_minutes":0,"rv30_run_count":0,"remote_profile_removal_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-123-BLOCKED","owner":"124"},{"code":"BLOCKED-EXTERNAL-ADAPTER-REMOVAL","owner":"124"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"inventory_contract_complete":True,"preview_contract_complete":True,"ordered_removal_contract_complete":True,"recovery_fixture_complete":True,"native_residue_scan_complete":False,"strict_local_acceptance_complete":False,"rv30_complete":False,"remote_profile_removal_complete":False,"independent_human_review":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_124_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_123_closed":False,"strict_local_restored_natively":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=124,root=ROOT,output="artifacts/sprints/sprint-124/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-ADP-001","AM-XTE-001","AT-ADP-001","AT-XTE-001","SR-DEL-010","RV-30"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
