#!/usr/bin/env python3
"""Build truthful Sprint 95 local coordination evidence for Stories 95.1-95.2."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","kernel/engine/Cargo.toml","kernel/engine/src/lib.rs","kernel/engine/src/child_authority.rs","kernel/engine/src/multi_agent.rs","kernel/engine/src/profile_workflows.rs","artifacts/sprints/sprint-94/local-evidence-report.json","artifacts/sprints/sprint-95/profile-workflow-corpus.json","scripts/profile_workflow_contract.py","tests/test_profile_workflow_contract.py","supply-chain/dependency-hashes.sha256","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","scripts/sprint_evidence_recorder.py","scripts/sprint_95_evidence.py","tests/test_sprint_95_evidence.py")
COMMANDS:Final=(("profile-workflow-rust-contract",("cargo","test","-p","agentmage-kernel-engine","profile_workflows::tests","--lib")),("multi-agent-rust-contract",("cargo","test","-p","agentmage-kernel-engine","multi_agent::tests","--lib")),("profile-workflow-artifact-contract",("python3","-m","unittest","tests.test_profile_workflow_contract")),("runtime-schema-contract",("npm","run","-s","schemas:test")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_95_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0] for i in COMMANDS[:3]);IMPLEMENTED:Final={"canonical_workflow_count":4,"workflow_node_count":28,"synthetic_case_count":80,"shared_runtime_count":1,"provider_effect_count":0,"native_descendant_cleanup_count":0,"native_worktree_pipeline_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-94-BLOCKED","owner":"95"},{"code":"NATIVE-COORDINATION-RECOVERY-WORKTREE-AND-REVIEW-ABSENT","owner":"95.1.3.4-95.2.3.5-95.AC4"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"canonical_workflow_count":4,"synthetic_case_count":80,"dissent_preserved":True,"real_effect_count":0,"native_descendant_cleanup_observed":False,"native_worktree_pipeline_observed":False,"independent_review":False,"sprint_gate_closed":False}
SUMMARY:Final={"local_sprint_95_coordination_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_94_closed":False,"native_recovery_complete":False,"native_writable_coordination_complete":False,"independent_review_present":False,"stories_95_3_and_95_4_complete":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=95,root=ROOT,output="artifacts/sprints/sprint-95/local-coordination-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:2]),security_requirement_ids=("SR-GOV-010","SR-ACC-001","SR-ACC-002","SR-ACC-003","SR-ACC-004","SR-ACC-005","SR-ACC-006","SR-ACC-007","SR-ACC-008","SR-AI-003","SR-AI-004","SR-AI-005","SR-AI-009","SR-AI-010","SR-TST-005","SR-TST-006","SR-TST-011"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
