#!/usr/bin/env python3
"""Build truthful Sprint 120 local Markdown mathematics evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","kernel/engine/Cargo.toml","kernel/engine/src/lib.rs","kernel/engine/src/markdown_math.rs","SECURITY-REVIEW.md","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-120/markdown-math-corpus.json","scripts/markdown_math_contract.py","tests/test_markdown_math_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_120_evidence.py","tests/test_sprint_120_evidence.py")
COMMANDS:Final=(("math-rust-contract",("cargo","test","-p","agentmage-kernel-engine","markdown_math::tests","--lib")),("math-corpus-contract",("python3","-m","unittest","tests.test_markdown_math_contract")),("dependency-boundary-contract",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_120_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"syntax_family_count":15,"round_trip_case_count":128,"attack_case_count":2048,"fault_case_count":512,"native_platform_execution_count":0,"file_access_count":0,"network_access_count":0,"promoted_platform_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-119-BLOCKED","owner":"120"},{"code":"BLOCKED-EXTERNAL-MATH-AT-MTH-001","owner":"120"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"source_round_trip_exact":True,"unsafe_commands_denied":True,"offline_renderer_manifested":True,"cross_platform_visual_complete":False,"accessibility_native_complete":False,"rv15_complete":False,"rv20_complete":False,"at_mth_001_complete":False,"independent_human_review":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_120_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_119_closed":False,"native_math_support":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=120,root=ROOT,output="artifacts/sprints/sprint-120/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=("AM-MTH-001","AT-MTH-001","SR-TST-002","SR-TST-004","SR-CIV-006","SR-CIV-007","SR-CIV-008","SR-CIV-009","RV-15","RV-20"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
