#!/usr/bin/env python3
"""Build truthful Sprint 137 Linux mail interoperability evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/linux_mail_interop.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-137/linux-mail-corpus.json","scripts/linux_mail_interop_contract.py","tests/test_linux_mail_interop_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_137_evidence.py","tests/test_sprint_137_evidence.py")
COMMANDS:Final=(("linux-mail-rust",("cargo","test","-p","agentmage-kernel-engine","linux_mail_interop::tests","--lib")),("linux-mail-corpus",("python3","-m","unittest","tests.test_linux_mail_interop_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_137_evidence")));FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"profile_count":6,"attack_family_count":15,"failure_family_count":10,"state_count":5,"fixture_case_count":4500,"source_mutation_count":0,"credential_extraction_count":0,"path_escape_count":0,"removal_authority_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-135-BLOCKED","owner":"137"},{"code":"BLOCKED_EXTERNAL","platform":"native Thunderbird, Evolution, and KMail installations plus representative user-selected mbox and Maildir archives","artifact":"untouched native client-version, archive-parser, non-mutation, reviewer, and removal evidence","action":"provision exact supported and future client versions and representative archives, then run AT-LMAIL-001 plus RV-23, RV-24, RV-30, and RV-31 native campaigns","credential":None,"payment":None});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"interop_routes_complete":True,"private_profile_denial_complete":True,"read_only_import_complete":True,"source_nonmutation_complete":True,"removal_complete":True,"native_client_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_137_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_135_closed":False,"native_linux_mail_support_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=137,root=ROOT,output="artifacts/sprints/sprint-137/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-LMAIL-001","AT-LMAIL-001","SR-PRD-008","RV-23","RV-24","RV-30","RV-31"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
