#!/usr/bin/env python3
"""Build truthful Sprint 144 Actual Budget evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/financial_domain.rs","kernel/engine/src/financial_import.rs","kernel/engine/src/actual_budget_adapter.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-144/actual-budget-corpus.json","scripts/actual_budget_adapter_contract.py","tests/test_actual_budget_adapter_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_144_evidence.py","tests/test_sprint_144_evidence.py")
COMMANDS:Final=(("actual-budget-rust",("cargo","test","-p","agentmage-kernel-engine","actual_budget_adapter::tests","--lib")),("actual-budget-corpus",("python3","-m","unittest","tests.test_actual_budget_adapter_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_144_evidence")));FOCUSED_COMMANDS:Final=tuple(item[0]for item in COMMANDS[:3]);IMPLEMENTED:Final={"profile_count":6,"operation_count":9,"record_kind_count":12,"mutation_family_count":13,"failure_family_count":10,"fixture_case_count":4680,"wrong_file_write_count":0,"duplicate_effect_count":0,"precision_loss_count":0,"money_movement_count":0,"network_broadening_count":0,"removal_authority_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-128-142-143-BLOCKED","owner":"144"},{"code":"BLOCKED_EXTERNAL","platform":"native supported Actual Budget server, client, and representative budget files","artifact":"untouched native API-version, budget-identity, sync, backup, recovery, security, reviewer, and removal evidence","action":"provision the exact supported Actual Budget installation and representative budget files, then run AT-ACT-001 plus RV-23 through RV-26, RV-33, and RV-35 native campaigns","credential":"Actual Budget local server authentication credential","payment":"none"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"exact_profile_complete":True,"native_identity_mapping_complete":True,"bounded_effects_complete":True,"backup_and_recovery_complete":True,"money_movement_absent":True,"removal_complete":True,"native_actual_budget_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_144_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"native_actual_budget_support_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=144,root=ROOT,output="artifacts/sprints/sprint-144/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-ACT-001","AT-ACT-001","SR-FIN-001","SR-FIN-002","SR-FIN-006","RV-23","RV-24","RV-25","RV-26","RV-33","RV-35"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
