#!/usr/bin/env python3
"""Build truthful Sprint 168 experimental promotion evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","TASKS.md","SECURITY-REVIEW.md","MODEL-PROVENANCE-POLICY.md","experimental/model-lab/Cargo.toml","experimental/model-lab/Cargo.lock","experimental/model-lab/src/lib.rs","experimental/model-lab/src/promotion.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-168/experimental-promotion-corpus.json","scripts/experimental_promotion_contract.py","tests/test_experimental_promotion_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_168_evidence.py","tests/test_sprint_168_evidence.py")
COMMANDS:Final=(("experimental-promotion-rust",("cargo","test","--manifest-path","experimental/model-lab/Cargo.toml","promotion::tests")),("experimental-promotion-corpus",("python3","-m","unittest","tests.test_experimental_promotion_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_168_evidence")));FOCUSED_COMMANDS:Final=tuple(x[0]for x in COMMANDS[:3]);IMPLEMENTED:Final={"promotion_route_count":10,"mutation_count":13,"lifecycle_state_count":16,"fixture_case_count":2080,"ordinary_activation_count":0,"direct_promotion_count":0,"approved_state_change_count":0,"canonical_damage_count":0,"signed_support_matrix_count":0,"promotion_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-163-164-167-BLOCKED","owner":"168"},{"code":"BLOCKED_EXTERNAL","platform":"native supported lab platforms plus approved catalog/admission, signing, accessibility, resource, reinstall, crash-removal, residue, and independent review environments","artifact":"untouched complete AT-EML-001 and RV-42, signed approved-catalog transition, removal, crash recovery, reinstall, residue, accessibility, resource, neighboring-state, manifest reconciliation, signed post-GA support matrix, and independent-review evidence","action":"satisfy upstream blockers, provision exact native lab and approved-model environments, run complete promotion-denial, removal, crash, reinstall, residue, accessibility, and RV-42 campaigns, then independently reproduce and sign the post-GA support matrix","credential":"catalog-signing, artifact, platform, accessibility, and independent reviewer credentials","payment":"artifact, signing, platform, accessibility, or independent evaluator costs if applicable"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"no_direct_promotion_complete":True,"normal_admission_contract_complete":True,"signed_catalog_requirement_complete":True,"promotion_bypass_mutations_complete":True,"removal_preservation_contract_complete":True,"native_removal_reinstall_complete":False,"signed_support_matrix_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_168_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"experimental_model_promoted":False,"experimental_lab_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=168,root=ROOT,output="artifacts/sprints/sprint-168/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-EML-001","AT-EML-001","SR-LAB-001","SR-LAB-002","SR-LAB-003","RV-42"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
