#!/usr/bin/env python3
"""Build truthful Sprint 102 local non-GA checkpoint evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","README.md","PRD.md","IMPLEMENTATION-PLAN.md","Agent-Scaffolding-Inventory.md","TASKS.md","SECURITY-REVIEW.md","SECURITY.md","WINDOWS-BOUNDARIES.md","docs/decisions/0008-first-ga-delivery-system-and-windows.md","requirements/registry.json","requirements/traceability-report.json","architecture/status-model.json","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-101/requirement-closure-corpus.json","artifacts/sprints/sprint-101/local-evidence-report.json","artifacts/sprints/sprint-102/inherited-checkpoint-corpus.json","scripts/inherited_scope_checkpoint_contract.py","tests/test_inherited_scope_checkpoint_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_102_evidence.py","tests/test_sprint_102_evidence.py")
COMMANDS:Final=(("inherited-checkpoint-contract",("python3","-m","unittest","tests.test_inherited_scope_checkpoint_contract")),("requirements-currentness",("python3","scripts/requirement_registry.py","--check")),("traceability-currentness",("python3","scripts/traceability_report.py","--check")),("status-truth",("python3","scripts/status_model.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_102_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:4]);IMPLEMENTED:Final={"requirement_count":294,"completion_record_count":112,"truth_document_count":8,"blocker_case_count":256,"clean_platform_bundle_count":0,"signed_manifest_count":0,"independent_review_count":0,"user_approval_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-101-BLOCKED","owner":"102"},{"code":"BLOCKED-EXTERNAL-INHERITED-CLEAN-PLATFORM-SIGNING-REVIEW","owner":"102.1.1.1-102.1.1.3-102.1.2.2-102.1.2.4-102.1.3.3-102.1.3.6"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"documentation_complete":True,"traceability_complete":True,"deferred_register_complete":True,"summary_reconciliation_complete":True,"negative_release_gate_complete":True,"clean_platform_campaign_complete":False,"all_capabilities_removal_complete":False,"signed_bom_complete":False,"independent_review_complete":False,"user_approval_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_102_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_101_closed":False,"legacy_g_product_closed":False,"g_ga_closed":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=102,root=ROOT,output="artifacts/sprints/sprint-102/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("SR-GOV-010","SR-TST-005","SR-TST-006","SR-TST-011","RV-01","RV-30"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
