#!/usr/bin/env python3
"""Build truthful Sprint 160 public-web research safety evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/web_research_safety.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-160/web-research-safety-corpus.json","scripts/web_research_safety_contract.py","tests/test_web_research_safety_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_160_evidence.py","tests/test_sprint_160_evidence.py")
COMMANDS:Final=(("web-safety-rust",("cargo","test","-p","agentmage-kernel-engine","web_research_safety::tests","--lib")),("web-safety-corpus",("python3","-m","unittest","tests.test_web_research_safety_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_160_evidence")));FOCUSED_COMMANDS:Final=tuple(x[0]for x in COMMANDS[:3])
IMPLEMENTED:Final={"source_state_count":7,"hazard_count":12,"private_class_count":8,"fixture_count":4,"case_count":2688,"authority_count":0,"undeclared_egress_count":0,"raw_private_count":0,"unadmitted_download_count":0,"promotion_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-21-66-74-157-158-BLOCKED","owner":"160"},{"code":"BLOCKED_EXTERNAL","platform":"native Fedora, Ubuntu, and Windows public-network worker, download quarantine, accessibility, removal, and independent review environments","artifact":"untouched search-provider, DNS, proxy, certificate, redirect, retrieval, citation, freshness, quarantine, cancellation, resource, accessibility, disablement, removal, and RV-37 evidence","action":"satisfy upstream blockers, provision exact native platforms and public search environments, then run AT-WEB-001 and RV-37 separately per platform","credential":"search-provider, network, proxy, certificate, platform, accessibility, and independent reviewer credentials","payment":"search, proxy, certificate, platform, network, accessibility, or independent evaluator costs if applicable"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"bounded_retrieval_complete":True,"citation_freshness_complete":True,"download_quarantine_complete":True,"hostile_content_refusal_complete":True,"private_disclosure_preview_complete":True,"native_platform_campaign_complete":False,"accessibility_removal_complete":False,"rv37_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_160_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"public_research_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=160,root=ROOT,output="artifacts/sprints/sprint-160/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-WEB-001","AT-WEB-001","SR-WEB-001","SR-WEB-002","SR-WEB-003","SR-WEB-004","RV-37"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
