#!/usr/bin/env python3
"""Build truthful Sprint 85 local GitHub mutation evidence."""
from pathlib import Path
from typing import Final
try: from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError: from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","capabilities/knowledge/Cargo.toml","capabilities/knowledge/src/lib.rs","capabilities/knowledge/src/github_mutation.rs","capabilities/knowledge/src/github_provider.rs","capabilities/knowledge/src/github_triage.rs","docs/guides/github-mutation-and-recovery.md","docs/security/repository-safety.md","docs/verification/sprint-85-github-mutation-corpus.json","artifacts/sprints/sprint-84/local-evidence-report.json","scripts/github_mutation_contract.py","tests/test_github_mutation_contract.py","supply-chain/dependency-hashes.sha256","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","scripts/sprint_evidence_recorder.py","scripts/sprint_85_evidence.py","tests/test_sprint_85_evidence.py")
COMMANDS:Final=(("github-mutation-rust-contract",("cargo","test","-p","agentmage-capability-knowledge","github_mutation::tests","--lib")),("github-mutation-artifact-contract",("python3","-m","unittest","tests.test_github_mutation_contract")),("runtime-schema-contract",("npm","run","-s","schemas:test")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_85_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0] for i in COMMANDS[:2]); IMPLEMENTED:Final={"mutation_class_count":14,"rust_test_count":6,"corpus_case_count":56,"prohibited_operation_count":12,"effect_executor_count":0,"native_mutation_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-84-BLOCKED","owner":"85"},{"code":"NATIVE-GITHUB-MUTATION-SIGNED-PUSH-AND-REVIEW-ABSENT","owner":"85.1.3.4"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"rust_test_count":6,"corpus_case_count":56,"native_mutation_executed":False,"signed_commit_created":False,"push_executed":False,"independent_review":False,"sprint_gate_closed":False}
SUMMARY:Final={"local_sprint_85_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_84_closed":False,"native_github_mutation_complete":False,"signed_push_complete":False,"independent_review_present":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=85,root=ROOT,output="artifacts/sprints/sprint-85/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=("SR-GOV-010","SR-ACC-001","SR-ACC-002","SR-ACC-003","SR-ACC-004","SR-ACC-005","SR-ACC-006","SR-ACC-007","SR-DAT-002","SR-OPS-001","SR-OPS-002","SR-TST-005","SR-TST-012","SR-GIT-002","SR-GIT-008","SR-GIT-009","SR-GIT-010","SR-GIT-011","SR-GIT-012"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
