#!/usr/bin/env python3
"""Build truthful Sprint 161 local-continuity evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/local_continuity.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-161/local-continuity-corpus.json","scripts/local_continuity_contract.py","tests/test_local_continuity_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_161_evidence.py","tests/test_sprint_161_evidence.py")
COMMANDS:Final=(("local-continuity-rust",("cargo","test","-p","agentmage-kernel-engine","local_continuity::tests","--lib")),("local-continuity-corpus",("python3","-m","unittest","tests.test_local_continuity_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_161_evidence")));FOCUSED_COMMANDS:Final=tuple(x[0]for x in COMMANDS[:3])
IMPLEMENTED:Final={"root_kind_count":9,"failure_count":13,"snapshot_stage_count":8,"audit_transition_count":6,"change_count":10,"record_count":12,"backup_case_count":936,"checkpoint_case_count":720,"plaintext_count":0,"raw_credential_count":0,"false_complete_count":0,"canonical_preconfirm_mutation_count":0,"stale_current_count":0,"promotion_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-11-22-32-73-102-157-158-BLOCKED","owner":"161"},{"code":"BLOCKED_EXTERNAL","platform":"native Fedora, Ubuntu, and Windows local storage, clean-device restore, accessibility, residue, and independent review environments","artifact":"untouched encrypted snapshot, integrity, root rejection, interruption, migration, rollback, retention, deletion, cancellation, accessibility, residue, checkpoint, resume, invalidation, RV-39, and RV-47 evidence","action":"satisfy upstream blockers, provision exact native storage and clean-device environments, then run AT-BKC-001, AT-CKP-001, local RV-39, and checkpoint RV-47 separately per platform","credential":"platform key-store, filesystem, clean-device, accessibility, and independent reviewer credentials","payment":"platform, storage, accessibility, or independent evaluator costs if applicable"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"snapshot_contract_complete":True,"unsafe_root_refusal_complete":True,"staged_restore_complete":True,"checkpoint_contract_complete":True,"transitive_invalidation_complete":True,"deterministic_resume_complete":True,"native_platform_campaign_complete":False,"clean_device_accessibility_complete":False,"rv39_47_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_161_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"local_continuity_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=161,root=ROOT,output="artifacts/sprints/sprint-161/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-BKC-001","AM-CKP-001","AT-BKC-001","AT-CKP-001","SR-BCK-001","SR-BCK-002","SR-BCK-005","SR-AUD-006","RV-39","RV-47"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
