#!/usr/bin/env python3
"""Build truthful Sprint 154 cloud correlation evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/cloud_delivery_correlation.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-154/cloud-delivery-correlation-corpus.json","scripts/cloud_delivery_correlation_contract.py","tests/test_cloud_delivery_correlation_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_154_evidence.py","tests/test_sprint_154_evidence.py")
COMMANDS:Final=(("correlation-rust",("cargo","test","-p","agentmage-kernel-engine","cloud_delivery_correlation::tests","--lib")),("correlation-corpus",("python3","-m","unittest","tests.test_cloud_delivery_correlation_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_154_evidence")));FOCUSED_COMMANDS:Final=tuple(item[0]for item in COMMANDS[:3])
IMPLEMENTED:Final={"provider_count":3,"view_count":6,"attack_count":14,"association_class_count":6,"fixture_count":4,"case_count":6048,"causal_claim_count":0,"inherited_authority_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-129-131-152-153-BLOCKED","owner":"154"},{"code":"BLOCKED_EXTERNAL","platform":"native cloud, delivery, productivity, incident, telemetry, and billing providers plus independent review environment","artifact":"untouched native identity, source, time, cost, allocation, conflicting-evidence, causal-restraint, recomputation, reviewer, and authority-absence evidence","action":"satisfy Sprint 129, 131, and 152-153 external tuples, then run AT-CCST-001, RV-14, RV-27, and RV-34 native cross-system campaigns","credential":"all cloud, delivery, productivity, incident, telemetry, and billing credentials named by upstream sprints","payment":"provider, telemetry, billing, and independent evaluator costs if applicable"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"native_identity_complete":True,"source_and_time_complete":True,"cost_context_complete":True,"association_labeling_complete":True,"causal_restraint_complete":True,"authority_absence_complete":True,"native_cross_system_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_154_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"cloud_correlation_support_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=154,root=ROOT,output="artifacts/sprints/sprint-154/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-CCST-001","AT-CCST-001","SR-CLD-001","SR-CLD-002","SR-CLD-003","RV-14","RV-27","RV-34"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
