#!/usr/bin/env python3
"""Build truthful Sprint 91 local scheduled-authority evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","kernel/engine/Cargo.toml","kernel/engine/src/lib.rs","kernel/engine/src/job_scheduler.rs","kernel/engine/src/scheduled_authority.rs","docs/guides/read-only-jobs-and-schedules.md","docs/guides/scheduled-authority.md","docs/verification/sprint-91-scheduled-authority-corpus.json","artifacts/sprints/sprint-90/local-evidence-report.json","scripts/scheduled_authority_contract.py","tests/test_scheduled_authority_contract.py","supply-chain/dependency-hashes.sha256","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","scripts/sprint_evidence_recorder.py","scripts/sprint_91_evidence.py","tests/test_sprint_91_evidence.py")
COMMANDS:Final=(("scheduled-authority-rust-contract",("cargo","test","-p","agentmage-kernel-engine","scheduled_authority::tests","--lib")),("scheduled-authority-artifact-contract",("python3","-m","unittest","tests.test_scheduled_authority_contract")),("runtime-schema-contract",("npm","run","-s","schemas:test")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_91_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0] for i in COMMANDS[:2]);IMPLEMENTED:Final={"predeclarable_effect_count":3,"denied_effect_count":3,"control_state_count":5,"rust_test_count":6,"corpus_case_count":64,"effect_executor_count":0,"native_effect_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-90-BLOCKED","owner":"91"},{"code":"NATIVE-SCHEDULED-AUTHORITY-EFFECT-STOP-AND-REVIEW-ABSENT","owner":"91.1.3.3-91.1.3.5"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"rust_test_count":6,"corpus_case_count":64,"native_scheduled_effect_executed":False,"emergency_stop_executed":False,"descendant_termination_observed":False,"independent_review":False,"sprint_gate_closed":False}
SUMMARY:Final={"local_sprint_91_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_90_closed":False,"native_scheduled_authority_complete":False,"native_recovery_complete":False,"independent_review_present":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=91,root=ROOT,output="artifacts/sprints/sprint-91/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=("SR-GOV-010","SR-ACC-001","SR-ACC-002","SR-ACC-003","SR-ACC-004","SR-ACC-005","SR-ACC-006","SR-ACC-007","SR-AI-004","SR-AI-005","SR-OPS-001","SR-OPS-002","SR-OPS-006","SR-TST-005","SR-TST-011"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
