#!/usr/bin/env python3
"""Build truthful Sprint 96 local update and maintenance evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","kernel/engine/Cargo.toml","kernel/engine/src/lib.rs","kernel/engine/src/update_maintenance.rs","artifacts/sprints/sprint-96/update-maintenance-corpus.json","scripts/update_maintenance_contract.py","tests/test_update_maintenance_contract.py","supply-chain/dependency-hashes.sha256","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","scripts/sprint_evidence_recorder.py","scripts/sprint_96_evidence.py","tests/test_sprint_96_evidence.py")
COMMANDS:Final=(("update-maintenance-rust-contract",("cargo","test","-p","agentmage-kernel-engine","update_maintenance::tests","--lib")),("update-maintenance-artifact-contract",("python3","-m","unittest","tests.test_update_maintenance_contract")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_96_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0] for i in COMMANDS[:2]);IMPLEMENTED:Final={"attack_recovery_class_count":18,"case_count":72,"dependency_component_count":498,"removal_disposition_count":498,"offline_preview_contract_count":1,"signed_package_count":0,"staged_activation_count":0,"rollback_execution_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-95-BLOCKED","owner":"96"},{"code":"SIGNED-UPDATE-NATIVE-VULNERABILITY-FEED-AND-INDEPENDENT-REVIEW-ABSENT","owner":"96.1.1.1-96.1.1.2-96.1.3.4-96.AC2-96.AC5"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"case_count":72,"dependency_inventory_complete":True,"license_inventory_complete":True,"hash_inventory_complete":True,"sbom_closure_complete":True,"removal_plan_complete":True,"current_vulnerability_feed_present":False,"native_update_observed":False,"independent_review":False,"sprint_gate_closed":False}
SUMMARY:Final={"local_sprint_96_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_95_closed":False,"signed_update_complete":False,"vulnerability_review_complete":False,"independent_review_present":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=96,root=ROOT,output="artifacts/sprints/sprint-96/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=("SR-DAT-005","SR-DAT-006","SR-DAT-007","SR-DAT-008","SR-DAT-009","SR-DAT-010","SR-DAT-011","SR-DAT-012","SR-SUP-002","SR-SUP-003","SR-SUP-004","SR-SUP-005","SR-SUP-006","SR-SUP-007","SR-SUP-008","SR-SUP-009","SR-SUP-010","SR-SUP-011","SR-SUP-012","SR-SUP-013","SR-OPS-006","SR-OPS-007","SR-OPS-008","SR-OPS-009","SR-OPS-010","SR-TST-003","SR-TST-005","SR-TST-007","SR-TST-008","SR-TST-009","SR-TST-010","SR-TST-011","RV-19","RV-21","RV-22"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
