#!/usr/bin/env python3
"""Build truthful Sprint 147 recurring-obligation evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/financial_domain.rs","kernel/engine/src/recurring_obligation.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-147/obligation-corpus.json","scripts/recurring_obligation_contract.py","tests/test_recurring_obligation_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_147_evidence.py","tests/test_sprint_147_evidence.py")
COMMANDS:Final=(("obligation-rust",("cargo","test","-p","agentmage-kernel-engine","recurring_obligation::tests","--lib")),("obligation-corpus",("python3","-m","unittest","tests.test_recurring_obligation_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_147_evidence")));FOCUSED_COMMANDS:Final=tuple(item[0]for item in COMMANDS[:3]);IMPLEMENTED:Final={"obligation_kind_count":8,"mutation_family_count":12,"failure_family_count":10,"fixture_case_count":5760,"authority_count":0,"false_completion_count":0,"financial_effect_count":0,"hidden_uncertainty_count":0,"citation_loss_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-131-138-143-146-BLOCKED","owner":"147"},{"code":"BLOCKED_EXTERNAL","platform":"native financial and communication provider accounts with recurring transaction and correspondence history","artifact":"untouched native detection, identity, citation, hostile-content, reminder, draft, security, reviewer, and removal evidence","action":"provision exact provider accounts, credentials, recurring history, and correspondence, then run AT-BIL-001, RV-31, and RV-33 native campaigns","credential":"applicable financial and communication provider credentials","payment":"provider subscription costs if applicable"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"recurring_detection_complete":True,"model_status_separation_complete":True,"citation_links_complete":True,"local_reminders_complete":True,"communication_drafts_bounded":True,"financial_effects_absent":True,"native_provider_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_147_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"native_obligation_support_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=147,root=ROOT,output="artifacts/sprints/sprint-147/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-BIL-001","AT-BIL-001","SR-FIN-003","SR-FIN-004","SR-FIN-006","RV-31","RV-33"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
