#!/usr/bin/env python3
"""Build truthful Sprint 76 local desktop experience evidence."""
from pathlib import Path
from typing import Final
try: from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError: from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT: Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS: Final=("Cargo.toml","Cargo.lock","shells/host/Cargo.toml","shells/host/src/lib.rs","shells/host/src/desktop_experience.rs","kernel/contracts/src/conversation.rs","schemas/runtime/thin-client-request.schema.json","schemas/runtime/thin-client-event.schema.json","docs/architecture/thin-client-boundary.md","docs/architecture/desktop-thin-client.md","docs/guides/conversations.md","docs/guides/desktop-conversation-workspace.md","docs/verification/sprint-76-desktop-corpus.json","scripts/desktop_experience_contract.py","tests/test_desktop_experience_contract.py","supply-chain/dependency-hashes.sha256","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","scripts/sprint_evidence_recorder.py","scripts/sprint_76_evidence.py","tests/test_sprint_76_evidence.py")
COMMANDS: Final=(("desktop-rust-contract",("cargo","test","-p","agentmage-host","desktop_experience::tests","--all-features")),("desktop-artifact-contract",("python3","-m","unittest","tests.test_desktop_experience_contract")),("runtime-schema-contract",("npm","run","-s","schemas:test")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_76_evidence")))
FOCUSED_COMMANDS: Final=tuple(item[0] for item in COMMANDS[:2])
IMPLEMENTED: Final={"architecture_selection":True,"navigation_filter_count":9,"transcript_item_kind_count":11,"conversation_action_count":7,"checkpoint_dimension_count":6,"approval_kind_count":4,"corpus_case_count":42,"external_web_service_count":0,"client_authority_count":0,"client_effect_count":0,"native_desktop_package":False,"platform_support":False}
BLOCKERS: Final=({"code":"UPSTREAM-SPRINT-75-BLOCKED","owner":"76.1"},{"code":"NATIVE-DESKTOP-SECURITY-EVIDENCE-ABSENT","owner":"76.1.3.4"})
VERIFICATION: Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"rust_test_count":9,"corpus_case_count":42,"external_web_service_count":0,"client_authority_count":0,"client_effect_count":0,"native_protocol_parity":False,"native_accessibility":False,"clean_install":False,"independent_review":False,"sprint_gate_closed":False}
SUMMARY: Final={"local_sprint_76_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_75_closed":False,"native_desktop_evidence_complete":False,"native_security_evidence_complete":False,"signed_package_present":False,"independent_review_present":False,"release_approval":False}
DEFINITION: Final=SprintEvidenceDefinition(sprint=76,root=ROOT,output="artifacts/sprints/sprint-76/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=("SR-PLT-001","SR-PLT-002","SR-PLT-003","SR-PLT-004","SR-PLT-005","SR-PLT-006","SR-PLT-007","SR-PLT-008","SR-PLT-009","SR-PLT-010","SR-ACC-001","SR-TST-007","SR-TST-008","SR-TST-009","SR-CIV-006","SR-CIV-007","SR-CIV-008","SR-CIV-009"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__": raise SystemExit(main(DEFINITION))
