#!/usr/bin/env python3
"""Build truthful Sprint 153 provider-observer evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/cloud_observer.rs","kernel/engine/src/cloud_provider_observer.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-153/provider-observer-corpus.json","scripts/cloud_provider_observer_contract.py","tests/test_cloud_provider_observer_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_153_evidence.py","tests/test_sprint_153_evidence.py")
COMMANDS:Final=(("provider-rust",("cargo","test","-p","agentmage-kernel-engine","cloud_provider_observer::tests","--lib")),("provider-corpus",("python3","-m","unittest","tests.test_cloud_provider_observer_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_153_evidence")));FOCUSED_COMMANDS:Final=tuple(item[0]for item in COMMANDS[:3])
IMPLEMENTED:Final={"provider_count":3,"read_count":10,"attack_count":16,"state_count":8,"fixture_count":5,"prohibited_count":11,"case_count":19200,"secret_disclosure_count":0,"escape_count":0,"provider_effect_count":0,"residual_authority_count":0,"promotion_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-103-125-152-BLOCKED","owner":"153"},{"code":"BLOCKED_EXTERNAL","platform":"isolated AWS, Azure, and Google Cloud provider accounts plus independent read-only review environment","artifact":"untouched native hierarchy, identity, scope, query, telemetry, security, deployment, cost, billing, isolation, throttling, version-skew, reviewer, revocation, and removal evidence","action":"provision exact AWS, Azure, and Google Cloud accounts and credentials, then run AT-AWS-001, AT-AZR-001, AT-GCP-001, RV-23, RV-24, RV-26, RV-29, RV-34, and RV-35 native campaigns","credential":"AWS role credential, Azure service principal credential, and Google Cloud workload identity credential","payment":"cloud account, resource, telemetry, and independent evaluator costs if applicable"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"aws_contract_complete":True,"azure_contract_complete":True,"gcp_contract_complete":True,"native_identity_preservation_complete":True,"prohibited_families_absent":True,"bounded_recovery_complete":True,"native_provider_campaigns_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_153_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"native_cloud_provider_support_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=153,root=ROOT,output="artifacts/sprints/sprint-153/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-AWS-001","AM-AZR-001","AM-GCP-001","AT-AWS-001","AT-AZR-001","AT-GCP-001","SR-CLD-001","SR-CLD-002","SR-CLD-003","RV-23","RV-24","RV-26","RV-29","RV-34","RV-35"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
