#!/usr/bin/env python3
"""Build truthful Sprint 123 local provider-resilience evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","DELIVERY-SYSTEM.md","SECURITY-REVIEW.md","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-123/provider-resilience-corpus.json","scripts/extreme_provider_campaign.py","tests/test_extreme_provider_campaign.py","scripts/sprint_evidence_recorder.py","scripts/sprint_123_evidence.py","tests/test_sprint_123_evidence.py")
COMMANDS:Final=(("provider-resilience-corpus",("python3","-m","unittest","tests.test_extreme_provider_campaign")),("dependency-boundary-contract",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_123_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:2]);IMPLEMENTED:Final={"conformance_case_count":2048,"attack_case_count":2048,"blocker_case_count":512,"approved_live_environment_count":0,"native_fuzz_run_count":0,"prolonged_campaign_minutes":0,"review_vector_count":0,"promoted_provider_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-122-BLOCKED","owner":"123"},{"code":"BLOCKED-EXTERNAL-AT-XTE-001","owner":"123"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"harness_contract_complete":True,"cross_adapter_fixture_complete":True,"fake_fault_campaign_complete":True,"approved_live_campaign_complete":False,"native_fuzz_complete":False,"prolonged_resource_complete":False,"rv15_17_complete":False,"rv23_29_complete":False,"at_xte_001_complete":False,"independent_red_team_review":False,"remote_route_qualification_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_123_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_122_closed":False,"provider_support_changed":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=123,root=ROOT,output="artifacts/sprints/sprint-123/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-XTE-001","AT-XTE-001","SR-DEL-012","SR-DEL-013","SR-DEL-014","RV-15","RV-16","RV-17","RV-23","RV-24","RV-25","RV-26","RV-27","RV-28","RV-29"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
