#!/usr/bin/env python3
"""Build truthful Sprint 138 communication write-safety evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/communication_write_safety.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-138/communication-write-corpus.json","scripts/communication_write_contract.py","tests/test_communication_write_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_138_evidence.py","tests/test_sprint_138_evidence.py")
COMMANDS:Final=(("communication-write-rust",("cargo","test","-p","agentmage-kernel-engine","communication_write_safety::tests","--lib")),("communication-write-corpus",("python3","-m","unittest","tests.test_communication_write_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_138_evidence")));FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"provider_count":8,"operation_count":14,"bound_field_count":24,"fixture_case_count":12000,"field_mutation_case_count":11520,"uncertainty_schedule_count":5000,"unauthorized_effect_count":0,"duplicate_effect_count":0,"false_completion_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-132-137-BLOCKED","owner":"138"},{"code":"BLOCKED_EXTERNAL","platform":"native Outlook, Gmail, standard mail, Proton Bridge, Teams, and Slack provider accounts","artifact":"untouched cross-provider effect, postcondition, cancellation, security, independent-reviewer, and reconciliation evidence","action":"provision every exact provider account and credential, then run AT-COMW-001 plus RV-25, RV-26, and RV-31 native campaigns","credential":"all provider-specific credentials recorded by Sprints 132 through 137","payment":"provider subscription costs if applicable"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"operation_specific_contracts_complete":True,"exact_approval_complete":True,"persisted_intent_complete":True,"reconciliation_complete":True,"mutation_and_schedule_floors_complete":True,"native_cross_provider_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_138_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprints_132_137_closed":False,"native_write_safety_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=138,root=ROOT,output="artifacts/sprints/sprint-138/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-COMW-001","AT-COMW-001","SR-PRD-001","SR-PRD-005","SR-PRD-006","SR-PRD-007","RV-25","RV-26","RV-31"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
