#!/usr/bin/env python3
"""Build truthful Sprint 114 local infrastructure evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","kernel/engine/Cargo.toml","kernel/engine/src/lib.rs","kernel/engine/src/infrastructure_safety.rs","SECURITY-REVIEW.md","DELIVERY-SYSTEM.md","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-114/infrastructure-safety-corpus.json","scripts/infrastructure_safety_contract.py","tests/test_infrastructure_safety_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_114_evidence.py","tests/test_sprint_114_evidence.py")
COMMANDS:Final=(("infrastructure-rust-contract",("cargo","test","-p","agentmage-kernel-engine","infrastructure_safety::tests","--lib")),("infrastructure-corpus-contract",("python3","-m","unittest","tests.test_infrastructure_safety_contract")),("dependency-boundary-contract",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_114_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"tool_fixture_count":2,"read_case_count":24,"plan_case_count":64,"attack_case_count":2048,"fault_case_count":512,"live_backend_contact_count":0,"sensitive_disclosure_count":0,"unsafe_apply_count":0,"promoted_tool_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-113-BLOCKED","owner":"114"},{"code":"BLOCKED-EXTERNAL-IAC-AT-IAC-001-RV-29","owner":"114"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"saved_plan_binding":True,"authority_separation":True,"unknown_state_blocks_retry":True,"supported_version_matrix_complete":False,"rv29_complete":False,"at_iac_001_complete":False,"independent_human_review":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_114_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_113_closed":False,"live_iac_support":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=114,root=ROOT,output="artifacts/sprints/sprint-114/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=("AM-IAC-001","AT-IAC-001","SR-DEL-*","RV-25","RV-28","RV-29"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
