#!/usr/bin/env python3
"""Build truthful Sprint 164 model-management evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","TASKS.md","SECURITY-REVIEW.md","MODEL-PROVENANCE-POLICY.md","docs/decisions/0027-muse-first-model-neutral-runtime-and-evaluation.md","kernel/engine/src/lib.rs","kernel/engine/src/model_management.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-164/model-management-corpus.json","scripts/model_management_contract.py","tests/test_model_management_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_164_evidence.py","tests/test_sprint_164_evidence.py")
COMMANDS:Final=(("model-management-rust",("cargo","test","-p","agentmage-kernel-engine","model_management::tests","--lib")),("model-management-corpus",("python3","-m","unittest","tests.test_model_management_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_164_evidence")));FOCUSED_COMMANDS:Final=tuple(x[0]for x in COMMANDS[:3]);IMPLEMENTED:Final={"intent_count":13,"mutation_count":24,"transition_count":10,"outcome_count":13,"fixture_case_count":3120,"silent_activation_count":0,"partial_activation_count":0,"substituted_profile_count":0,"unconfirmed_effect_count":0,"approved_profile_execution_count":0,"promotion_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-14-15-23-157-158-163-BLOCKED","owner":"164"},{"code":"BLOCKED_EXTERNAL","platform":"catalog signing and approved model artifact infrastructure plus native Fedora, Ubuntu, Windows, accessibility, strict-local, clean-install, and independent review environments","artifact":"untouched approved-profile acquisition, import, resume, signature, scan, format, hardware, runtime self-test, atomic activation, rollback, removal, storage cleanup, accessibility, strict-local restoration, AT-MGR-001, and RV-40 evidence","action":"satisfy upstream blockers, provision one signed approved compatible profile and exact native environments, then run the complete acquisition, activation, interruption, rollback, removal, accessibility, strict-local, AT-MGR-001, and RV-40 campaigns","credential":"catalog-signing, model-source, artifact, platform key-store, accessibility, and independent reviewer credentials","payment":"model, signing, storage, platform, accessibility, or independent evaluator costs if applicable"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"chat_intent_contract_complete":True,"exact_preview_confirmation_complete":True,"isolated_installer_scope_complete":True,"quarantine_lifecycle_contract_complete":True,"atomic_activation_rollback_contract_complete":True,"mutation_and_interruption_contract_complete":True,"approved_profile_campaign_complete":False,"native_manifest_reconciliation_complete":False,"native_accessibility_removal_complete":False,"rv40_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_164_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"approved_profile_execution_count":0,"model_management_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=164,root=ROOT,output="artifacts/sprints/sprint-164/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-MGR-001","AT-MGR-001","SR-MGM-002","SR-MGM-003","RV-40"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
