#!/usr/bin/env python3
"""Build truthful Sprint 98 local safe-mode and recovery evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","kernel/engine/Cargo.toml","kernel/engine/src/lib.rs","kernel/engine/src/update_maintenance.rs","kernel/engine/src/backup_migration.rs","kernel/engine/src/maintenance_recovery.rs","docs/operations/maintenance-and-recovery.md","artifacts/sprints/sprint-96/local-evidence-report.json","artifacts/sprints/sprint-97/backup-migration-corpus.json","artifacts/sprints/sprint-98/maintenance-recovery-corpus.json","scripts/maintenance_recovery_contract.py","tests/test_maintenance_recovery_contract.py","supply-chain/dependency-hashes.sha256","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","scripts/sprint_evidence_recorder.py","scripts/sprint_98_evidence.py","tests/test_sprint_98_evidence.py")
COMMANDS:Final=(("maintenance-recovery-rust-contract",("cargo","test","-p","agentmage-kernel-engine","maintenance_recovery::tests","--lib")),("backup-migration-rust-contract",("cargo","test","-p","agentmage-kernel-engine","backup_migration::tests","--lib")),("update-maintenance-rust-contract",("cargo","test","-p","agentmage-kernel-engine","update_maintenance::tests","--lib")),("maintenance-recovery-artifact-contract",("python3","-m","unittest","tests.test_maintenance_recovery_contract")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_98_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0] for i in COMMANDS[:4]);IMPLEMENTED:Final={"safe_mode_disabled_capability_count":8,"diagnostic_subsystem_count":6,"failure_class_count":9,"case_count":72,"native_recovery_execution_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-97-BLOCKED","owner":"98"},{"code":"NATIVE-MAINTENANCE-RECOVERY-CROSS-PLATFORM-AND-INDEPENDENT-REVIEW-ABSENT","owner":"98.1-native-98.AC1-98.AC3"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"case_count":72,"optional_capability_count_in_safe_mode":0,"raw_diagnostic_content_count":0,"secret_diagnostic_count":0,"network_count":0,"native_recovery_execution_count":0,"independent_review":False,"sprint_gate_closed":False}
SUMMARY:Final={"local_sprint_98_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_97_closed":False,"native_maintenance_recovery_complete":False,"cross_platform_recovery_complete":False,"independent_review_present":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=98,root=ROOT,output="artifacts/sprints/sprint-98/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:3]),security_requirement_ids=("SR-DAT-005","SR-DAT-006","SR-DAT-007","SR-DAT-008","SR-DAT-009","SR-DAT-010","SR-DAT-011","SR-DAT-012","SR-SUP-002","SR-SUP-003","SR-SUP-004","SR-SUP-005","SR-SUP-006","SR-SUP-007","SR-SUP-008","SR-SUP-009","SR-SUP-010","SR-SUP-011","SR-SUP-012","SR-SUP-013","SR-OPS-006","SR-OPS-007","SR-OPS-008","SR-OPS-009","SR-OPS-010","SR-TST-003","SR-TST-005","SR-TST-007","SR-TST-008","SR-TST-009","SR-TST-010","SR-TST-011","RV-19","RV-21","RV-22"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
