#!/usr/bin/env python3
"""Build truthful Sprint 75 local aggregate evidence."""
from pathlib import Path
from typing import Final
try: from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError: from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT: Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS: Final=("Cargo.toml","Cargo.lock","capabilities/knowledge/src/connected_connector.rs","capabilities/knowledge/src/github_provider.rs","capabilities/knowledge/src/hosted_repository.rs","capabilities/knowledge/src/github_triage.rs","capabilities/knowledge/src/pull_request_review.rs","artifacts/sprints/sprint-70/local-evidence-report.json","artifacts/sprints/sprint-71/local-evidence-report.json","artifacts/sprints/sprint-72/local-evidence-report.json","artifacts/sprints/sprint-73/local-evidence-report.json","artifacts/sprints/sprint-74/local-evidence-report.json","supply-chain/dependency-hashes.sha256","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","docs/guides/v0.7-read-only-connected-profile.md","docs/security/future-hosted-write-exclusions.md","docs/verification/sprint-75-v0.7-acceptance-bundle.json","docs/verification/sprint-75-read-only-conformance.md","docs/verification/sprint-75-strict-local-regression.md","docs/verification/sprint-75-release-notes-and-capability-matrix.md","scripts/v07_read_only_contract.py","tests/test_v07_read_only_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_75_evidence.py","tests/test_sprint_75_evidence.py")
COMMANDS: Final=(("v07-read-only-contract",("python3","-m","unittest","tests.test_v07_read_only_contract")),("connector-contract",("python3","-m","unittest","tests.test_temporary_connector_contract","tests.test_github_provider_contract","tests.test_hosted_repository_contract","tests.test_github_triage_contract","tests.test_pull_request_review_contract")),("runtime-schema-contract",("npm","run","-s","schemas:test")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_75_evidence")))
FOCUSED_COMMANDS: Final=tuple(x[0] for x in COMMANDS[:3])
IMPLEMENTED: Final={"retained_sprint_report_count":5,"aggregate_artifact_count":4,"local_read_only_conformance":True,"future_write_exclusions":True,"connected_guide":True,"hosted_mutation_operation_count":0,"network_request_count":0,"native_acceptance":False,"strict_local_native_regression":False,"signed_gate_decision":False}
BLOCKERS: Final=({"code":"UPSTREAM-SPRINTS-70-74-BLOCKED","owner":"75.1"},{"code":"NATIVE-CONNECTOR-ACCEPTANCE-ABSENT","owner":"75.1.1.1"},{"code":"STRICT-LOCAL-NATIVE-REGRESSION-ABSENT","owner":"75.1.1.3"},{"code":"SIGNED-RELEASE-GATE-ABSENT","owner":"75.1.3.5"})
VERIFICATION: Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"retained_sprint_report_count":5,"hosted_mutation_operation_count":0,"network_request_count":0,"native_acceptance":False,"strict_local_native_regression":False,"sprint_gate_closed":False}
SUMMARY: Final={"local_sprint_75_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprints_closed":False,"native_connector_acceptance_complete":False,"strict_local_native_regression_complete":False,"credential_cache_cleanup_complete":False,"native_security_evidence_complete":False,"signed_gate_decision_present":False,"release_approval":False}
DEFINITION: Final=SprintEvidenceDefinition(sprint=75,root=ROOT,output="artifacts/sprints/sprint-75/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("SR-GOV-010","SR-ACC-002","SR-ACC-006","SR-ACC-007","SR-ACC-008","SR-DAT-002","SR-DAT-007","SR-NET-005","SR-NET-006","SR-OPS-001","SR-OPS-002","SR-OPS-003","SR-TST-004","SR-TST-005"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__": raise SystemExit(main(DEFINITION))
