#!/usr/bin/env python3
"""Build truthful Sprint 73 local evidence."""
from pathlib import Path
from typing import Final
try: from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError: from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT: Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS: Final=("Cargo.toml","Cargo.lock","capabilities/knowledge/Cargo.toml","capabilities/knowledge/src/hosted_repository.rs","capabilities/knowledge/src/github_triage.rs","capabilities/knowledge/src/lib.rs","schemas/runtime/hosted-local-relationship.schema.json","schemas/runtime/github-triage-item.schema.json","schemas/runtime/hosted-event-receipt.schema.json","schemas/runtime/examples/hosted-local-relationship.valid.json","schemas/runtime/examples/github-triage-item.valid.json","schemas/runtime/examples/hosted-event-receipt.valid.json","scripts/validate_planning_schemas.mjs","tests/test_planning_schemas.mjs","supply-chain/dependency-hashes.sha256","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","docs/architecture/github-read-only-triage.md","docs/guides/github-triage-review.md","docs/verification/sprint-73-github-triage-corpus.json","docs/verification/sprint-73-github-triage-dependencies.json","docs/verification/sprint-73-local-results.md","scripts/github_triage_contract.py","tests/test_github_triage_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_73_evidence.py","tests/test_sprint_73_evidence.py")
COMMANDS: Final=(("triage-unit",("cargo","test","-p","agentmage-capability-knowledge","github_triage::tests","--lib","--locked")),("triage-contract",("python3","-m","unittest","tests.test_github_triage_contract")),("runtime-schema-contract",("npm","run","-s","schemas:test")),("triage-strict-clippy",("cargo","clippy","-p","agentmage-capability-knowledge","--all-targets","--locked","--","-D","warnings")),("triage-format",("cargo","fmt","--all","--","--check")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_73_evidence")))
FOCUSED_COMMANDS: Final=tuple(x[0] for x in COMMANDS[:3])
IMPLEMENTED: Final={"rust_fixture_count":4,"corpus_case_count":60,"hosted_object_kind_count":7,"triage_reason_count":10,"runtime_schema_count":3,"unpublished_drafts":True,"externally_verified_event_admission":True,"actual_provider_inspection":False,"actual_signature_verification":False,"network_client_count":0,"provider_effect_count":0,"local_effect_count":0,"credential_material_count":0}
BLOCKERS: Final=({"code":"UPSTREAM-SPRINT-72-BLOCKED","owner":"73.1"},{"code":"PROVIDER-INSPECTION-AND-SIGNATURE-VERIFICATION-ABSENT","owner":"73.1.3.4"},{"code":"NATIVE-TRIAGE-SECURITY-CAMPAIGN-ABSENT","owner":"73.1.3.5"})
VERIFICATION: Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"corpus_case_count":60,"hosted_object_kind_count":7,"provider_effect_count":0,"local_effect_count":0,"credential_material_count":0,"native_campaign":False,"sprint_gate_closed":False}
SUMMARY: Final={"local_sprint_73_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_72_closed":False,"actual_provider_inspection_complete":False,"actual_signature_verification_complete":False,"hosted_local_correlation_complete":False,"native_security_evidence_complete":False,"independent_review_present":False,"release_approval":False}
DEFINITION: Final=SprintEvidenceDefinition(sprint=73,root=ROOT,output="artifacts/sprints/sprint-73/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=("SR-ACC-007","SR-ACC-008","SR-AI-005","SR-AI-007","SR-AI-010","SR-OPS-001","SR-OPS-002","SR-TST-004"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__": raise SystemExit(main(DEFINITION))
