#!/usr/bin/env python3
"""Build truthful Sprint 126 local release-checkpoint evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","README.md","PRD.md","TASKS.md","SECURITY-REVIEW.md","DELIVERY-SYSTEM.md","WINDOWS-BOUNDARIES.md","MODEL-PROVENANCE-POLICY.md","SECURITY.md","requirements/registry.json","requirements/traceability-report.json","architecture/status-model.json","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-126/release-checkpoint-corpus.json","scripts/release_checkpoint_contract.py","tests/test_release_checkpoint_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_126_evidence.py","tests/test_sprint_126_evidence.py")
COMMANDS:Final=(("release-checkpoint-contract",("python3","-m","unittest","tests.test_release_checkpoint_contract")),("traceability-currentness",("python3","scripts/traceability_report.py","--check")),("status-model-currentness",("python3","scripts/status_model.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_126_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"truth_document_count":8,"release_blocker_case_count":256,"signed_binary_manifest_count":0,"native_reproduction_count":0,"reviewer_signature_count":0,"user_release_approval_count":0,"release_package_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-125-BLOCKED","owner":"126"},{"code":"BLOCKED-EXTERNAL-RELEASE-CANDIDATE","owner":"126"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"requirement_graph_current":True,"documentation_truth_current":True,"summary_reconciliation_complete":True,"support_matrix_closed":True,"negative_release_gate_complete":True,"native_reproduction_complete":False,"signed_bom_complete":False,"rv01_30_complete":False,"rv49_complete":False,"at_ga_001_complete":False,"independent_review_complete":False,"user_approval_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_126_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_125_closed":False,"g_ga_closed":False,"release_package_produced":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=126,root=ROOT,output="artifacts/sprints/sprint-126/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-GA-001","AM-GAD-001","AT-GA-001","RV-01","RV-30","RV-49"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
