#!/usr/bin/env python3
"""Build truthful Sprint 151 finance-gate evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/finance_privacy.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-151/finance-privacy-corpus.json","scripts/finance_privacy_contract.py","tests/test_finance_privacy_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_151_evidence.py","tests/test_sprint_151_evidence.py")
COMMANDS:Final=(("privacy-rust",("cargo","test","-p","agentmage-kernel-engine","finance_privacy::tests","--lib")),("privacy-corpus",("python3","-m","unittest","tests.test_finance_privacy_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_151_evidence")));FOCUSED_COMMANDS:Final=tuple(x[0]for x in COMMANDS[:3]);IMPLEMENTED:Final={"prohibited_family_count":13,"surface_count":15,"attack_source_count":9,"removal_state_count":7,"scan_class_count":12,"case_count":12285,"undeclared_disclosure_count":0,"capability_shape_count":0,"external_effect_count":0,"canary_disclosure_count":0,"residual_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-142-150-BLOCKED","owner":"151"},{"code":"BLOCKED_EXTERNAL","platform":"all native finance providers, strict-local host, non-finance packs, backup/export destinations, and independent review environment","artifact":"untouched integrated privacy, canary, static, dynamic, compiled-artifact, provider-request, removal, restoration, reviewer, and support-matrix evidence","action":"satisfy every Sprint 142-150 external tuple, then run AT-FPRV-001, RV-18, RV-24, RV-33, and RV-35 native campaigns plus strict-local and non-finance restoration suites","credential":"all finance, backup, and export credentials recorded by Sprints 142-150","payment":"provider, host, backup, or evaluator costs if applicable"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"field_policy_complete":True,"receipted_flows_complete":True,"money_movement_absence_complete":True,"canary_campaign_complete":True,"removal_inventory_complete":True,"native_integrated_finance_campaign_complete":False,"finance_gate_closed":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_151_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprints_142_150_closed":False,"finance_epic_closed":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=151,root=ROOT,output="artifacts/sprints/sprint-151/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-FPRV-001","AT-FPRV-001","SR-FIN-001","SR-FIN-002","SR-FIN-003","SR-FIN-004","SR-FIN-005","SR-FIN-006","RV-18","RV-24","RV-33","RV-35"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
