#!/usr/bin/env python3
"""Build truthful Sprint 157 trusted-operation and audit evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","TRUSTED-OPERATIONS.md","CODEBASE-AUDIT.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/trusted_audit_contract.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-157/trusted-audit-corpus.json","scripts/trusted_audit_contract.py","tests/test_trusted_audit_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_157_evidence.py","tests/test_sprint_157_evidence.py")
COMMANDS:Final=(("trusted-audit-rust",("cargo","test","-p","agentmage-kernel-engine","trusted_audit_contract::tests","--lib")),("trusted-audit-corpus",("python3","-m","unittest","tests.test_trusted_audit_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_157_evidence")));FOCUSED_COMMANDS:Final=tuple(x[0]for x in COMMANDS[:3]);IMPLEMENTED:Final={"capability_count":5,"lifecycle_count":11,"platform_count":3,"fault_count":10,"path_disposition_count":9,"memory_record_kind_count":13,"trusted_case_count":1650,"audit_case_count":1170,"union_count":0,"effect_count":0,"audit_authority_count":0,"audit_completeness_count":0,"promotion_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-4-16-103-105-121-125-156-BLOCKED","owner":"157"},{"code":"BLOCKED_EXTERNAL","platform":"native Fedora, Ubuntu, Windows, and retained macOS topology plus signed release-manifest and independent review environments","artifact":"untouched native process, IPC, socket, path, network, secret, storage, cleanup, topology, manifest, diagnostic, reviewer, and whole-codebase-audit contract evidence","action":"satisfy upstream Sprint blockers, provision exact native platforms and signed manifest environment, then run AT-TRU-001, AT-CBA-001, and RV-36 through RV-48 native campaigns","credential":"platform, signing, repository, model/runtime, and independent reviewer credentials","payment":"platform, signing, model, hosting, or independent evaluator costs if applicable"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"trusted_contract_complete":True,"topology_contract_complete":True,"lifecycle_contract_complete":True,"audit_identity_complete":True,"project_memory_complete":True,"audit_topology_complete":True,"native_topology_campaign_complete":False,"signed_manifest_complete":False,"independent_review_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_157_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"trusted_operations_promoted":False,"whole_codebase_audit_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=157,root=ROOT,output="artifacts/sprints/sprint-157/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-TRU-001","AT-TRU-001","AM-CBA-001","AT-CBA-001","SR-CMD-001","SR-CMD-004","SR-TOP-001","SR-AUD-001","RV-36","RV-48"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
