#!/usr/bin/env python3
"""Build truthful Sprint 133 Teams evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/communications_teams.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-133/teams-corpus.json","scripts/communications_teams_contract.py","tests/test_communications_teams_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_133_evidence.py","tests/test_sprint_133_evidence.py")
COMMANDS:Final=(("teams-rust",("cargo","test","-p","agentmage-kernel-engine","communications_teams::tests","--lib")),("teams-corpus",("python3","-m","unittest","tests.test_communications_teams_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_133_evidence")));FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"profile_count":6,"mutation_family_count":17,"failure_family_count":9,"fixture_case_count":4590,"unauthorized_effect_count":0,"duplicate_effect_count":0,"removal_authority_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-132-BLOCKED","owner":"133"},{"code":"BLOCKED_EXTERNAL","platform":"Microsoft Teams organizational test tenant and accounts","artifact":"untouched native tenant capability, effect, event, security, reviewer, and removal evidence","action":"provision exact tenant/accounts/credentials and run AT-TMS-001 plus RV-23 through RV-26 and RV-31 native campaigns","credential":"Microsoft Graph delegated Teams credentials","payment":"Microsoft 365 tenant or provider costs if applicable"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"teams_identity_complete":True,"capability_discovery_complete":True,"exact_effect_complete":True,"failure_reconciliation_complete":True,"isolation_and_removal_complete":True,"native_provider_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_133_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_132_closed":False,"native_teams_support_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=133,root=ROOT,output="artifacts/sprints/sprint-133/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-TMS-001","AT-TMS-001","SR-PRD-005","SR-PRD-006","SR-PRD-007","RV-23","RV-24","RV-25","RV-26","RV-31"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
