#!/usr/bin/env python3
"""Build and validate truthful Sprint 70 local evidence."""
from __future__ import annotations
from pathlib import Path
from typing import Final
try:
    from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:
    from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT: Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS: Final=("Cargo.toml","Cargo.lock","capabilities/knowledge/Cargo.toml","capabilities/knowledge/src/connected_connector.rs","capabilities/knowledge/src/lib.rs","schemas/runtime/temporary-network-grant.schema.json","schemas/runtime/connector-cache-entry.schema.json","schemas/runtime/examples/temporary-network-grant.valid.json","schemas/runtime/examples/connector-cache-entry.valid.json","scripts/validate_planning_schemas.mjs","tests/test_planning_schemas.mjs","supply-chain/dependency-hashes.sha256","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","docs/architecture/temporary-connected-profile-and-cache.md","docs/guides/temporary-connected-profile-review.md","docs/verification/sprint-70-connector-corpus.json","docs/verification/sprint-70-connector-dependency-manifest.json","docs/verification/sprint-70-local-results.md","scripts/temporary_connector_contract.py","tests/test_temporary_connector_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_70_evidence.py","tests/test_sprint_70_evidence.py")
COMMANDS: Final=(("connector-unit",("cargo","test","-p","agentmage-capability-knowledge","connected_connector::tests","--lib","--locked")),("connector-contract",("python3","-m","unittest","tests.test_temporary_connector_contract")),("runtime-schema-contract",("npm","run","-s","schemas:test")),("connector-strict-clippy",("cargo","clippy","-p","agentmage-capability-knowledge","--all-targets","--locked","--","-D","warnings")),("connector-format",("cargo","fmt","--all","--","--check")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_70_evidence")))
FOCUSED_COMMANDS: Final=tuple(item[0] for item in COMMANDS[:3])
SECURITY_REQUIREMENTS: Final=("SR-GOV-010","SR-ACC-002","SR-ACC-007","SR-DAT-001","SR-DAT-002","SR-DAT-003","SR-DAT-004","SR-NET-003","SR-NET-004","SR-NET-005","SR-NET-006","SR-NET-007","SR-OPS-001","SR-OPS-002","SR-OPS-003")
IMPLEMENTED: Final={"connector_rust_fixture_count":4,"connector_corpus_case_count":60,"exact_visible_grant":True,"temporary_activation":True,"offline_restoration":True,"fresh_grant_retry":True,"powerless_cache_observation":True,"strict_local_default_unchanged":True,"actual_network_execution":False,"credential_derivation":False,"encrypted_cache_persistence":False,"network_client_count":0,"background_worker_count":0,"connector_account_count":0,"native_packet_capture":False,"independent_review":False}
BLOCKERS: Final=({"code":"UPSTREAM-SPRINT-69-BLOCKED","owner":"70.1"},{"code":"NETWORK-EXECUTOR-AND-ACCOUNT-ABSENT","owner":"70.1.1.6"},{"code":"ENCRYPTED-CACHE-PERSISTENCE-ABSENT","owner":"70.1.AC2"},{"code":"NATIVE-PACKET-CAPTURE-ABSENT","owner":"70.1.3.5"},{"code":"INDEPENDENT-BOUNDARY-REVIEW-ABSENT","owner":"70.1.3.5"})
VERIFICATION: Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"connector_corpus_case_count":60,"accepted_network_effect_count":0,"network_client_count":0,"credential_material_count":0,"connector_account_count":0,"cache_write_count":0,"offline_restoration_verified":True,"imported_authority_count":0,"native_packet_capture":False,"independent_review":False,"sprint_gate_closed":False}
SUMMARY: Final={"local_sprint_70_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_69_closed":False,"actual_connector_read_complete":False,"credential_derivation_complete":False,"encrypted_cache_lifecycle_complete":False,"native_network_evidence_complete":False,"independent_review_present":False,"release_approval":False}
DEFINITION: Final=SprintEvidenceDefinition(sprint=70,root=ROOT,output="artifacts/sprints/sprint-70/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=SECURITY_REQUIREMENTS,implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__": raise SystemExit(main(DEFINITION))
