#!/usr/bin/env python3
"""Build truthful Sprint 74 local evidence."""
from pathlib import Path
from typing import Final
try: from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError: from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT: Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS: Final=("Cargo.toml","Cargo.lock","capabilities/knowledge/Cargo.toml","capabilities/knowledge/src/pull_request_review.rs","capabilities/knowledge/src/lib.rs","schemas/runtime/pull-request-worktree-binding.schema.json","schemas/runtime/local-pull-request-review-packet.schema.json","schemas/runtime/examples/pull-request-worktree-binding.valid.json","schemas/runtime/examples/local-pull-request-review-packet.valid.json","scripts/validate_planning_schemas.mjs","tests/test_planning_schemas.mjs","supply-chain/dependency-hashes.sha256","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","docs/architecture/pull-request-local-review.md","docs/guides/pull-request-local-review.md","docs/verification/sprint-74-pr-review-corpus.json","docs/verification/sprint-74-pr-review-dependencies.json","docs/verification/sprint-74-local-results.md","scripts/pull_request_review_contract.py","tests/test_pull_request_review_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_74_evidence.py","tests/test_sprint_74_evidence.py")
COMMANDS: Final=(("pr-review-unit",("cargo","test","-p","agentmage-capability-knowledge","pull_request_review::tests","--lib","--locked")),("pr-review-contract",("python3","-m","unittest","tests.test_pull_request_review_contract")),("runtime-schema-contract",("npm","run","-s","schemas:test")),("pr-review-strict-clippy",("cargo","clippy","-p","agentmage-capability-knowledge","--all-targets","--locked","--","-D","warnings")),("pr-review-format",("cargo","fmt","--all","--","--check")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_74_evidence")))
FOCUSED_COMMANDS: Final=tuple(x[0] for x in COMMANDS[:3])
IMPLEMENTED: Final={"rust_fixture_count":4,"corpus_case_count":53,"review_dimension_count":7,"finding_state_count":8,"runtime_schema_count":2,"owned_worktree_contract_reused":True,"actual_pr_fetch_checkout":False,"actual_review_execution":False,"network_client_count":0,"publication_operation_count":0,"hosted_effect_count":0,"active_checkout_effect_count":0}
BLOCKERS: Final=({"code":"UPSTREAM-SPRINT-73-BLOCKED","owner":"74.1"},{"code":"PR-FETCH-CHECKOUT-AND-NATIVE-REVIEW-ABSENT","owner":"74.1.1.1"},{"code":"HOSTED-REFRESH-AND-REVIEW-CAMPAIGN-ABSENT","owner":"74.1.3.4"},{"code":"NATIVE-PR-SECURITY-CAMPAIGN-ABSENT","owner":"74.1.3.5"})
VERIFICATION: Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"corpus_case_count":53,"review_dimension_count":7,"finding_state_count":8,"publication_operation_count":0,"hosted_effect_count":0,"active_checkout_effect_count":0,"native_campaign":False,"sprint_gate_closed":False}
SUMMARY: Final={"local_sprint_74_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_73_closed":False,"actual_pr_fetch_checkout_complete":False,"actual_review_execution_complete":False,"hosted_refresh_complete":False,"native_security_evidence_complete":False,"independent_review_present":False,"release_approval":False}
DEFINITION: Final=SprintEvidenceDefinition(sprint=74,root=ROOT,output="artifacts/sprints/sprint-74/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=("SR-ACC-006","SR-ACC-007","SR-ACC-008","SR-AI-003","SR-AI-005","SR-AI-010","SR-TST-004","SR-TST-005"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__": raise SystemExit(main(DEFINITION))
