#!/usr/bin/env python3
"""Build truthful Sprint 129 identity-graph evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/productivity_identity_graph.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-129/identity-graph-corpus.json","scripts/productivity_identity_graph_contract.py","tests/test_productivity_identity_graph_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_129_evidence.py","tests/test_sprint_129_evidence.py")
COMMANDS:Final=(("identity-graph-rust",("cargo","test","-p","agentmage-kernel-engine","productivity_identity_graph::tests","--lib")),("identity-graph-corpus",("python3","-m","unittest","tests.test_productivity_identity_graph_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_129_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"identity_kind_count":13,"link_state_count":6,"attack_family_count":12,"fixture_case_count":936,"display_authorization_count":0,"stale_authorization_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-128-BLOCKED","owner":"129"},);VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"native_identity_contract_complete":True,"graph_mutation_contract_complete":True,"identity_confusion_resistance_complete":True,"removal_lineage_complete":True,"rv_32_local_graph_evidence_complete":True,"native_provider_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_129_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_128_closed":False,"identity_authority_broadening_count":0,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=129,root=ROOT,output="artifacts/sprints/sprint-129/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-PGR-001","AT-PGR-001","SR-PRD-002","RV-32"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
