#!/usr/bin/env python3
"""Build truthful Sprint 166 release-decision evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","TASKS.md","SECURITY-REVIEW.md","architecture/status-model.json","docs/decisions/0027-muse-first-model-neutral-runtime-and-evaluation.md","kernel/engine/src/lib.rs","kernel/engine/src/release_decision.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-166/release-decision-corpus.json","scripts/release_decision_contract.py","tests/test_release_decision_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_166_evidence.py","tests/test_sprint_166_evidence.py")
COMMANDS:Final=(("release-decision-rust",("cargo","test","-p","agentmage-kernel-engine","release_decision::tests","--lib")),("release-decision-corpus",("python3","-m","unittest","tests.test_release_decision_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_166_evidence")));FOCUSED_COMMANDS:Final=tuple(x[0]for x in COMMANDS[:3]);IMPLEMENTED:Final={"blocker_class_count":20,"non_pass_state_count":9,"fixture_case_count":180,"false_publication_count":0,"false_ga_closure_count":0,"substitution_count":0,"release_approval_count":0,"promotion_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-0-165-BLOCKED","owner":"166"},{"code":"BLOCKED_EXTERNAL","platform":"fresh disposable Fedora, Ubuntu, and Windows guests plus every provider, model, accessibility, performance, backup, recovery, update, removal, signing, fuzzing, and independent review environment","artifact":"untouched three-run platform lifecycles, complete provider/capability/model/audit matrices, signed manifests and packages, binary and Model BOMs, real RM-024 sanitizer/coverage/crash evidence, RV-01 through RV-49, independent reproduction, reviewer signatures, and explicit user approval","action":"satisfy every upstream blocker, provision all exact release candidates and environments, execute the complete published release and real-fuzz campaigns, reconcile current raw evidence, obtain independent signatures and explicit user approval, then sign the release decision","credential":"all provider, model, platform, signing, accessibility, fuzzing, and independent reviewer credentials","payment":"provider, model, hardware, hosted environment, signing, accessibility, or independent evaluator costs if applicable"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"independent_blocker_injection_complete":True,"non_pass_publication_denial_complete":True,"release_traceability_complete":False,"signed_manifest_reconciliation_complete":False,"independent_release_reproduction_complete":False,"real_rm024_complete":False,"explicit_user_approval_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_166_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"release_decision":"BLOCKED","release_approval_count":0,"package_publication_count":0,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=166,root=ROOT,output="artifacts/sprints/sprint-166/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-GAD-003","AM-GAD-004","AT-GA-003","AT-GA-004","RV-01","RV-49"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
