#!/usr/bin/env python3
"""Build truthful Sprint 88 local connector-write evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","capabilities/knowledge/Cargo.toml","capabilities/knowledge/src/lib.rs","capabilities/knowledge/src/connector_mutation.rs","docs/guides/connector-governance-and-recovery.md","docs/verification/sprint-87-connector-isolation-corpus.json","docs/verification/sprint-88-connector-write-corpus.json","artifacts/sprints/sprint-86/local-evidence-report.json","scripts/connector_mutation_contract.py","tests/test_connector_mutation_contract.py","supply-chain/dependency-hashes.sha256","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","scripts/sprint_evidence_recorder.py","scripts/sprint_88_evidence.py","tests/test_sprint_88_evidence.py")
COMMANDS:Final=(("connector-mutation-rust-contract",("cargo","test","-p","agentmage-capability-knowledge","connector_mutation::tests","--lib")),("connector-mutation-artifact-contract",("python3","-m","unittest","tests.test_connector_mutation_contract")),("runtime-schema-contract",("npm","run","-s","schemas:test")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_88_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0] for i in COMMANDS[:2]);IMPLEMENTED:Final={"connector_family_count":7,"rust_test_count":6,"corpus_case_count":56,"write_class_count":7,"result_class_count":4,"effect_executor_count":0,"native_mutation_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-87-BLOCKED","owner":"88"},{"code":"NATIVE-CONNECTOR-WRITE-RECOVERY-AND-REVIEW-ABSENT","owner":"88.1.3.3,88.1.3.5"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"rust_test_count":6,"corpus_case_count":56,"native_mutation_executed":False,"remote_reconciliation_executed":False,"rollback_executed":False,"independent_review":False,"sprint_gate_closed":False}
SUMMARY:Final={"local_sprint_88_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_87_closed":False,"native_connector_write_complete":False,"native_recovery_complete":False,"independent_review_present":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=88,root=ROOT,output="artifacts/sprints/sprint-88/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=("SR-GOV-010","SR-ACC-001","SR-ACC-002","SR-ACC-003","SR-ACC-004","SR-ACC-005","SR-ACC-006","SR-ACC-007","SR-ACC-008","SR-DAT-001","SR-DAT-002","SR-DAT-003","SR-NET-003","SR-NET-004","SR-NET-005","SR-NET-006","SR-OPS-001","SR-OPS-002","SR-CIV-001","SR-CIV-002","SR-CIV-003","SR-CIV-004","SR-CIV-005"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
