#!/usr/bin/env python3
"""Build truthful Sprint 135 standard-mail and Proton Bridge evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/communications_mail.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-135/mail-protocol-corpus.json","scripts/communications_mail_contract.py","tests/test_communications_mail_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_135_evidence.py","tests/test_sprint_135_evidence.py")
COMMANDS:Final=(("mail-rust",("cargo","test","-p","agentmage-kernel-engine","communications_mail::tests","--lib")),("mail-corpus",("python3","-m","unittest","tests.test_communications_mail_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_135_evidence")));FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"profile_count":7,"attack_family_count":15,"fault_family_count":12,"fixture_case_count":5040,"unauthorized_credential_disclosure_count":0,"unauthorized_effect_count":0,"duplicate_delivery_count":0,"false_completion_count":0,"removal_authority_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-132-BLOCKED","owner":"135"},{"code":"BLOCKED_EXTERNAL","platform":"IMAP, SMTP, JMAP servers and Proton Mail Bridge test accounts","artifact":"untouched native protocol negotiation, transport, delivery, security, reviewer, and removal evidence","action":"provision exact servers/accounts/credentials and Proton Bridge host, then run AT-MAIL-001 plus RV-23 through RV-26 and RV-31 native campaigns","credential":"server-specific IMAP, SMTP, JMAP, and Proton Bridge account credentials","payment":"mail provider or Proton subscription costs if applicable"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"protocol_identity_complete":True,"transport_downgrade_refusal_complete":True,"negotiated_registration_complete":True,"uncertain_reconciliation_complete":True,"removal_complete":True,"native_protocol_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_135_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_132_closed":False,"native_mail_support_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=135,root=ROOT,output="artifacts/sprints/sprint-135/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-MAIL-001","AT-MAIL-001","SR-PRD-005","SR-PRD-006","SR-PRD-007","RV-23","RV-24","RV-25","RV-26","RV-31"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
