#!/usr/bin/env python3
"""Build truthful Sprint 115 local release evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","kernel/engine/Cargo.toml","kernel/engine/src/lib.rs","kernel/engine/src/release_lifecycle.rs","SECURITY-REVIEW.md","DELIVERY-SYSTEM.md","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-115/release-lifecycle-corpus.json","scripts/release_lifecycle_contract.py","tests/test_release_lifecycle_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_115_evidence.py","tests/test_sprint_115_evidence.py")
COMMANDS:Final=(("release-rust-contract",("cargo","test","-p","agentmage-kernel-engine","release_lifecycle::tests","--lib")),("release-corpus-contract",("python3","-m","unittest","tests.test_release_lifecycle_contract")),("dependency-boundary-contract",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_115_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"tool_fixture_count":4,"manifest_case_count":64,"attack_case_count":2048,"fault_case_count":512,"live_environment_count":0,"hidden_effect_count":0,"automatic_advance_count":0,"promoted_tool_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-114-BLOCKED","owner":"115"},{"code":"BLOCKED-EXTERNAL-RELEASE-AT-REL-001","owner":"115"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"release_manifest_bound":True,"change_authority_separate":True,"fresh_compensation_required":True,"promoted_matrix_complete":False,"at_rel_001_complete":False,"independent_human_review":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_115_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_114_closed":False,"live_release_support":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=115,root=ROOT,output="artifacts/sprints/sprint-115/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=("AM-REL-001","AT-REL-001","SR-DEL-*","RV-25","RV-28"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
