#!/usr/bin/env python3
"""Build truthful Sprint 130 synchronization evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/productivity_sync.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-130/sync-corpus.json","scripts/productivity_sync_contract.py","tests/test_productivity_sync_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_130_evidence.py","tests/test_sprint_130_evidence.py")
COMMANDS:Final=(("sync-rust",("cargo","test","-p","agentmage-kernel-engine","productivity_sync::tests","--lib")),("sync-corpus",("python3","-m","unittest","tests.test_productivity_sync_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_130_evidence")));FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"fault_family_count":14,"transition_count":10,"fixture_case_count":1120,"event_authority_count":0,"removed_authority_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-129-BLOCKED","owner":"130"},);VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"sync_state_machine_complete":True,"visible_incomplete_state_complete":True,"event_authority_isolation_complete":True,"removal_cleanup_complete":True,"native_provider_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_130_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_129_closed":False,"sync_authority_broadening_count":0,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=130,root=ROOT,output="artifacts/sprints/sprint-130/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-SYNC-001","AT-SYNC-001","SR-PRD-003","RV-32"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
