#!/usr/bin/env python3
"""Build truthful Sprint 121 local Windows source evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","platforms/windows/Cargo.toml","platforms/windows/src/lib.rs","platforms/windows/src/delivery_contract.rs","platforms/windows/src/native_identity.rs","WINDOWS-BOUNDARIES.md","SECURITY-REVIEW.md","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-121/windows-delivery-corpus.json","scripts/windows_delivery_contract.py","tests/test_windows_delivery_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_121_evidence.py","tests/test_sprint_121_evidence.py")
COMMANDS:Final=(("windows-rust-contract",("cargo","test","-p","agentmage-platform-windows","--lib")),("windows-corpus-contract",("python3","-m","unittest","tests.test_windows_delivery_contract")),("dependency-boundary-contract",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_121_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"lifecycle_kind_count":8,"lifecycle_case_count":128,"attack_case_count":2048,"fault_case_count":512,"native_guest_execution_count":0,"signed_package_count":0,"external_effect_count":0,"promoted_platform_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-120-BLOCKED","owner":"121"},{"code":"BLOCKED-EXTERNAL-WINDOWS-AT-WIN-001","owner":"121"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"package_contract_complete":True,"ipc_contract_complete":True,"kvm_controller_contract_complete":True,"native_lifecycle_complete":False,"signature_timestamp_complete":False,"native_chat_complete":False,"rv01_complete":False,"rv02_complete":False,"rv05_complete":False,"at_win_001_complete":False,"independent_human_review":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_121_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_120_closed":False,"windows_platform_supported":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=121,root=ROOT,output="artifacts/sprints/sprint-121/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:1]),security_requirement_ids=("AM-WIN-001","AT-WIN-001","SR-PLT-001","SR-PLT-005","SR-PLT-006","SR-PLT-007","SR-PLT-008","SR-PLT-009","SR-PLT-010","SR-PLT-011","SR-PLT-012","SR-PLT-013","SR-PLT-014","SR-PLT-015","SR-PLT-016","SR-PLT-017","RV-01","RV-02","RV-05"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
