#!/usr/bin/env python3
"""Build truthful Sprint 132 Outlook evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","PRODUCTIVITY-SYSTEM.md","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/communications_outlook.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-132/outlook-corpus.json","scripts/communications_outlook_contract.py","tests/test_communications_outlook_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_132_evidence.py","tests/test_sprint_132_evidence.py")
COMMANDS:Final=(("outlook-rust",("cargo","test","-p","agentmage-kernel-engine","communications_outlook::tests","--lib")),("outlook-corpus",("python3","-m","unittest","tests.test_communications_outlook_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_132_evidence")));FOCUSED_COMMANDS:Final=tuple(i[0]for i in COMMANDS[:3]);IMPLEMENTED:Final={"profile_count":9,"mutation_case_count":3600,"retry_case_count":3150,"unauthorized_effect_count":0,"duplicate_delivery_count":0,"removal_authority_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-131-BLOCKED","owner":"132"},{"code":"BLOCKED_EXTERNAL","platform":"Microsoft Graph Outlook/Exchange test tenants and mailboxes","artifact":"untouched native provider conformance, security, accessibility, and removal evidence","action":"provision exact tenants/accounts/mailboxes/credentials and run AT-COM-001, AT-M365-001, RV-23 through RV-26 and RV-31 native campaigns","credential":"Microsoft Graph delegated and application credentials","payment":"Microsoft 365 tenant or provider costs if applicable"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"common_communications_contract_complete":True,"outlook_exact_effect_complete":True,"mutation_floor_complete":True,"retry_floor_complete":True,"removal_contract_complete":True,"native_provider_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_132_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprint_131_closed":False,"native_outlook_support_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=132,root=ROOT,output="artifacts/sprints/sprint-132/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-COM-001","AM-M365-001","AT-COM-001","AT-M365-001","SR-PRD-005","SR-PRD-006","RV-23","RV-24","RV-25","RV-26","RV-31"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
