#!/usr/bin/env python3
"""Build truthful Sprint 156 expanded checkpoint evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","README.md","PRD.md","Agent-Scaffolding-Inventory.md","TASKS.md","SECURITY-REVIEW.md","RUNTIME-BOUNDARIES.md","DELIVERY-SYSTEM.md","PRODUCTIVITY-SYSTEM.md","WINDOWS-BOUNDARIES.md","SECURITY.md","requirements/registry.json","requirements/traceability-report.json","architecture/status-model.json","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-156/expanded-release-checkpoint-corpus.json","scripts/expanded_release_checkpoint_contract.py","tests/test_expanded_release_checkpoint_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_156_evidence.py","tests/test_sprint_156_evidence.py")
COMMANDS:Final=(("expanded-checkpoint-contract",("python3","-m","unittest","tests.test_expanded_release_checkpoint_contract")),("traceability-currentness",("python3","scripts/traceability_report.py","--check")),("status-model-currentness",("python3","scripts/status_model.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_156_evidence")));FOCUSED_COMMANDS:Final=tuple(item[0]for item in COMMANDS[:3])
IMPLEMENTED:Final={"truth_document_count":10,"local_evidence_report_count":142,"blocker_case_count":512,"signed_manifest_count":0,"native_reproduction_count":0,"reviewer_signature_count":0,"user_approval_count":0,"release_package_count":0,"checkpoint_closure_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINTS-0-155-BLOCKED","owner":"156"},{"code":"BLOCKED_EXTERNAL","platform":"exact Fedora, Ubuntu, and Windows expanded release candidates, every promoted provider and credential, signing infrastructure, accessibility, performance, recovery, update, rollback, removal, strict-local, independent reproduction and review environments, and release owner approval","artifact":"untouched signed packages, source, binary, cryptographic and model BOMs, manifests, provenance, hashes, lifecycle, provider, AT, RV, accessibility, performance, recovery, removal, strict-local restoration, evidence indexes, reviewer signatures, user approval, and release notes","action":"satisfy every upstream Sprint 0-155 blocker, provision exact candidates and environments, rerun AT-GA-002 and every applicable AT, SR, and RV-01 through RV-35 campaign, obtain independent signatures and explicit release-owner approval, then sign only if every gate is green","credential":"all provider, platform, model, signing, instrumentation, reviewer, and release-owner credentials","payment":"provider, model, platform, hosting, signing, instrumentation, accessibility, performance, or review costs if applicable"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"requirement_graph_current":True,"documentation_truth_current":True,"summary_reconciliation_complete":True,"support_matrix_closed":True,"negative_release_gate_complete":True,"native_reproduction_complete":False,"signed_bom_complete":False,"rv01_35_complete":False,"at_ga_002_complete":False,"independent_review_complete":False,"user_approval_complete":False,"checkpoint_gate_closed":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_156_contract_passed":True,"sprint_status":"BLOCKED","upstream_sprints_closed":False,"g_ga_productivity_checkpoint_closed":False,"g_ga_closed":False,"release_package_produced":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=156,root=ROOT,output="artifacts/sprints/sprint-156/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-GAD-002","AT-GA-002","RV-01","RV-35"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
