#!/usr/bin/env python3
"""Build truthful Sprint 143 financial-import evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1];SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","TASKS.md","SECURITY-REVIEW.md","kernel/engine/src/lib.rs","kernel/engine/src/financial_domain.rs","kernel/engine/src/financial_import.rs","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","supply-chain/dependency-hashes.sha256","artifacts/sprints/sprint-143/import-corpus.json","scripts/financial_import_contract.py","tests/test_financial_import_contract.py","scripts/sprint_evidence_recorder.py","scripts/sprint_143_evidence.py","tests/test_sprint_143_evidence.py")
COMMANDS:Final=(("import-rust",("cargo","test","-p","agentmage-kernel-engine","financial_import::tests","--lib")),("import-corpus",("python3","-m","unittest","tests.test_financial_import_contract")),("dependency-boundary",("python3","scripts/dependency_rules.py")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("evidence-tests",("python3","-m","unittest","tests.test_sprint_143_evidence")));FOCUSED_COMMANDS:Final=tuple(item[0]for item in COMMANDS[:3]);IMPLEMENTED:Final={"format_count":3,"encoding_count":4,"mutation_family_count":14,"failure_family_count":10,"fixture_case_count":8400,"duplicate_record_count":0,"guessed_field_count":0,"source_mutation_count":0,"partial_state_count":0,"reconciliation_drift_count":0,"promotion_count":0};BLOCKERS:Final=({"code":"UPSTREAM-SPRINT-142-BLOCKED","owner":"143"},{"code":"BLOCKED_EXTERNAL","platform":"macOS arm64 and Windows 11 x86_64 native hosts with representative CSV, OFX, and QFX exports","artifact":"untouched native parser, encoding, filesystem, crash-recovery, byte-stability, and reviewer evidence","action":"provision exact hosts and representative exports, then run AT-FIMPORT-001 and RV-33 native campaigns","credential":"none","payment":"host or financial-export access costs if applicable"});VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"immutable_profiles_complete":True,"bounded_parser_complete":True,"matching_complete":True,"reconciliation_complete":True,"reimport_and_recovery_complete":True,"native_cross_platform_campaign_complete":False,"sprint_gate_closed":False};SUMMARY:Final={"local_sprint_143_contract_passed":True,"sprint_status":"BLOCKED","upstream_dependencies_closed":False,"native_import_support_promoted":False,"support_promotion_count":0}
DEFINITION:Final=SprintEvidenceDefinition(sprint=143,root=ROOT,output="artifacts/sprints/sprint-143/local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(),security_requirement_ids=("AM-FIMPORT-001","AT-FIMPORT-001","SR-FIN-001","SR-FIN-002","RV-33"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
