#!/usr/bin/env python3
"""Build truthful Story 95.4 local pod-composition evidence."""
from pathlib import Path
from typing import Final
try:from scripts.sprint_evidence_recorder import SprintEvidenceDefinition,main
except ModuleNotFoundError:from sprint_evidence_recorder import SprintEvidenceDefinition,main
ROOT:Final=Path(__file__).resolve().parents[1]
SOURCE_PATHS:Final=("Cargo.toml","Cargo.lock","kernel/engine/Cargo.toml","kernel/engine/src/lib.rs","kernel/engine/src/multi_agent.rs","kernel/engine/src/pod_composition.rs","artifacts/sprints/sprint-95/story-95.3-local-evidence-report.json","artifacts/sprints/sprint-95/pod-composition-corpus.json","scripts/pod_composition_contract.py","tests/test_pod_composition_contract.py","supply-chain/dependency-hashes.sha256","supply-chain/dependency-provenance.json","supply-chain/sbom.cdx.json","scripts/sprint_evidence_recorder.py","scripts/story_95_4_evidence.py","tests/test_story_95_4_evidence.py")
COMMANDS:Final=(("pod-composition-rust-contract",("cargo","test","-p","agentmage-kernel-engine","pod_composition::tests","--lib")),("multi-agent-rust-contract",("cargo","test","-p","agentmage-kernel-engine","multi_agent::tests","--lib")),("pod-composition-artifact-contract",("python3","-m","unittest","tests.test_pod_composition_contract")),("supply-chain-currentness",("python3","scripts/supply_chain.py")),("product-ci-contract",("python3","scripts/product_ci.py","--check")),("evidence-tests",("python3","-m","unittest","tests.test_story_95_4_evidence")))
FOCUSED_COMMANDS:Final=tuple(i[0] for i in COMMANDS[:3]);IMPLEMENTED:Final={"attack_recovery_class_count":15,"case_count":60,"max_worker_count":5,"single_agent_mode_count":1,"enabled_pod_count":0,"native_worker_count":0}
BLOCKERS:Final=({"code":"UPSTREAM-STORIES-95.1-95.3-BLOCKED","owner":"95.4"},{"code":"NATIVE-POD-COMPOSITION-AND-INDEPENDENT-REVIEW-ABSENT","owner":"95.4-native"})
VERIFICATION:Final={"focused_local_contracts":True,"focused_blocking_skip_count":0,"case_count":60,"serialized_integration":True,"single_agent_mode_preserved":True,"native_worker_count":0,"independent_review":False,"story_gate_closed":False}
SUMMARY:Final={"local_story_95_4_contract_passed":True,"sprint_status":"BLOCKED","upstream_stories_closed":False,"native_pod_complete":False,"independent_review_present":False,"release_approval":False}
DEFINITION:Final=SprintEvidenceDefinition(sprint=95,root=ROOT,output="artifacts/sprints/sprint-95/story-95.4-local-evidence-report.json",source_paths=SOURCE_PATHS,commands=COMMANDS,focused_commands=FOCUSED_COMMANDS,rust_focused_commands=frozenset(FOCUSED_COMMANDS[:2]),security_requirement_ids=("SR-GOV-010","SR-ACC-001","SR-ACC-002","SR-ACC-003","SR-ACC-004","SR-ACC-005","SR-ACC-006","SR-ACC-007","SR-ACC-008","SR-AI-003","SR-AI-004","SR-AI-005","SR-AI-009","SR-AI-010","SR-TST-005","SR-TST-006","SR-TST-011"),implemented_contracts=IMPLEMENTED,verification_evidence=VERIFICATION,blockers=BLOCKERS,summary=SUMMARY)
if __name__=="__main__":raise SystemExit(main(DEFINITION))
